# Advanced Broadcasting, Conditional Logic, and Custom Vectorized Functions

In [2]:

import pandas as pd
import numpy as np

data = {
    'customer_id': range(101, 116),
    'name': [
        'Aarav', 'Priya', 'Rahul', 'Sneha', 'Vikram',
        'Ananya', 'Rohan', 'Neha', 'Karan', 'Isha',
        'Arjun', 'Meera', 'Dev', 'Kavya', 'Aditi'
    ],
    'city': [
        'Delhi', 'Mumbai', 'Bangalore', 'Delhi', 'Mumbai',
        'Bangalore', 'Pune', 'Delhi', 'Mumbai', 'Pune',
        'Bangalore', 'Delhi', 'Pune', 'Mumbai', 'Bangalore'
    ],
    'age': [
        24, 31, 28, 42, 35,
        26, 39, 22, 45, 33,
        29, 37, 41, 27, 30
    ],
    'income': [
        25000, 45000, 70000, 18000, 85000,
        55000, 32000, 0, 95000, 42000,
        -5000, 60000, 28000, 75000, np.nan
    ],
    'spending': [
        8000, 18000, 30000, 5000, 45000,
        22000, 12000, 7000, 110000, 25000,
        15000, 35000, -2000, 27000, 16000
    ],
    'savings': [
        5000, 15000, 30000, 8000, 40000,
        22000, 12000, 0, 50000, 18000,
        -1000, 26000, 9000, 35000, np.nan
    ],
    'monthly_expenses': [
        12000, 22000, 35000, 10000, 40000,
        28000, 18000, 6000, 45000, 25000,
        15000, 30000, 14000, 32000, 20000
    ]
}

df = pd.DataFrame(data)

df

,customer_id,name,city,age,income,spending,savings,monthly_expenses
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000
7,108,Neha,Delhi,22,0.0,7000,0.0,6000
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000

#### Q1. City-based bonus using vectorization
Create a city_bonus column using these rules:
- Delhi: 5,000
- Mumbai: 7,000
- Bangalore: 6,000
- All other cities: 2,000

In [4]:
conditions=[
    df['city']=='Delhi',
    df['city']=='Mumbai',
    df['city']=='Bangalore'
    
]
bonus=[5000,7000,6000]
df['city_bonus']=np.select(conditions,bonus,default=2000)
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000

#### Q2. Scale income using broadcasting
Create adjusted_income by increasing each customer's income by 10%.

Then create income_after_expenses by subtracting a fixed expense of 5,000 from each adjusted income.

In [6]:
df['adjusted_income']=df['income']*1.1
df['income_after_expenses']=df['adjusted_income']-5000
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN

#### Q3. Create spending tiers
Create a spending_tier column using these rules:
- Spending below 10,000: Low
- Spending from 10,000 to below 25,000: Medium
- Spending of 25,000 or above: High

In [8]:
conditions=[
    df['spending']<10000,
    df['spending'].between(10000,25000),
    df['spending']>25000
]
labels=['Low','Medium','High']
df['spending_tier']=np.select(conditions,labels)
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses,spending_tier
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0,Low
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0,Medium
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0,High
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0,Low
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0,High
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0,Medium
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0,Medium
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0,Low
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0,High
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0,Medium
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0,Medium
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0,High
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0,Low
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0,High
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN,Medium

#### Q4. Conditional tax calculation
Create a tax column using these rules:
- Income below 30,000: 0% tax
- Income from 30,000 to below 70,000: 10% tax
- Income of 70,000 or above: 20% tax
The tax is calculated on the customer's full income, not just the amount above each threshold.

In [10]:
conditions=[
    df['income']<30000,
    df['income'].between(30000,70000),
    df['income']>70000
    
]
tax_applied=[0,10,20]
df['tax']=np.select(conditions,tax_applied)

df['tax_on_income']=(df['income']*df['tax'])/100
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses,spending_tier,tax,tax_on_income
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0,Low,0,0.0
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0,Medium,10,4500.0
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0,High,10,7000.0
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0,Low,0,0.0
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0,High,20,17000.0
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0,Medium,10,5500.0
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0,Medium,10,3200.0
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0,Low,0,0.0
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0,High,20,19000.0
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0,Medium,10,4200.0
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0,Medium,0,-0.0
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0,High,10,6000.0
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0,Low,0,0.0
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0,High,20,15000.0
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN,Medium,0,NaN

#### Q5. Calculate savings contributions
Create monthly_contribution equal to 15% of savings for customers whose savings are at least 20,000. For everyone else, assign 5% of savings.

In [12]:
df['monthly_contribution']=(df['savings']*0.15).where(df['savings']>=20000,df['savings']*0.05)
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses,spending_tier,tax,tax_on_income,monthly_contribution
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0,Low,0,0.0,250.0
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0,Medium,10,4500.0,750.0
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0,High,10,7000.0,4500.0
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0,Low,0,0.0,400.0
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0,High,20,17000.0,6000.0
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0,Medium,10,5500.0,3300.0
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0,Medium,10,3200.0,600.0
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0,Low,0,0.0,0.0
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0,High,20,19000.0,7500.0
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0,Medium,10,4200.0,900.0
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0,Medium,0,-0.0,-50.0
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0,High,10,6000.0,3900.0
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0,Low,0,0.0,450.0
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0,High,20,15000.0,5250.0
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN,Medium,0,NaN,NaN

#### Q6. City-average comparison
Calculate the average income for each city and create a Boolean column, above_city_average, indicating whether each customer's income is greater than their city's average income.

In [14]:
df['above_city_average']=df['income']>df.groupby('city')['income'].transform('mean')
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses,spending_tier,tax,tax_on_income,monthly_contribution,above_city_average
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0,Low,0,0.0,250.0,False
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0,Medium,10,4500.0,750.0,False
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0,High,10,7000.0,4500.0,True
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0,Low,0,0.0,400.0,False
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0,High,20,17000.0,6000.0,True
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0,Medium,10,5500.0,3300.0,True
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0,Medium,10,3200.0,600.0,False
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0,Low,0,0.0,0.0,False
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0,High,20,19000.0,7500.0,True
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0,Medium,10,4200.0,900.0,True
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0,Medium,0,-0.0,-50.0,False
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0,High,10,6000.0,3900.0,True
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0,Low,0,0.0,450.0,False
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0,High,20,15000.0,5250.0,False
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN,Medium,0,NaN,NaN,False

#### Q7. Clip extreme spending values
Create spending_clipped by limiting spending to a minimum of 0 and a maximum of 100,000.

In [16]:
df['spending_clipped']=df['spending'].clip(lower=0,upper=100000)
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses,spending_tier,tax,tax_on_income,monthly_contribution,above_city_average,spending_clipped
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0,Low,0,0.0,250.0,False,8000
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0,Medium,10,4500.0,750.0,False,18000
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0,High,10,7000.0,4500.0,True,30000
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0,Low,0,0.0,400.0,False,5000
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0,High,20,17000.0,6000.0,True,45000
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0,Medium,10,5500.0,3300.0,True,22000
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0,Medium,10,3200.0,600.0,False,12000
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0,Low,0,0.0,0.0,False,7000
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0,High,20,19000.0,7500.0,True,100000
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0,Medium,10,4200.0,900.0,True,25000
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0,Medium,0,-0.0,-50.0,False,15000
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0,High,10,6000.0,3900.0,True,35000
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0,Low,0,0.0,450.0,False,0
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0,High,20,15000.0,5250.0,False,27000
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN,Medium,0,NaN,NaN,False,16000

#### Q8. Safe vectorized division
Create spending_ratio by dividing spending by income.

If income is zero or negative, the result must be NaN. Avoid division-by-zero problems and unnecessary row-wise operations.

In [18]:
df['spending_ratio']=df['spending']/df['income'].where(df['income']>0,np.nan)
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses,spending_tier,tax,tax_on_income,monthly_contribution,above_city_average,spending_clipped,spending_ratio
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0,Low,0,0.0,250.0,False,8000,0.320000
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0,Medium,10,4500.0,750.0,False,18000,0.400000
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0,High,10,7000.0,4500.0,True,30000,0.428571
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0,Low,0,0.0,400.0,False,5000,0.277778
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0,High,20,17000.0,6000.0,True,45000,0.529412
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0,Medium,10,5500.0,3300.0,True,22000,0.400000
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0,Medium,10,3200.0,600.0,False,12000,0.375000
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0,Low,0,0.0,0.0,False,7000,NaN
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0,High,20,19000.0,7500.0,True,100000,1.157895
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0,Medium,10,4200.0,900.0,True,25000,0.595238
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0,Medium,0,-0.0,-50.0,False,15000,NaN
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0,High,10,6000.0,3900.0,True,35000,0.583333
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0,Low,0,0.0,450.0,False,0,-0.071429
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0,High,20,15000.0,5250.0,False,27000,0.360000
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN,Medium,0,NaN,NaN,False,16000,NaN

#### Q9. Validate a transformation pipeline
Create valid_income by replacing zero and negative income values with NaN.

Then create income_category:
- Below 25,000: Low
- From 25,000 to below 60,000: Medium
- 60,000 or above: High

In [20]:
df['valid_income'] = df['income'].where(df['income'] > 0, np.nan)
conditions=[
    df['valid_income']<25000,
    df['valid_income'].between(25000,60000),
    df['valid_income']>60000
]
labels=['Low','Medium','High']
df['income_category']=np.select(conditions,labels,default='n/a')
df

,customer_id,name,city,age,income,spending,savings,monthly_expenses,city_bonus,adjusted_income,income_after_expenses,spending_tier,tax,tax_on_income,monthly_contribution,above_city_average,spending_clipped,spending_ratio,valid_income,income_category
0,101,Aarav,Delhi,24,25000.0,8000,5000.0,12000,5000,27500.0,22500.0,Low,0,0.0,250.0,False,8000,0.320000,25000.0,Medium
1,102,Priya,Mumbai,31,45000.0,18000,15000.0,22000,7000,49500.0,44500.0,Medium,10,4500.0,750.0,False,18000,0.400000,45000.0,Medium
2,103,Rahul,Bangalore,28,70000.0,30000,30000.0,35000,6000,77000.0,72000.0,High,10,7000.0,4500.0,True,30000,0.428571,70000.0,High
3,104,Sneha,Delhi,42,18000.0,5000,8000.0,10000,5000,19800.0,14800.0,Low,0,0.0,400.0,False,5000,0.277778,18000.0,Low
4,105,Vikram,Mumbai,35,85000.0,45000,40000.0,40000,7000,93500.0,88500.0,High,20,17000.0,6000.0,True,45000,0.529412,85000.0,High
5,106,Ananya,Bangalore,26,55000.0,22000,22000.0,28000,6000,60500.0,55500.0,Medium,10,5500.0,3300.0,True,22000,0.400000,55000.0,Medium
6,107,Rohan,Pune,39,32000.0,12000,12000.0,18000,2000,35200.0,30200.0,Medium,10,3200.0,600.0,False,12000,0.375000,32000.0,Medium
7,108,Neha,Delhi,22,0.0,7000,0.0,6000,5000,0.0,-5000.0,Low,0,0.0,0.0,False,7000,NaN,NaN,n/a
8,109,Karan,Mumbai,45,95000.0,110000,50000.0,45000,7000,104500.0,99500.0,High,20,19000.0,7500.0,True,100000,1.157895,95000.0,High
9,110,Isha,Pune,33,42000.0,25000,18000.0,25000,2000,46200.0,41200.0,Medium,10,4200.0,900.0,True,25000,0.595238,42000.0,Medium
10,111,Arjun,Bangalore,29,-5000.0,15000,-1000.0,15000,6000,-5500.0,-10500.0,Medium,0,-0.0,-50.0,False,15000,NaN,NaN,n/a
11,112,Meera,Delhi,37,60000.0,35000,26000.0,30000,5000,66000.0,61000.0,High,10,6000.0,3900.0,True,35000,0.583333,60000.0,Medium
12,113,Dev,Pune,41,28000.0,-2000,9000.0,14000,2000,30800.0,25800.0,Low,0,0.0,450.0,False,0,-0.071429,28000.0,Medium
13,114,Kavya,Mumbai,27,75000.0,27000,35000.0,32000,7000,82500.0,77500.0,High,20,15000.0,5250.0,False,27000,0.360000,75000.0,High
14,115,Aditi,Bangalore,30,NaN,16000,NaN,20000,6000,NaN,NaN,Medium,0,NaN,NaN,False,16000,NaN,NaN,n/a

#### Q10. Mini-project — Customer financial features
Using vectorized operations, create these four columns:
1. savings_category: below 10,000 = Low Savings; 10,000 to below 25,000 = Moderate Savings; 25,000 or above = High Savings.
2. income_to_savings_ratio: income divided by savings, with zero or negative savings resulting in NaN.
3. financial_status: Strong if income is at least 50,000 and savings are at least 20,000; otherwise Needs Review. Invalid income or savings should result in a missing status.
4. monthly_savings_target: 20% of income for customers with savings below 10,000, and 10% of income for everyone else with valid income.