# Advanced GroupBy, agg(), transform() and filter()

In [2]:
import pandas as pd
import numpy as np

data = {
    "order_id": range(3001, 3031),
    "customer_id": [
        401, 402, 403, 404, 405, 406, 407, 408, 409, 410,
        401, 402, 403, 404, 405, 406, 407, 408, 409, 410,
        411, 412, 413, 414, 415, 411, 412, 413, 414, 415
    ],
    "city": [
        "Delhi", "Mumbai", "Delhi", "Pune", "Mumbai",
        "Bangalore", "Pune", "Delhi", "Mumbai", "Bangalore",
        "Delhi", "Mumbai", "Delhi", "Pune", "Mumbai",
        "Bangalore", "Pune", "Delhi", "Mumbai", "Bangalore",
        "Pune", "Delhi", "Bangalore", "Mumbai", "Pune",
        "Delhi", "Mumbai", "Bangalore", "Delhi", "Pune"
    ],
    "category": [
        "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics", "Clothing",
        "Furniture", "Electronics"
    ],
    "sales": [
        25000, 8000, 15000, 12000, 6000,
        18000, 14000, 5000, 22000, 9000,
        30000, 11000, 20000, 16000, 7500,
        24000, 13000, np.nan, 19000, 10000,
        17000, 4500, 28000, 12000, 6500,
        21000, 16000, 7000, 26000, 11000
    ],
    "quantity": [
        3, 2, 1, 2, 4, 3, 2, 1, 3, 2,
        4, 3, 2, 1, 2, 4, 2, 3, 2, 1,
        2, 1, 4, 2, 3, 3, 2, 1, 4, 2
    ],
    "discount_pct": [
        5, 10, 0, 15, 10, 5, 20, 0, 5, 10,
        0, 15, 5, 10, 20, 5, 10, 5, 0, 15,
        10, 0, 5, 10, 15, 5, 10, 20, 0, 5
    ],
    "order_status": [
        "Completed", "Completed", "Cancelled", "Completed",
        "Completed", "Completed", "Cancelled", "Completed",
        "Completed", "Cancelled", "Completed", "Completed",
        "Completed", "Cancelled", "Completed", "Completed",
        "Completed", "Completed", "Cancelled", "Completed",
        "Completed", "Cancelled", "Completed", "Completed",
        "Completed", "Completed", "Cancelled", "Completed",
        "Completed", "Completed"
    ]
}

df = pd.DataFrame(data)

df

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled
3,3004,404,Pune,Electronics,12000.0,2,15,Completed
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed
16,3017,407,Pune,Furniture,13000.0,2,10,Completed
17,3018,408,Delhi,Electronics,NaN,3,5,Completed
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed
20,3021,411,Pune,Electronics,17000.0,2,10,Completed
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed
24,3025,415,Pune,Clothing,6500.0,3,15,Completed
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed
29,3030,415,Pune,Electronics,11000.0,2,5,Completed

In [4]:
df.isnull().sum()

order_id        0
customer_id     0
city            0
category        0
sales           1
quantity        0
discount_pct    0
order_status    0
dtype: int64

#### Q1. Transform: City-average sales
Create a new column city_avg_sales containing the average sales for the corresponding city on every row.

Requirements:
- Use groupby() with transform().
- Preserve the original row count and index.
- Missing sales should be handled using pandas' normal mean behavior.

In [7]:
df['city_avg_sales']=df.groupby('city')['sales'].transform('mean')
df

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286
17,3018,408,Delhi,Electronics,NaN,3,5,Completed,18312.500000
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286

#### Q2. Transform: Deviation from city average
Create sales_vs_city_avg by subtracting the city-average sales from each order's sales.

Formula:

sales_vs_city_avg = sales - city_avg_sales

Requirements:
- Use vectorized operations.
- Preserve missing sales as missing.
- Interpret positive and negative values.

In [10]:
df['sales_vs_city_avg']=df['sales']-df['city_avg_sales']
df

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000,6687.500000
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000,-4687.500000
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000,-3312.500000
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286,-785.714286
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000,-6687.500000
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000,2000.000000
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286,1214.285714
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000,-13312.500000
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000,9312.500000
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000,-7000.000000
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000,11687.500000
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000,-1687.500000
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000,1687.500000
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286,3214.285714
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000,-5187.500000
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000,8000.000000
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286,214.285714
17,3018,408,Delhi,Electronics,NaN,3,5,Completed,18312.500000,NaN
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000,6312.500000
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000,-6000.000000
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286,4214.285714
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000,-13812.500000
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000,12000.000000
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000,-687.500000
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286,-6285.714286
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000,2687.500000
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000,3312.500000
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000,-9000.000000
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000,7687.500000
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286,-1785.714286

#### Q3. Multiple transformations by category
Create these columns:
- category_avg_sales: category-average sales.
- category_total_quantity: total quantity within the category.
- category_order_count: number of rows within the category.
Use transform() so each result aligns with the original DataFrame.

In [13]:
df['category_avg_sales']=df.groupby('category')['sales'].transform('mean')
df['category_total_quantity']=df.groupby('category')['quantity'].transform('sum')
df['category_order_count']=df.groupby('category')['order_id'].transform('count')

#### Q4. Filter high-performing cities
Return only cities whose total valid sales exceed 100,000.

Requirements:
- Use groupby() and filter().
- Keep the original rows belonging to qualifying cities.
- Store the filtered DataFrame in high_sales_cities.

In [24]:
dff = df.dropna(subset=['sales']).copy()
dff

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg,category_avg_sales,category_total_quantity,category_order_count
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000,6687.500000,14350.000000,24,11
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000,-4687.500000,10111.111111,21,9
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000,-3312.500000,19900.000000,26,10
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286,-785.714286,14350.000000,24,11
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000,-6687.500000,10111.111111,21,9
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000,2000.000000,19900.000000,26,10
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286,1214.285714,14350.000000,24,11
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000,-13312.500000,10111.111111,21,9
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000,9312.500000,19900.000000,26,10
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000,-7000.000000,14350.000000,24,11
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000,11687.500000,19900.000000,26,10
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000,-1687.500000,10111.111111,21,9
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000,1687.500000,14350.000000,24,11
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286,3214.285714,19900.000000,26,10
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000,-5187.500000,14350.000000,24,11
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000,8000.000000,10111.111111,21,9
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286,214.285714,19900.000000,26,10
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000,6312.500000,10111.111111,21,9
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000,-6000.000000,19900.000000,26,10
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286,4214.285714,14350.000000,24,11
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000,-13812.500000,10111.111111,21,9
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000,12000.000000,19900.000000,26,10
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000,-687.500000,14350.000000,24,11
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286,-6285.714286,10111.111111,21,9
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000,2687.500000,19900.000000,26,10
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000,3312.500000,14350.000000,24,11
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000,-9000.000000,10111.111111,21,9
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000,7687.500000,19900.000000,26,10
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286,-1785.714286,14350.000000,24,11

In [26]:
high_sales_cities = dff.groupby('city').filter(
    lambda group: group['sales'].sum() > 100000
)
high_sales_cities

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg,category_avg_sales,category_total_quantity,category_order_count
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.5,6687.5,14350.000000,24,11
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.5,-4687.5,10111.111111,21,9
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.5,-3312.5,19900.000000,26,10
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.5,-6687.5,10111.111111,21,9
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.5,-13312.5,10111.111111,21,9
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.5,9312.5,19900.000000,26,10
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.5,11687.5,19900.000000,26,10
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.5,-1687.5,10111.111111,21,9
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.5,1687.5,14350.000000,24,11
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.5,-5187.5,14350.000000,24,11
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.5,6312.5,10111.111111,21,9
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.5,-13812.5,10111.111111,21,9
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.5,-687.5,14350.000000,24,11
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.5,2687.5,19900.000000,26,10
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.5,3312.5,14350.000000,24,11
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.5,7687.5,19900.000000,26,10

#### Q5. Filter categories by order volume
Keep only categories with at least eight orders.

Requirements:
- Use groupby() and filter().
- Count rows, not non-missing sales.
- Store the result in high_volume_categories.

In [33]:
high_volume_categories = df.groupby('category').filter(
    lambda group: len(group) >= 8
)
high_volume_categories

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg,category_avg_sales,category_total_quantity,category_order_count
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000,6687.500000,14350.000000,24,11
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000,-4687.500000,10111.111111,21,9
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000,-3312.500000,19900.000000,26,10
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286,-785.714286,14350.000000,24,11
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000,-6687.500000,10111.111111,21,9
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000,2000.000000,19900.000000,26,10
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286,1214.285714,14350.000000,24,11
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000,-13312.500000,10111.111111,21,9
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000,9312.500000,19900.000000,26,10
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000,-7000.000000,14350.000000,24,11
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000,11687.500000,19900.000000,26,10
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000,-1687.500000,10111.111111,21,9
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000,1687.500000,14350.000000,24,11
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286,3214.285714,19900.000000,26,10
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000,-5187.500000,14350.000000,24,11
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000,8000.000000,10111.111111,21,9
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286,214.285714,19900.000000,26,10
17,3018,408,Delhi,Electronics,NaN,3,5,Completed,18312.500000,NaN,14350.000000,24,11
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000,6312.500000,10111.111111,21,9
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000,-6000.000000,19900.000000,26,10
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286,4214.285714,14350.000000,24,11
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000,-13812.500000,10111.111111,21,9
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000,12000.000000,19900.000000,26,10
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000,-687.500000,14350.000000,24,11
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286,-6285.714286,10111.111111,21,9
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000,2687.500000,19900.000000,26,10
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000,3312.500000,14350.000000,24,11
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000,-9000.000000,10111.111111,21,9
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000,7687.500000,19900.000000,26,10
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286,-1785.714286,14350.000000,24,11

#### Q6. Group-wise percentage contribution
Create category_sales_share showing each order's sales as a percentage of the total valid sales for its category.

Formula:

sales / category_total_sales * 100

Requirements:
- Use transform() for the category total.
- Handle missing sales.
- Avoid division by zero.

In [38]:
category_total_sales = df.groupby('category')['sales'].transform('sum')

df['category_sales_share'] = (
    df['sales'] / category_total_sales.where(category_total_sales != 0, np.nan)
) * 100
df

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg,category_avg_sales,category_total_quantity,category_order_count,category_sales_share
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000,6687.500000,14350.000000,24,11,17.421603
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000,-4687.500000,10111.111111,21,9,8.791209
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000,-3312.500000,19900.000000,26,10,7.537688
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286,-785.714286,14350.000000,24,11,8.362369
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000,-6687.500000,10111.111111,21,9,6.593407
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000,2000.000000,19900.000000,26,10,9.045226
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286,1214.285714,14350.000000,24,11,9.756098
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000,-13312.500000,10111.111111,21,9,5.494505
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000,9312.500000,19900.000000,26,10,11.055276
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000,-7000.000000,14350.000000,24,11,6.271777
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000,11687.500000,19900.000000,26,10,15.075377
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000,-1687.500000,10111.111111,21,9,12.087912
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000,1687.500000,14350.000000,24,11,13.937282
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286,3214.285714,19900.000000,26,10,8.040201
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000,-5187.500000,14350.000000,24,11,5.226481
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000,8000.000000,10111.111111,21,9,26.373626
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286,214.285714,19900.000000,26,10,6.532663
17,3018,408,Delhi,Electronics,NaN,3,5,Completed,18312.500000,NaN,14350.000000,24,11,NaN
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000,6312.500000,10111.111111,21,9,20.879121
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000,-6000.000000,19900.000000,26,10,5.025126
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286,4214.285714,14350.000000,24,11,11.846690
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000,-13812.500000,10111.111111,21,9,4.945055
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000,12000.000000,19900.000000,26,10,14.070352
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000,-687.500000,14350.000000,24,11,8.362369
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286,-6285.714286,10111.111111,21,9,7.142857
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000,2687.500000,19900.000000,26,10,10.552764
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000,3312.500000,14350.000000,24,11,11.149826
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000,-9000.000000,10111.111111,21,9,7.692308
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000,7687.500000,19900.000000,26,10,13.065327
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286,-1785.714286,14350.000000,24,11,7.665505

#### Q7. Rank orders within each city
Create sales_rank_in_city ranking sales from highest to lowest within each city.

Requirements:
- Use groupby() and rank().
- Highest sales should receive rank 1.
- Use method="dense" for ties.
- Missing sales should retain missing ranks.

In [41]:
df['sales_rank_in_city']=df.groupby('city')['sales'].rank(method='dense',ascending=False)
df

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg,category_avg_sales,category_total_quantity,category_order_count,category_sales_share,sales_rank_in_city
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000,6687.500000,14350.000000,24,11,17.421603,3.0
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000,-4687.500000,10111.111111,21,9,8.791209,6.0
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000,-3312.500000,19900.000000,26,10,7.537688,6.0
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286,-785.714286,14350.000000,24,11,8.362369,5.0
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000,-6687.500000,10111.111111,21,9,6.593407,8.0
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000,2000.000000,19900.000000,26,10,9.045226,3.0
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286,1214.285714,14350.000000,24,11,9.756098,3.0
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000,-13312.500000,10111.111111,21,9,5.494505,7.0
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000,9312.500000,19900.000000,26,10,11.055276,1.0
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000,-7000.000000,14350.000000,24,11,6.271777,5.0
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000,11687.500000,19900.000000,26,10,15.075377,1.0
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000,-1687.500000,10111.111111,21,9,12.087912,5.0
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000,1687.500000,14350.000000,24,11,13.937282,5.0
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286,3214.285714,19900.000000,26,10,8.040201,2.0
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000,-5187.500000,14350.000000,24,11,5.226481,7.0
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000,8000.000000,10111.111111,21,9,26.373626,2.0
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286,214.285714,19900.000000,26,10,6.532663,4.0
17,3018,408,Delhi,Electronics,NaN,3,5,Completed,18312.500000,NaN,14350.000000,24,11,NaN,NaN
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000,6312.500000,10111.111111,21,9,20.879121,2.0
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000,-6000.000000,19900.000000,26,10,5.025126,4.0
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286,4214.285714,14350.000000,24,11,11.846690,1.0
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000,-13812.500000,10111.111111,21,9,4.945055,8.0
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000,12000.000000,19900.000000,26,10,14.070352,1.0
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000,-687.500000,14350.000000,24,11,8.362369,4.0
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286,-6285.714286,10111.111111,21,9,7.142857,7.0
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000,2687.500000,19900.000000,26,10,10.552764,4.0
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000,3312.500000,14350.000000,24,11,11.149826,3.0
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000,-9000.000000,10111.111111,21,9,7.692308,6.0
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000,7687.500000,19900.000000,26,10,13.065327,2.0
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286,-1785.714286,14350.000000,24,11,7.665505,6.0

#### Q8. Calculate within-city cumulative sales
Create cumulative_sales_by_city using cumulative sales within each city.

Requirements:
- Sort orders by order_id before calculating the cumulative sum.
- Use groupby() and cumsum().
- Preserve the original DataFrame unchanged.
- Explain how missing sales affect the cumulative result.

In [50]:
dff = df.sort_values('order_id').copy()
dff['cumulative_sales_by_city']=df.groupby('city')['sales'].cumsum()
dff

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg,category_avg_sales,category_total_quantity,category_order_count,category_sales_share,sales_rank_in_city,cumulative_sales_by_city
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000,6687.500000,14350.000000,24,11,17.421603,3.0,25000.0
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000,-4687.500000,10111.111111,21,9,8.791209,6.0,8000.0
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000,-3312.500000,19900.000000,26,10,7.537688,6.0,40000.0
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286,-785.714286,14350.000000,24,11,8.362369,5.0,12000.0
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000,-6687.500000,10111.111111,21,9,6.593407,8.0,14000.0
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000,2000.000000,19900.000000,26,10,9.045226,3.0,18000.0
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286,1214.285714,14350.000000,24,11,9.756098,3.0,26000.0
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000,-13312.500000,10111.111111,21,9,5.494505,7.0,45000.0
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000,9312.500000,19900.000000,26,10,11.055276,1.0,36000.0
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000,-7000.000000,14350.000000,24,11,6.271777,5.0,27000.0
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000,11687.500000,19900.000000,26,10,15.075377,1.0,75000.0
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000,-1687.500000,10111.111111,21,9,12.087912,5.0,47000.0
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000,1687.500000,14350.000000,24,11,13.937282,5.0,95000.0
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286,3214.285714,19900.000000,26,10,8.040201,2.0,42000.0
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000,-5187.500000,14350.000000,24,11,5.226481,7.0,54500.0
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000,8000.000000,10111.111111,21,9,26.373626,2.0,51000.0
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286,214.285714,19900.000000,26,10,6.532663,4.0,55000.0
17,3018,408,Delhi,Electronics,NaN,3,5,Completed,18312.500000,NaN,14350.000000,24,11,NaN,NaN,NaN
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000,6312.500000,10111.111111,21,9,20.879121,2.0,73500.0
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000,-6000.000000,19900.000000,26,10,5.025126,4.0,61000.0
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286,4214.285714,14350.000000,24,11,11.846690,1.0,72000.0
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000,-13812.500000,10111.111111,21,9,4.945055,8.0,99500.0
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000,12000.000000,19900.000000,26,10,14.070352,1.0,89000.0
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000,-687.500000,14350.000000,24,11,8.362369,4.0,85500.0
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286,-6285.714286,10111.111111,21,9,7.142857,7.0,78500.0
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000,2687.500000,19900.000000,26,10,10.552764,4.0,120500.0
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000,3312.500000,14350.000000,24,11,11.149826,3.0,101500.0
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000,-9000.000000,10111.111111,21,9,7.692308,6.0,96000.0
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000,7687.500000,19900.000000,26,10,13.065327,2.0,146500.0
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286,-1785.714286,14350.000000,24,11,7.665505,6.0,89500.0

#### Q9. Compare each order with its category median
Create above_category_median as a Boolean column indicating whether each order's sales exceed its category's median sales.

Requirements:
- Calculate the category median using transform("median").
- Return missing results for rows with missing sales.
- Do not use row-wise apply().

In [53]:
df['category_median']=df.groupby('category')['sales'].transform('median')
df['above_category_median']=df['sales']>df['category_median']
df

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,city_avg_sales,sales_vs_city_avg,category_avg_sales,category_total_quantity,category_order_count,category_sales_share,sales_rank_in_city,category_median,above_category_median
0,3001,401,Delhi,Electronics,25000.0,3,5,Completed,18312.500000,6687.500000,14350.000000,24,11,17.421603,3.0,13000.0,True
1,3002,402,Mumbai,Clothing,8000.0,2,10,Completed,12687.500000,-4687.500000,10111.111111,21,9,8.791209,6.0,7000.0,True
2,3003,403,Delhi,Furniture,15000.0,1,0,Cancelled,18312.500000,-3312.500000,19900.000000,26,10,7.537688,6.0,19500.0,False
3,3004,404,Pune,Electronics,12000.0,2,15,Completed,12785.714286,-785.714286,14350.000000,24,11,8.362369,5.0,13000.0,False
4,3005,405,Mumbai,Clothing,6000.0,4,10,Completed,12687.500000,-6687.500000,10111.111111,21,9,6.593407,8.0,7000.0,False
5,3006,406,Bangalore,Furniture,18000.0,3,5,Completed,16000.000000,2000.000000,19900.000000,26,10,9.045226,3.0,19500.0,False
6,3007,407,Pune,Electronics,14000.0,2,20,Cancelled,12785.714286,1214.285714,14350.000000,24,11,9.756098,3.0,13000.0,True
7,3008,408,Delhi,Clothing,5000.0,1,0,Completed,18312.500000,-13312.500000,10111.111111,21,9,5.494505,7.0,7000.0,False
8,3009,409,Mumbai,Furniture,22000.0,3,5,Completed,12687.500000,9312.500000,19900.000000,26,10,11.055276,1.0,19500.0,True
9,3010,410,Bangalore,Electronics,9000.0,2,10,Cancelled,16000.000000,-7000.000000,14350.000000,24,11,6.271777,5.0,13000.0,False
10,3011,401,Delhi,Furniture,30000.0,4,0,Completed,18312.500000,11687.500000,19900.000000,26,10,15.075377,1.0,19500.0,True
11,3012,402,Mumbai,Clothing,11000.0,3,15,Completed,12687.500000,-1687.500000,10111.111111,21,9,12.087912,5.0,7000.0,True
12,3013,403,Delhi,Electronics,20000.0,2,5,Completed,18312.500000,1687.500000,14350.000000,24,11,13.937282,5.0,13000.0,True
13,3014,404,Pune,Furniture,16000.0,1,10,Cancelled,12785.714286,3214.285714,19900.000000,26,10,8.040201,2.0,19500.0,False
14,3015,405,Mumbai,Electronics,7500.0,2,20,Completed,12687.500000,-5187.500000,14350.000000,24,11,5.226481,7.0,13000.0,False
15,3016,406,Bangalore,Clothing,24000.0,4,5,Completed,16000.000000,8000.000000,10111.111111,21,9,26.373626,2.0,7000.0,True
16,3017,407,Pune,Furniture,13000.0,2,10,Completed,12785.714286,214.285714,19900.000000,26,10,6.532663,4.0,19500.0,False
17,3018,408,Delhi,Electronics,NaN,3,5,Completed,18312.500000,NaN,14350.000000,24,11,NaN,NaN,13000.0,False
18,3019,409,Mumbai,Clothing,19000.0,2,0,Cancelled,12687.500000,6312.500000,10111.111111,21,9,20.879121,2.0,7000.0,True
19,3020,410,Bangalore,Furniture,10000.0,1,15,Completed,16000.000000,-6000.000000,19900.000000,26,10,5.025126,4.0,19500.0,False
20,3021,411,Pune,Electronics,17000.0,2,10,Completed,12785.714286,4214.285714,14350.000000,24,11,11.846690,1.0,13000.0,True
21,3022,412,Delhi,Clothing,4500.0,1,0,Cancelled,18312.500000,-13812.500000,10111.111111,21,9,4.945055,8.0,7000.0,False
22,3023,413,Bangalore,Furniture,28000.0,4,5,Completed,16000.000000,12000.000000,19900.000000,26,10,14.070352,1.0,19500.0,True
23,3024,414,Mumbai,Electronics,12000.0,2,10,Completed,12687.500000,-687.500000,14350.000000,24,11,8.362369,4.0,13000.0,False
24,3025,415,Pune,Clothing,6500.0,3,15,Completed,12785.714286,-6285.714286,10111.111111,21,9,7.142857,7.0,7000.0,False
25,3026,411,Delhi,Furniture,21000.0,3,5,Completed,18312.500000,2687.500000,19900.000000,26,10,10.552764,4.0,19500.0,True
26,3027,412,Mumbai,Electronics,16000.0,2,10,Cancelled,12687.500000,3312.500000,14350.000000,24,11,11.149826,3.0,13000.0,True
27,3028,413,Bangalore,Clothing,7000.0,1,20,Completed,16000.000000,-9000.000000,10111.111111,21,9,7.692308,6.0,7000.0,False
28,3029,414,Delhi,Furniture,26000.0,4,0,Completed,18312.500000,7687.500000,19900.000000,26,10,13.065327,2.0,19500.0,True
29,3030,415,Pune,Electronics,11000.0,2,5,Completed,12785.714286,-1785.714286,14350.000000,24,11,7.665505,6.0,13000.0,False

#### Q10. Mini-project: Group-based performance analysis
Create a DataFrame called performance_report with the following features:
1. city_avg_sales: average sales within each city.
2. category_avg_sales: average sales within each category.
3. city_sales_rank: each city's total sales ranked from highest to lowest.
4. category_sales_share_pct: each order's percentage of its category's total valid sales.
5. above_city_average: whether the order's sales exceed its city's average.
6. above_category_median: whether the order's sales exceed its category median.
7. customer_order_count: number of orders per customer.
8. customer_total_sales: total sales per customer.