# Business Analytics and Advanced Aggregation

In [2]:
import pandas as pd
import numpy as np

data = {
    'order_id': range(4001, 4031),

    'customer_id': [
        501, 502, 503, 504, 505, 506, 507, 508, 509, 510,
        501, 502, 511, 512, 513, 506, 507, 514, 515, 510,
        516, 517, 518, 504, 505, 519, 520, 511, 512, 513
    ],

    'city': [
        'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai',
        'Bangalore', 'Pune', 'Delhi', 'Mumbai', 'Bangalore',
        'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai',
        'Bangalore', 'Pune', 'Delhi', 'Mumbai', 'Bangalore',
        'Pune', 'Delhi', 'Bangalore', 'Mumbai', 'Pune',
        'Delhi', 'Mumbai', 'Bangalore', 'Pune', 'Delhi'
    ],

    'category': [
        'Electronics', 'Clothing', 'Furniture', 'Electronics',
        'Clothing', 'Furniture', 'Electronics', 'Clothing',
        'Furniture', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Electronics', 'Clothing',
        'Furniture', 'Electronics', 'Clothing', 'Furniture',
        'Electronics', 'Clothing', 'Furniture', 'Electronics',
        'Clothing', 'Furniture', 'Electronics', 'Clothing',
        'Furniture', 'Electronics'
    ],

    'sales': [
        28000, 7500, 16000, 22000, 9000,
        19000, 14500, 6000, 24000, 11000,
        32000, 12500, 18000, 14000, 8500,
        26000, 15500, 21000, 7000, 12000,
        17500, 5000, 30000, 13500, 6500,
        25000, 20000, 9500, np.nan, 17000
    ],

    'quantity': [
        3, 2, 1, 2, 3,
        2, 4, 1, 3, 2,
        4, 2, 3, 2, 1,
        4, 2, 3, 2, 1,
        2, 1, 4, 2, 3,
        3, 2, 1, 4, 2
    ],

    'discount_pct': [
        5, 10, 0, 10, 15,
        5, 20, 0, 5, 10,
        0, 15, 10, 5, 20,
        5, 10, 5, 0, 15,
        10, 0, 5, 10, 15,
        5, 10, 20, 0, 5
    ],

    'order_status': [
        'Completed', 'Completed', 'Cancelled', 'Completed',
        'Completed', 'Completed', 'Cancelled', 'Completed',
        'Completed', 'Cancelled', 'Completed', 'Completed',
        'Completed', 'Cancelled', 'Completed', 'Completed',
        'Completed', 'Completed', 'Cancelled', 'Completed',
        'Completed', 'Cancelled', 'Completed', 'Completed',
        'Completed', 'Completed', 'Cancelled', 'Completed',
        'Completed', 'Completed'
    ],

    'channel': [
        'Organic', 'Paid Ads', 'Organic', 'Email', 'Paid Ads',
        'Organic', 'Email', 'Paid Ads', 'Organic', 'Email',
        'Organic', 'Paid Ads', 'Email', 'Organic', 'Paid Ads',
        'Email', 'Organic', 'Paid Ads', 'Email', 'Organic',
        'Email', 'Organic', 'Paid Ads', 'Email', 'Organic',
        'Paid Ads', 'Email', 'Organic', 'Paid Ads', 'Email'
    ]
}

df = pd.DataFrame(data)

df.head()

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status,channel
0,4001,501,Delhi,Electronics,28000.0,3,5,Completed,Organic
1,4002,502,Mumbai,Clothing,7500.0,2,10,Completed,Paid Ads
2,4003,503,Pune,Furniture,16000.0,1,0,Cancelled,Organic
3,4004,504,Delhi,Electronics,22000.0,2,10,Completed,Email
4,4005,505,Mumbai,Clothing,9000.0,3,15,Completed,Paid Ads

In [4]:
df.shape

(30, 9)

#### Q1. Revenue performance by city
Create a DataFrame named city_performance grouped by city, containing:
- order_count: number of orders
- valid_sales_count: non-missing sales count
- total_sales: sum of valid sales
- average_sales: mean sales
- median_sales: median sales
- total_quantity: total quantity sold
- average_discount: average discount percentage
Sort the result by total_sales in descending order.

In [11]:
city_performance=df.groupby('city').agg(
    order_count=('order_id','count'),
    valid_sales=('sales','count'),
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    meadian_sales=('sales','median'),
    total_quantity=('quantity','sum'),
    avg_discount=('discount_pct','mean')
)
city_performance

,order_count,valid_sales,total_sales,avg_sales,meadian_sales,total_quantity,avg_discount
city,,,,,,,
Bangalore,6,6,107500.0,17916.666667,15500.0,14,10.000000
Delhi,9,9,170000.0,18888.888889,21000.0,21,3.888889
Mumbai,8,8,102000.0,12750.000000,10750.0,17,10.625000
Pune,7,6,88000.0,14666.666667,15750.0,19,9.285714

#### Q2. Category performance report
Create category_performance, grouped by category, with:
- Total sales
- Average sales
- Number of orders
- Total quantity sold
- Average discount
- Number of unique customers
Sort by total sales from highest to lowest.

Identify the category with the highest total sales and the category with the highest average discount.

In [16]:
category_performance=df.groupby('category').agg(
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    No_of_orders=('order_id','count'),
    total_quantity=('quantity','sum'),
    avg_discount=('discount_pct','mean'),
    unique_customers=('customer_id','unique')
)
category_performance

,total_sales,avg_sales,No_of_orders,total_quantity,avg_discount,unique_customers
category,,,,,,
Clothing,89000.0,9888.888889,9,19,8.888889,"[502, 505, 508, 506, 515, 517, 511]"
Electronics,191000.0,17363.636364,11,26,10.454545,"[501, 504, 507, 510, 511, 513, 514, 516, 520]"
Furniture,187500.0,20833.333333,10,26,5.000000,"[503, 506, 509, 501, 512, 507, 510, 518, 519]"

In [18]:
category_performance['total_sales'].idxmax()

'Electronics'

In [20]:
category_performance['avg_discount'].idxmax()

'Electronics'

#### Q3. Order-status analysis
Create status_report, grouped by order_status, with:
- Order count
- Total sales
- Average sales
- Total quantity
- Unique customers
Calculate the percentage of orders in each status:
\[
\text{Order Share (\%)} =
\frac{\text{Orders in Status}}{\text{All Orders}}\times100
\]

Store this as order_share_pct.

In [25]:
status_report=df.groupby('order_status').agg(
    order_count=('order_id','count'),
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    total_quantity=('quantity','sum'),
    unique_customers=('customer_id','unique')
    
)
status_report['order_share_pct'] = (
    status_report['order_count'] / df['order_id'].count()
) * 100
status_report

,order_count,total_sales,avg_sales,total_quantity,unique_customers,order_share_pct
order_status,,,,,,
Cancelled,7,87500.0,12500.000000,14,"[503, 507, 510, 512, 515, 517, 520]",23.333333
Completed,23,380000.0,17272.727273,57,"[501, 502, 504, 505, 506, 508, 509, 511, 513, ...",76.666667

#### Q4. Channel-level business KPIs
Create channel_report, grouped by channel, with:
- Order count
- Total sales
- Average sales
- Median sales
- Unique customers
- Average discount
Then calculate each channel's contribution to total recorded sales as sales_contribution_pct.

In [32]:
channel_report=df.groupby('channel').agg(
    order_count=('order_id','count'),
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    median_sales=('sales','median'),
    unique_customers=('customer_id','unique'),
    avg_discount=('discount_pct','mean')
)
channel_report

,order_count,total_sales,avg_sales,median_sales,unique_customers,avg_discount
channel,,,,,,
Email,10,166500.0,16650.0,17250.0,"[504, 507, 510, 511, 506, 515, 516, 520, 513]",9.000000
Organic,11,181500.0,16500.0,15500.0,"[501, 503, 506, 509, 512, 507, 510, 517, 505, ...",7.272727
Paid Ads,9,119500.0,14937.5,10750.0,"[502, 505, 508, 513, 514, 518, 519, 512]",8.333333

In [38]:
channel_report['sales_contribution_pct']=(channel_report['total_sales']/df['sales'].sum())*100
channel_report

,order_count,total_sales,avg_sales,median_sales,unique_customers,avg_discount,sales_contribution_pct
channel,,,,,,,
Email,10,166500.0,16650.0,17250.0,"[504, 507, 510, 511, 506, 515, 516, 520, 513]",9.000000,35.614973
Organic,11,181500.0,16500.0,15500.0,"[501, 503, 506, 509, 512, 507, 510, 517, 505, ...",7.272727,38.823529
Paid Ads,9,119500.0,14937.5,10750.0,"[502, 505, 508, 513, 514, 518, 519, 512]",8.333333,25.561497

#### Q5. City and category performance
Group by both city and category.

Create city_category_report containing:
- Order count
- Total sales
- Average sales
- Total quantity
- Average discount
- Unique customers
Sort by city and then total sales in descending order within each city.

Identify the highest-sales category for every city.

In [49]:
city_category_report=df.groupby(['city','category']).agg(
    order_count=('order_id','count'),
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    median_sales=('sales','median'),
    unique_customers=('customer_id','unique'),
    avg_discount=('discount_pct','mean')
)
city_category_report = city_category_report.sort_values(
    by=['city', 'total_sales'],
    ascending=[True, False]
)
city_category_report

                       order_count  total_sales     avg_sales  median_sales  \
city      category
Bangalore Furniture              3      61000.0  20333.333333       19000.0
          Clothing               2      35500.0  17750.000000       17750.0
          Electronics            1      11000.0  11000.000000       11000.0
Delhi     Electronics            4      88000.0  22000.000000       21500.0
          Furniture              3      71000.0  23666.666667       25000.0
          Clothing               2      11000.0   5500.000000        5500.0
Mumbai    Electronics            3      42000.0  14000.000000       13500.0
          Clothing               4      36000.0   9000.000000        8250.0
          Furniture              1      24000.0  24000.000000       24000.0
Pune      Electronics            3      50000.0  16666.666667       17500.0
          Furniture              3      31500.0  15750.000000       15750.0
          Clothing               1       6500.0   6500.000000        6500.0

                           unique_customers  avg_discount
city      category
Bangalore Furniture         [506, 510, 518]      8.333333
          Clothing               [506, 511]     12.500000
          Electronics                 [510]     10.000000
Delhi     Electronics  [501, 504, 514, 513]      6.250000
          Furniture         [501, 512, 519]      3.333333
          Clothing               [508, 517]      0.000000
Mumbai    Electronics       [513, 504, 520]     13.333333
          Clothing          [502, 505, 515]     10.000000
          Furniture                   [509]      5.000000
Pune      Electronics       [507, 511, 516]     13.333333
          Furniture         [503, 507, 512]      3.333333
          Clothing                    [505]     15.000000