# Multi-Column Grouping and Multiple Aggregations

In [2]:
import pandas as pd
import numpy as np

data = {
    "order_id": range(2001, 2026),
    "customer_id": [
        301, 302, 303, 304, 305,
        306, 307, 308, 309, 310,
        301, 302, 303, 304, 305,
        306, 307, 308, 309, 310,
        311, 312, 313, 314, 315
    ],
    "city": [
        "Delhi", "Delhi", "Mumbai", "Mumbai", "Pune",
        "Pune", "Bangalore", "Bangalore", "Delhi", "Mumbai",
        "Delhi", "Delhi", "Mumbai", "Mumbai", "Pune",
        "Pune", "Bangalore", "Bangalore", "Delhi", "Mumbai",
        "Pune", "Delhi", "Bangalore", "Mumbai", "Pune"
    ],
    "category": [
        "Electronics", "Clothing", "Electronics", "Furniture",
        "Clothing", "Electronics", "Clothing", "Furniture",
        "Furniture", "Clothing", "Electronics", "Furniture",
        "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Clothing", "Electronics", "Furniture",
        "Electronics", "Clothing", "Furniture", "Clothing",
        "Electronics"
    ],
    "sales": [
        25000, 5000, 18000, 14000, 6500,
        22000, 7500, 16000, 12000, 9000,
        30000, 11000, 8000, 24000, 15000,
        5500, 28000, 6000, np.nan, 13000,
        19000, 4500, 21000, 10000, 17000
    ],
    "quantity": [
        3, 2, 2, 1, 4,
        3, 5, 2, 1, 3,
        4, 2, 1, 3, 2,
        2, 4, 2, 3, 2,
        2, 1, 3, 2, 4
    ],
    "discount_pct": [
        5, 10, 0, 15, 10,
        5, 0, 20, 10, 5,
        0, 15, 10, 5, 20,
        0, 5, 10, 5, 15,
        10, 0, 5, 10, 0
    ],
    "order_status": [
        "Completed", "Completed", "Completed", "Cancelled",
        "Completed", "Completed", "Completed", "Cancelled",
        "Completed", "Completed", "Completed", "Cancelled",
        "Completed", "Completed", "Completed", "Cancelled",
        "Completed", "Completed", "Completed", "Completed",
        "Cancelled", "Completed", "Completed", "Cancelled",
        "Completed"
    ]
}

df = pd.DataFrame(data)

df

,order_id,customer_id,city,category,sales,quantity,discount_pct,order_status
0,2001,301,Delhi,Electronics,25000.0,3,5,Completed
1,2002,302,Delhi,Clothing,5000.0,2,10,Completed
2,2003,303,Mumbai,Electronics,18000.0,2,0,Completed
3,2004,304,Mumbai,Furniture,14000.0,1,15,Cancelled
4,2005,305,Pune,Clothing,6500.0,4,10,Completed
5,2006,306,Pune,Electronics,22000.0,3,5,Completed
6,2007,307,Bangalore,Clothing,7500.0,5,0,Completed
7,2008,308,Bangalore,Furniture,16000.0,2,20,Cancelled
8,2009,309,Delhi,Furniture,12000.0,1,10,Completed
9,2010,310,Mumbai,Clothing,9000.0,3,5,Completed
10,2011,301,Delhi,Electronics,30000.0,4,0,Completed
11,2012,302,Delhi,Furniture,11000.0,2,15,Cancelled
12,2013,303,Mumbai,Clothing,8000.0,1,10,Completed
13,2014,304,Mumbai,Electronics,24000.0,3,5,Completed
14,2015,305,Pune,Furniture,15000.0,2,20,Completed
15,2016,306,Pune,Clothing,5500.0,2,0,Cancelled
16,2017,307,Bangalore,Electronics,28000.0,4,5,Completed
17,2018,308,Bangalore,Clothing,6000.0,2,10,Completed
18,2019,309,Delhi,Electronics,NaN,3,5,Completed
19,2020,310,Mumbai,Furniture,13000.0,2,15,Completed
20,2021,311,Pune,Electronics,19000.0,2,10,Cancelled
21,2022,312,Delhi,Clothing,4500.0,1,0,Completed
22,2023,313,Bangalore,Furniture,21000.0,3,5,Completed
23,2024,314,Mumbai,Clothing,10000.0,2,10,Cancelled
24,2025,315,Pune,Electronics,17000.0,4,0,Completed

#### Q1. Total sales by city and category
Calculate total sales for every combination of city and category.

Requirements:
1. Group by both columns.
2. Sum sales.
3. Store the result in city_category_sales.
4. Sort by total sales in descending order.

In [5]:
city_category_sales=df.groupby(['city','category'])['sales'].sum().sort_values(ascending=False)
city_category_sales

city       category
Pune       Electronics    58000.0
Delhi      Electronics    55000.0
Mumbai     Electronics    42000.0
Bangalore  Furniture      37000.0
           Electronics    28000.0
Mumbai     Clothing       27000.0
           Furniture      27000.0
Delhi      Furniture      23000.0
Pune       Furniture      15000.0
Bangalore  Clothing       13500.0
Pune       Clothing       12000.0
Delhi      Clothing        9500.0
Name: sales, dtype: float64

#### Q2. Average sales by city and category
Calculate average sales for each city-category combination.

Requirements:
1. Group by city and category.
2. Calculate mean sales.
3. Store the result in city_category_avg.
4. Round to two decimal places.

In [10]:
city_category_avg=round(df.groupby(['city','category'])['sales'].mean(),2)
city_category_avg

city       category
Bangalore  Clothing        6750.00
           Electronics    28000.00
           Furniture      18500.00
Delhi      Clothing        4750.00
           Electronics    27500.00
           Furniture      11500.00
Mumbai     Clothing        9000.00
           Electronics    21000.00
           Furniture      13500.00
Pune       Clothing        6000.00
           Electronics    19333.33
           Furniture      15000.00
Name: sales, dtype: float64

#### Q3. Order count by city and status
Calculate the number of orders for each combination of city and order status.

Requirements:
1. Group by city and order_status.
2. Count rows using size().
3. Store the result in city_status_count.
4. Make sure orders with missing sales are still counted.

In [13]:
city_status_count=df.groupby(['city','order_status']).size()
city_status_count

city       order_status
Bangalore  Cancelled       1
           Completed       4
Delhi      Cancelled       1
           Completed       6
Mumbai     Cancelled       2
           Completed       5
Pune       Cancelled       2
           Completed       4
dtype: int64

#### Q4. Multiple aggregations by city and category
For every city-category combination, calculate:
- Total sales
- Average sales
- Median sales
- Total quantity
- Number of non-missing sales values
Store the result in city_category_summary.

In [22]:
city_category_summary=(df.groupby(['city','category'])).agg(
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    median_sales=('sales','median'),
    total_quantity=('quantity','sum'),
    count_sales=('sales','count'))

city_category_summary

                       total_sales     avg_sales  median_sales  \
city      category
Bangalore Clothing         13500.0   6750.000000        6750.0
          Electronics      28000.0  28000.000000       28000.0
          Furniture        37000.0  18500.000000       18500.0
Delhi     Clothing          9500.0   4750.000000        4750.0
          Electronics      55000.0  27500.000000       27500.0
          Furniture        23000.0  11500.000000       11500.0
Mumbai    Clothing         27000.0   9000.000000        9000.0
          Electronics      42000.0  21000.000000       21000.0
          Furniture        27000.0  13500.000000       13500.0
Pune      Clothing         12000.0   6000.000000        6000.0
          Electronics      58000.0  19333.333333       19000.0
          Furniture        15000.0  15000.000000       15000.0

                       total_quantity  count_sales
city      category
Bangalore Clothing                  7            2
          Electronics               4            1
          Furniture                 5            2
Delhi     Clothing                  3            2
          Electronics              10            2
          Furniture                 3            2
Mumbai    Clothing                  6            3
          Electronics               5            2
          Furniture                 3            2
Pune      Clothing                  6            2
          Electronics               9            3
          Furniture                 2            1

#### Q5. Find the best-performing category in each city
Identify the category with the highest total sales in each city.

Requirements:
1. Calculate total sales by city and category.
2. Find the category with the maximum sales within each city.
3. Store the final result in top_category_by_city.
4. Return one top category per city when there are no ties; document how you handle ties.

In [25]:
category_by_city=df.groupby(['city','category'])['sales'].sum()
category_by_city

city       category
Bangalore  Clothing       13500.0
           Electronics    28000.0
           Furniture      37000.0
Delhi      Clothing        9500.0
           Electronics    55000.0
           Furniture      23000.0
Mumbai     Clothing       27000.0
           Electronics    42000.0
           Furniture      27000.0
Pune       Clothing       12000.0
           Electronics    58000.0
           Furniture      15000.0
Name: sales, dtype: float64

In [32]:
top_category_by_city = (
    category_by_city
    .loc[category_by_city.groupby(level='city').idxmax()]
)

top_category_by_city

city       category
Bangalore  Furniture      37000.0
Delhi      Electronics    55000.0
Mumbai     Electronics    42000.0
Pune       Electronics    58000.0
Name: sales, dtype: float64

#### Q6. Unique customers by city and category
Count distinct customers for every city-category combination.

Requirements:
1. Group by city and category.
2. Count unique customer_id values.
3. Store the result in unique_customers_summary.
Concepts: nunique() and multi-column grouping.

In [35]:
unique_customers_summary=df.groupby(['city','category'])['customer_id'].nunique()
unique_customers_summary

city       category
Bangalore  Clothing       2
           Electronics    1
           Furniture      2
Delhi      Clothing       2
           Electronics    2
           Furniture      2
Mumbai     Clothing       3
           Electronics    2
           Furniture      2
Pune       Clothing       2
           Electronics    3
           Furniture      1
Name: customer_id, dtype: int64

#### Q7. Sales contribution within each city
Calculate each category's percentage contribution to its city's total sales.

Formula:

category_sales / city_total_sales * 100

Requirements:
1. Calculate total sales for each city-category combination.
2. Calculate total sales for each city.
3. Add city_sales_contribution_pct.
4. Handle missing sales and zero denominators safely.

In [42]:
total_sales=df.groupby(['city','category'])['sales'].sum()
total_sales

city       category
Bangalore  Clothing       13500.0
           Electronics    28000.0
           Furniture      37000.0
Delhi      Clothing        9500.0
           Electronics    55000.0
           Furniture      23000.0
Mumbai     Clothing       27000.0
           Electronics    42000.0
           Furniture      27000.0
Pune       Clothing       12000.0
           Electronics    58000.0
           Furniture      15000.0
Name: sales, dtype: float64

#### Q8. Average discount by city and category
Calculate the average discount_pct for each city-category combination.

Requirements:
1. Group by city and category.
2. Calculate mean discount.
3. Store the result in avg_discount_summary.
4. Identify the combination with the highest average discount.
Concepts: groupby(), mean(), idxmax().

In [49]:
avg_discount_summary=df.groupby(['city','category'])['discount_pct'].mean()
avg_discount_summary.idxmax()

('Pune', 'Furniture')

#### Q9. Completed-order sales by city and category
Analyze completed orders only.

Requirements:
1. Filter rows where order_status == "Completed".
2. Group by city and category.
3. Calculate order count, total sales, and average sales.
4. Store the result in completed_sales_summary.
5. Compare it with the overall sales summary.
Use size() for order counts and explain how missing sales affects sales totals and averages.

In [69]:
dff=df.query('order_status=="Completed"')

completed_sales_summary=dff.groupby(['city','category'])['sales'].agg(['count','sum','mean'])
completed_sales_summary

                       count      sum     mean
city      category
Bangalore Clothing         2  13500.0   6750.0
          Electronics      1  28000.0  28000.0
          Furniture        1  21000.0  21000.0
Delhi     Clothing         2   9500.0   4750.0
          Electronics      2  55000.0  27500.0
          Furniture        1  12000.0  12000.0
Mumbai    Clothing         2  17000.0   8500.0
          Electronics      2  42000.0  21000.0
          Furniture        1  13000.0  13000.0
Pune      Clothing         1   6500.0   6500.0
          Electronics      2  39000.0  19500.0
          Furniture        1  15000.0  15000.0

In [73]:
overall_sales_summary=df.groupby(['city','category'])['sales'].agg(['count','sum','mean'])
overall_sales_summary

                       count      sum          mean
city      category
Bangalore Clothing         2  13500.0   6750.000000
          Electronics      1  28000.0  28000.000000
          Furniture        2  37000.0  18500.000000
Delhi     Clothing         2   9500.0   4750.000000
          Electronics      2  55000.0  27500.000000
          Furniture        2  23000.0  11500.000000
Mumbai    Clothing         3  27000.0   9000.000000
          Electronics      2  42000.0  21000.000000
          Furniture        2  27000.0  13500.000000
Pune      Clothing         2  12000.0   6000.000000
          Electronics      3  58000.0  19333.333333
          Furniture        1  15000.0  15000.000000

#### Q10. Mini-project — Multi-dimensional business report
Build a report grouped by city, category, and order_status.

Include:
1. order_count: number of orders.
2. valid_sales_count: number of non-missing sales values.
3. total_sales: sum of sales.
4. average_sales: mean sales.
5. median_sales: median sales.
6. total_quantity: sum of quantity.
7. average_discount: average discount percentage.
8. unique_customers: distinct customers.
Store the result in business_report.

Then:
- Sort the report by total_sales in descending order.
- Inspect the first 10 rows.
- Check for missing values.
- Explain two business insights supported by the results.

In [78]:
business_report=df.groupby(['city','category','order_status']).agg(
    order_count=('order_id','count'),
    valid_sales_count=('sales','count'),
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    median_sales=('sales','median'),
    total_quantity=('quantity','sum'),
    avg_discount=('discount_pct','mean'),
    unique_customers=('customer_id','unique')
)
business_report

                                    order_count  valid_sales_count  \
city      category    order_status
Bangalore Clothing    Completed               2                  2
          Electronics Completed               1                  1
          Furniture   Cancelled               1                  1
                      Completed               1                  1
Delhi     Clothing    Completed               2                  2
          Electronics Completed               3                  2
          Furniture   Cancelled               1                  1
                      Completed               1                  1
Mumbai    Clothing    Cancelled               1                  1
                      Completed               2                  2
          Electronics Completed               2                  2
          Furniture   Cancelled               1                  1
                      Completed               1                  1
Pune      Clothing    Cancelled               1                  1
                      Completed               1                  1
          Electronics Cancelled               1                  1
                      Completed               2                  2
          Furniture   Completed               1                  1

                                    total_sales  avg_sales  median_sales  \
city      category    order_status
Bangalore Clothing    Completed         13500.0     6750.0        6750.0
          Electronics Completed         28000.0    28000.0       28000.0
          Furniture   Cancelled         16000.0    16000.0       16000.0
                      Completed         21000.0    21000.0       21000.0
Delhi     Clothing    Completed          9500.0     4750.0        4750.0
          Electronics Completed         55000.0    27500.0       27500.0
          Furniture   Cancelled         11000.0    11000.0       11000.0
                      Completed         12000.0    12000.0       12000.0
Mumbai    Clothing    Cancelled         10000.0    10000.0       10000.0
                      Completed         17000.0     8500.0        8500.0
          Electronics Completed         42000.0    21000.0       21000.0
          Furniture   Cancelled         14000.0    14000.0       14000.0
                      Completed         13000.0    13000.0       13000.0
Pune      Clothing    Cancelled          5500.0     5500.0        5500.0
                      Completed          6500.0     6500.0        6500.0
          Electronics Cancelled         19000.0    19000.0       19000.0
                      Completed         39000.0    19500.0       19500.0
          Furniture   Completed         15000.0    15000.0       15000.0

                                    total_quantity  avg_discount  \
city      category    order_status
Bangalore Clothing    Completed                  7      5.000000
          Electronics Completed                  4      5.000000
          Furniture   Cancelled                  2     20.000000
                      Completed                  3      5.000000
Delhi     Clothing    Completed                  3      5.000000
          Electronics Completed                 10      3.333333
          Furniture   Cancelled                  2     15.000000
                      Completed                  1     10.000000
Mumbai    Clothing    Cancelled                  2     10.000000
                      Completed                  4      7.500000
          Electronics Completed                  5      2.500000
          Furniture   Cancelled                  1     15.000000
                      Completed                  2     15.000000
Pune      Clothing    Cancelled                  2      0.000000
                      Completed                  4     10.000000
          Electronics Cancelled                  2     10.000000
                      Completed                  7      2.500000
          Furniture   Completed                  2     20.000000

                                   unique_customers
city      category    order_status
Bangalore Clothing    Completed          [307, 308]
          Electronics Completed               [307]
          Furniture   Cancelled               [308]
                      Completed               [313]
Delhi     Clothing    Completed          [302, 312]
          Electronics Completed          [301, 309]
          Furniture   Cancelled               [302]
                      Completed               [309]
Mumbai    Clothing    Cancelled               [314]
                      Completed          [310, 303]
          Electronics Completed          [303, 304]
          Furniture   Cancelled               [304]
                      Completed               [310]
Pune      Clothing    Cancelled               [306]
                      Completed               [305]
          Electronics Cancelled               [311]
                      Completed          [306, 315]
          Furniture   Completed               [305]

In [84]:
business_report=business_report.sort_values(by='total_sales',ascending=False)
business_report

                                    order_count  valid_sales_count  \
city      category    order_status
Delhi     Electronics Completed               3                  2
Mumbai    Electronics Completed               2                  2
Pune      Electronics Completed               2                  2
Bangalore Electronics Completed               1                  1
          Furniture   Completed               1                  1
Pune      Electronics Cancelled               1                  1
Mumbai    Clothing    Completed               2                  2
Bangalore Furniture   Cancelled               1                  1
Pune      Furniture   Completed               1                  1
Mumbai    Furniture   Cancelled               1                  1
Bangalore Clothing    Completed               2                  2
Mumbai    Furniture   Completed               1                  1
Delhi     Furniture   Completed               1                  1
                      Cancelled               1                  1
Mumbai    Clothing    Cancelled               1                  1
Delhi     Clothing    Completed               2                  2
Pune      Clothing    Completed               1                  1
                      Cancelled               1                  1

                                    total_sales  avg_sales  median_sales  \
city      category    order_status
Delhi     Electronics Completed         55000.0    27500.0       27500.0
Mumbai    Electronics Completed         42000.0    21000.0       21000.0
Pune      Electronics Completed         39000.0    19500.0       19500.0
Bangalore Electronics Completed         28000.0    28000.0       28000.0
          Furniture   Completed         21000.0    21000.0       21000.0
Pune      Electronics Cancelled         19000.0    19000.0       19000.0
Mumbai    Clothing    Completed         17000.0     8500.0        8500.0
Bangalore Furniture   Cancelled         16000.0    16000.0       16000.0
Pune      Furniture   Completed         15000.0    15000.0       15000.0
Mumbai    Furniture   Cancelled         14000.0    14000.0       14000.0
Bangalore Clothing    Completed         13500.0     6750.0        6750.0
Mumbai    Furniture   Completed         13000.0    13000.0       13000.0
Delhi     Furniture   Completed         12000.0    12000.0       12000.0
                      Cancelled         11000.0    11000.0       11000.0
Mumbai    Clothing    Cancelled         10000.0    10000.0       10000.0
Delhi     Clothing    Completed          9500.0     4750.0        4750.0
Pune      Clothing    Completed          6500.0     6500.0        6500.0
                      Cancelled          5500.0     5500.0        5500.0

                                    total_quantity  avg_discount  \
city      category    order_status
Delhi     Electronics Completed                 10      3.333333
Mumbai    Electronics Completed                  5      2.500000
Pune      Electronics Completed                  7      2.500000
Bangalore Electronics Completed                  4      5.000000
          Furniture   Completed                  3      5.000000
Pune      Electronics Cancelled                  2     10.000000
Mumbai    Clothing    Completed                  4      7.500000
Bangalore Furniture   Cancelled                  2     20.000000
Pune      Furniture   Completed                  2     20.000000
Mumbai    Furniture   Cancelled                  1     15.000000
Bangalore Clothing    Completed                  7      5.000000
Mumbai    Furniture   Completed                  2     15.000000
Delhi     Furniture   Completed                  1     10.000000
                      Cancelled                  2     15.000000
Mumbai    Clothing    Cancelled                  2     10.000000
Delhi     Clothing    Completed                  3      5.000000
Pune      Clothing    Completed                  4     10.000000
                      Cancelled                  2      0.000000

                                   unique_customers
city      category    order_status
Delhi     Electronics Completed          [301, 309]
Mumbai    Electronics Completed          [303, 304]
Pune      Electronics Completed          [306, 315]
Bangalore Electronics Completed               [307]
          Furniture   Completed               [313]
Pune      Electronics Cancelled               [311]
Mumbai    Clothing    Completed          [310, 303]
Bangalore Furniture   Cancelled               [308]
Pune      Furniture   Completed               [305]
Mumbai    Furniture   Cancelled               [304]
Bangalore Clothing    Completed          [307, 308]
Mumbai    Furniture   Completed               [310]
Delhi     Furniture   Completed               [309]
                      Cancelled               [302]
Mumbai    Clothing    Cancelled               [314]
Delhi     Clothing    Completed          [302, 312]
Pune      Clothing    Completed               [305]
                      Cancelled               [306]

In [86]:
business_report.head(10)

                                    order_count  valid_sales_count  \
city      category    order_status
Delhi     Electronics Completed               3                  2
Mumbai    Electronics Completed               2                  2
Pune      Electronics Completed               2                  2
Bangalore Electronics Completed               1                  1
          Furniture   Completed               1                  1
Pune      Electronics Cancelled               1                  1
Mumbai    Clothing    Completed               2                  2
Bangalore Furniture   Cancelled               1                  1
Pune      Furniture   Completed               1                  1
Mumbai    Furniture   Cancelled               1                  1

                                    total_sales  avg_sales  median_sales  \
city      category    order_status
Delhi     Electronics Completed         55000.0    27500.0       27500.0
Mumbai    Electronics Completed         42000.0    21000.0       21000.0
Pune      Electronics Completed         39000.0    19500.0       19500.0
Bangalore Electronics Completed         28000.0    28000.0       28000.0
          Furniture   Completed         21000.0    21000.0       21000.0
Pune      Electronics Cancelled         19000.0    19000.0       19000.0
Mumbai    Clothing    Completed         17000.0     8500.0        8500.0
Bangalore Furniture   Cancelled         16000.0    16000.0       16000.0
Pune      Furniture   Completed         15000.0    15000.0       15000.0
Mumbai    Furniture   Cancelled         14000.0    14000.0       14000.0

                                    total_quantity  avg_discount  \
city      category    order_status
Delhi     Electronics Completed                 10      3.333333
Mumbai    Electronics Completed                  5      2.500000
Pune      Electronics Completed                  7      2.500000
Bangalore Electronics Completed                  4      5.000000
          Furniture   Completed                  3      5.000000
Pune      Electronics Cancelled                  2     10.000000
Mumbai    Clothing    Completed                  4      7.500000
Bangalore Furniture   Cancelled                  2     20.000000
Pune      Furniture   Completed                  2     20.000000
Mumbai    Furniture   Cancelled                  1     15.000000

                                   unique_customers
city      category    order_status
Delhi     Electronics Completed          [301, 309]
Mumbai    Electronics Completed          [303, 304]
Pune      Electronics Completed          [306, 315]
Bangalore Electronics Completed               [307]
          Furniture   Completed               [313]
Pune      Electronics Cancelled               [311]
Mumbai    Clothing    Completed          [310, 303]
Bangalore Furniture   Cancelled               [308]
Pune      Furniture   Completed               [305]
Mumbai    Furniture   Cancelled               [304]

In [88]:
business_report.isna().sum()

order_count          0
valid_sales_count    0
total_sales          0
avg_sales            0
median_sales         0
total_quantity       0
avg_discount         0
unique_customers     0
dtype: int64