# Batch 1

#### Q1. Select a single column
import pandas as pddf = pd.DataFrame({    "age": [22, 35, 28, 41, 30],    "salary": [25000, 45000, 32000, 60000, 40000],    "department": ["IT", "HR", "IT", "Sales", "HR"]})



1. Select the age column using square brackets.
2. Select the age column using dot notation.
3. What is the data type of df["age"]?
4. Why is df["age"] generally safer than df.age?

In [3]:
import pandas as pd

df = pd.DataFrame({
    "age": [22, 35, 28, 41, 30],
    "salary": [25000, 45000, 32000, 60000, 40000],
    "department": ["IT", "HR", "IT", "Sales", "HR"]
})

In [5]:
df['age']

0    22
1    35
2    28
3    41
4    30
Name: age, dtype: int64

In [7]:
df.age

0    22
1    35
2    28
3    41
4    30
Name: age, dtype: int64

In [9]:
df.age.dtype

dtype('int64')

Column names with spaces or special characters: df["employee age"] works, but df.employee age does not.



Conflicts with DataFrame attributes or methods: If a column is named count, shape, or mean, dot notation may access the built-in attribute or method instead of the column.



More reliable for dynamic column names: Bracket notation works when the column name is stored in a variable.

#### Q2. Select multiple columns
Using df from Q1:
1. Select age and salary.
2. Select department and salary.
3. Select all three columns but in this order: salary, age, department.
4. What is the difference between df["age"] and df[["age"]]?

In [13]:
df[['age','salary']]

   age  salary
0   22   25000
1   35   45000
2   28   32000
3   41   60000
4   30   40000

In [15]:
df[['department','salary']]

  department  salary
0         IT   25000
1         HR   45000
2         IT   32000
3      Sales   60000
4         HR   40000

In [17]:
df[['salary', 'age', 'department']]

   salary  age department
0   25000   22         IT
1   45000   35         HR
2   32000   28         IT
3   60000   41      Sales
4   40000   30         HR

difference of dataframe n series

#### Q3. Select rows using loc and iloc
df = pd.DataFrame({    "name": ["Aman", "Riya", "Karan", "Neha"],    "age": [22, 25, 30, 28],    "salary": [25000, 35000, 50000, 42000]}, index=["a", "b", "c", "d"])



1. Select the row with index label "b" using loc.
2. Select the third row using iloc.
3. Select rows "a" through "c" using loc.
4. Select the first two rows using iloc.

In [24]:
df = pd.DataFrame({
    "name": ["Aman", "Riya", "Karan", "Neha"],
    "age": [22, 25, 30, 28],
    "salary": [25000, 35000, 50000, 42000]
}, index=["a", "b", "c", "d"])
df

    name  age  salary
a   Aman   22   25000
b   Riya   25   35000
c  Karan   30   50000
d   Neha   28   42000

In [26]:
df.loc['b']

name       Riya
age          25
salary    35000
Name: b, dtype: object

In [28]:
df.iloc[2]

name      Karan
age          30
salary    50000
Name: c, dtype: object

In [30]:
df.loc['a':'c']

    name  age  salary
a   Aman   22   25000
b   Riya   25   35000
c  Karan   30   50000

In [34]:
df.iloc[:2]

   name  age  salary
a  Aman   22   25000
b  Riya   25   35000

#### Q4. Select rows and columns together
Using the same DataFrame from Q3:
1. Select the name value for index "c".
2. Select name and salary for index "d".
3. Select age and salary for rows "a" and "b".
4. Select the first three rows and the first two columns using iloc.

In [37]:
df.loc['c','name']

'Karan'

In [39]:
df.loc['d',['name','salary']]

name       Neha
salary    42000
Name: d, dtype: object

In [41]:
df.loc[['a','c'],['age','salary']]

   age  salary
a   22   25000
c   30   50000

In [45]:
df.iloc[:3,:2]

    name  age
a   Aman   22
b   Riya   25
c  Karan   30

#### Q5. Filter using one condition
df = pd.DataFrame({    "employee": ["A", "B", "C", "D", "E"],    "age": [22, 35, 28, 41, 30],    "salary": [25000, 45000, 32000, 60000, 40000],    "department": ["IT", "HR", "IT", "Sales", "HR"]})



Write Pandas code to:
1. Select employees older than 30.
2. Select employees with salary greater than or equal to 40,000.
3. Select employees in the IT department.
4. Select employees younger than 30.

In [48]:
df = pd.DataFrame({
    "employee": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 28, 41, 30],
    "salary": [25000, 45000, 32000, 60000, 40000],
    "department": ["IT", "HR", "IT", "Sales", "HR"]
})

In [50]:
df[df['age']>30]

  employee  age  salary department
1        B   35   45000         HR
3        D   41   60000      Sales

In [52]:
df[df['salary']>=40000]

  employee  age  salary department
1        B   35   45000         HR
3        D   41   60000      Sales
4        E   30   40000         HR

In [54]:
df[df['department']=='IT']

  employee  age  salary department
0        A   22   25000         IT
2        C   28   32000         IT

In [56]:
df[df['age']<30]

  employee  age  salary department
0        A   22   25000         IT
2        C   28   32000         IT

#### Q6. Filter using multiple conditions
Using the DataFrame from Q5:
1. Select employees older than 25 and earning more than 35,000.
2. Select employees in IT or HR.
3. Select employees whose age is between 25 and 35, inclusive.
4. Why must each condition be enclosed in parentheses when using & and |?

In [65]:
df[(df['age']>25) & (df['salary']>35000)]

  employee  age  salary department
1        B   35   45000         HR
3        D   41   60000      Sales
4        E   30   40000         HR

In [67]:
df[(df['department']=="IT") | (df['department']=='HR')]

  employee  age  salary department
0        A   22   25000         IT
1        B   35   45000         HR
2        C   28   32000         IT
4        E   30   40000         HR

In [69]:
df[(df['age']>=25) & (df['age']<=35)]

  employee  age  salary department
1        B   35   45000         HR
2        C   28   32000         IT
4        E   30   40000         HR

#### Q7. Debug the code
high_salary = df[df["salary"] > 30000 and df["age"] >= 30]



1. Explain why this code raises an error.
2. Rewrite it to select employees earning over 30,000 and aged at least 30.
3. Rewrite it to select employees earning over 30,000 or aged at least 30.

In [72]:
high_salary = df[(df["salary"] > 30000) & (df["age"] >= 30)]

In [74]:
df

  employee  age  salary department
0        A   22   25000         IT
1        B   35   45000         HR
2        C   28   32000         IT
3        D   41   60000      Sales
4        E   30   40000         HR

#### Q8. Use isin() and between()
df = pd.DataFrame({    "customer_id": [101, 102, 103, 104, 105, 106],    "city": ["Delhi", "Mumbai", "Pune", "Delhi", "Jaipur", "Mumbai"],    "age": [22, 35, 28, 41, 30, 25],    "spend": [1200, 2500, 1800, 4000, 2200, 1500]})



1. Select customers from Delhi or Mumbai using isin().
2. Select customers aged between 25 and 35 using between().
3. Select customers from Delhi or Pune who spend more than 1,500.
4. Select customers whose IDs are in [102, 104, 106].

In [77]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106],
    "city": ["Delhi", "Mumbai", "Pune", "Delhi", "Jaipur", "Mumbai"],
    "age": [22, 35, 28, 41, 30, 25],
    "spend": [1200, 2500, 1800, 4000, 2200, 1500]
})
df

   customer_id    city  age  spend
0          101   Delhi   22   1200
1          102  Mumbai   35   2500
2          103    Pune   28   1800
3          104   Delhi   41   4000
4          105  Jaipur   30   2200
5          106  Mumbai   25   1500

In [79]:
df[df['city'].isin(['Delhi','Mumbai'])]

   customer_id    city  age  spend
0          101   Delhi   22   1200
1          102  Mumbai   35   2500
3          104   Delhi   41   4000
5          106  Mumbai   25   1500

In [81]:
df[df['age'].between(25,35)]

   customer_id    city  age  spend
1          102  Mumbai   35   2500
2          103    Pune   28   1800
4          105  Jaipur   30   2200
5          106  Mumbai   25   1500

In [85]:
#Select customers from Delhi or Pune who spend more than 1,500.
df[(df['city'].isin(['Delhi','Pune'])) & df['spend']>1500]

Empty DataFrame
Columns: [customer_id, city, age, spend]
Index: []

In [87]:
#Select customers whose IDs are in [102, 104, 106].
df[(df['customer_id'].isin([102, 104, 106]))]

   customer_id    city  age  spend
1          102  Mumbai   35   2500
3          104   Delhi   41   4000
5          106  Mumbai   25   1500

#### Q9. Real-world ML scenario
A customer churn dataset contains these columns:
customer_id, age, monthly_spend, support_calls, contract_type, churn
Write code to:
1. Select customers with monthly_spend > 2000.
2. Select customers with support_calls >= 3 and churn == 1.
3. Select only age, monthly_spend, and churn.
4. Select customers with contract_type equal to "Monthly" or "Yearly".
5. Explain why filtering to only customers with churn == 1 before training a typical churn classifier could cause a problem.

#### Q10. Mini-project — Customer Data Selection
Create this DataFrame:
df = pd.DataFrame({    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],    "age": [22, 35, 28, 41, 30, 25, 45, 33],    "monthly_spend": [1200, 2500, 1800, 4000, 2200, 1500, 5000, 3100],    "visits": [4, 8, 5, 9, 6, 3, 12, 7],    "city": ["Delhi", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune", "Delhi", "Jaipur"],    "churn": [0, 1, 0, 1, 1, 0, 0, 1]})



Complete the following:
1. Display only customer_id, monthly_spend, and churn.
2. Select customers spending more than 2,000.
3. Select customers aged at least 30 with 7 or more visits.
4. Select customers from Delhi or Mumbai.
5. Select customers who churned and spent at least 2,000.
6. Select customers who did not churn and visited fewer than 6 times.
7. Select rows at positions 1, 3, and 5 using iloc.
8. Display age and churn for the first four rows using iloc.
9. Select customers whose age is between 25 and 40, inclusive.
10. Write a short explanation of how these selection and filtering operations help with ML data analysis.

In [91]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "age": [22, 35, 28, 41, 30, 25, 45, 33],
    "monthly_spend": [1200, 2500, 1800, 4000, 2200, 1500, 5000, 3100],
    "visits": [4, 8, 5, 9, 6, 3, 12, 7],
    "city": ["Delhi", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune", "Delhi", "Jaipur"],
    "churn": [0, 1, 0, 1, 1, 0, 0, 1]
})
df

   customer_id  age  monthly_spend  visits    city  churn
0          101   22           1200       4   Delhi      0
1          102   35           2500       8  Mumbai      1
2          103   28           1800       5    Pune      0
3          104   41           4000       9   Delhi      1
4          105   30           2200       6  Mumbai      1
5          106   25           1500       3    Pune      0
6          107   45           5000      12   Delhi      0
7          108   33           3100       7  Jaipur      1

In [93]:
#Display only customer_id, monthly_spend, and churn.
df[['customer_id','monthly_spend','churn']]

   customer_id  monthly_spend  churn
0          101           1200      0
1          102           2500      1
2          103           1800      0
3          104           4000      1
4          105           2200      1
5          106           1500      0
6          107           5000      0
7          108           3100      1

In [95]:
#Select customers spending more than 2,000.
df[df['monthly_spend']>2000]

   customer_id  age  monthly_spend  visits    city  churn
1          102   35           2500       8  Mumbai      1
3          104   41           4000       9   Delhi      1
4          105   30           2200       6  Mumbai      1
6          107   45           5000      12   Delhi      0
7          108   33           3100       7  Jaipur      1

In [97]:
#Select customers aged at least 30 with 7 or more visits.
df[(df['age']>=30) & (df['visits']>=7)]

   customer_id  age  monthly_spend  visits    city  churn
1          102   35           2500       8  Mumbai      1
3          104   41           4000       9   Delhi      1
6          107   45           5000      12   Delhi      0
7          108   33           3100       7  Jaipur      1

In [99]:
#Select customers from Delhi or Mumbai.
df[df['city'].isin(['Delhi','Mumbai'])]

   customer_id  age  monthly_spend  visits    city  churn
0          101   22           1200       4   Delhi      0
1          102   35           2500       8  Mumbai      1
3          104   41           4000       9   Delhi      1
4          105   30           2200       6  Mumbai      1
6          107   45           5000      12   Delhi      0

In [101]:
#Select customers who churned and spent at least 2,000.
df[(df['churn']==1) & df['monthly_spend']>=2000]

Empty DataFrame
Columns: [customer_id, age, monthly_spend, visits, city, churn]
Index: []

In [103]:
#Select customers who did not churn and visited fewer than 6 times.
df[(df['churn']==0) & (df['visits']<=6)]

   customer_id  age  monthly_spend  visits   city  churn
0          101   22           1200       4  Delhi      0
2          103   28           1800       5   Pune      0
5          106   25           1500       3   Pune      0

In [105]:
#Select rows at positions 1, 3, and 5 using iloc.
df.iloc[[1,3,5]]

   customer_id  age  monthly_spend  visits    city  churn
1          102   35           2500       8  Mumbai      1
3          104   41           4000       9   Delhi      1
5          106   25           1500       3    Pune      0

In [111]:
#Display age and churn for the first four rows using iloc.
df.iloc[0:4,[1,5]]

   age  churn
0   22      0
1   35      1
2   28      0
3   41      1

In [115]:
#Select customers whose age is between 25 and 40, inclusive.
df[df['age'].between(25,40)]

   customer_id  age  monthly_spend  visits    city  churn
1          102   35           2500       8  Mumbai      1
2          103   28           1800       5    Pune      0
4          105   30           2200       6  Mumbai      1
5          106   25           1500       3    Pune      0
7          108   33           3100       7  Jaipur      1