# Batch 3- Index Alignment, Sorting and Ranking

In [2]:
import pandas as pd

df = pd.DataFrame({
    "employee": ["Asha", "Rahul", "Neha", "Vikram", "Priya", "Aman"],
    "department": ["IT", "Sales", "IT", "HR", "Sales", "HR"],
    "salary": [60000, 45000, 75000, 50000, 45000, 65000],
    "experience": [3, 2, 5, 4, 2, 6],
    "performance_score": [85, 78, 92, 80, 88, 92]
})
df

  employee department  salary  experience  performance_score
0     Asha         IT   60000           3                 85
1    Rahul      Sales   45000           2                 78
2     Neha         IT   75000           5                 92
3   Vikram         HR   50000           4                 80
4    Priya      Sales   45000           2                 88
5     Aman         HR   65000           6                 92

#### Q1. Sort by one column
Sort employees by salary in ascending order.

In [4]:
df.sort_values(by='salary')

  employee department  salary  experience  performance_score
1    Rahul      Sales   45000           2                 78
4    Priya      Sales   45000           2                 88
3   Vikram         HR   50000           4                 80
0     Asha         IT   60000           3                 85
5     Aman         HR   65000           6                 92
2     Neha         IT   75000           5                 92

#### Q2. Sort by multiple columns
Sort by department alphabetically, then by salary in descending order within each department.

In [6]:
df.sort_values(by=['department','salary'],ascending=[False,True])

  employee department  salary  experience  performance_score
1    Rahul      Sales   45000           2                 78
4    Priya      Sales   45000           2                 88
0     Asha         IT   60000           3                 85
2     Neha         IT   75000           5                 92
3   Vikram         HR   50000           4                 80
5     Aman         HR   65000           6                 92

#### Q3. Reset the index
Sort the DataFrame by salary in descending order and reset the index, dropping the old index.

In [8]:
df_sorted=df.sort_values(by='salary',ascending=False)
df_sorted

  employee department  salary  experience  performance_score
2     Neha         IT   75000           5                 92
5     Aman         HR   65000           6                 92
0     Asha         IT   60000           3                 85
3   Vikram         HR   50000           4                 80
1    Rahul      Sales   45000           2                 78
4    Priya      Sales   45000           2                 88

In [9]:
df_sorted.reset_index(drop=True)

  employee department  salary  experience  performance_score
0     Neha         IT   75000           5                 92
1     Aman         HR   65000           6                 92
2     Asha         IT   60000           3                 85
3   Vikram         HR   50000           4                 80
4    Rahul      Sales   45000           2                 78
5    Priya      Sales   45000           2                 88

#### Q4. Set an index
Set employee as the DataFrame index, then retrieve Neha's complete row using .loc.

In [11]:
df_index=df.set_index('employee')
df_index

         department  salary  experience  performance_score
employee
Asha             IT   60000           3                 85
Rahul         Sales   45000           2                 78
Neha             IT   75000           5                 92
Vikram           HR   50000           4                 80
Priya         Sales   45000           2                 88
Aman             HR   65000           6                 92

In [12]:
df_index.loc['Neha']

department              IT
salary               75000
experience               5
performance_score       92
Name: Neha, dtype: object

#### Q5. Retrieve rows by position
Use .iloc to retrieve the first three rows and the employee and salary columns only.

In [14]:
df.iloc[:3][['employee','salary']]

  employee  salary
0     Asha   60000
1    Rahul   45000
2     Neha   75000

#### Q6. Rank salaries
Create a new column named salary_rank that ranks salaries from highest to lowest, with the highest salary receiving rank 1.

In [16]:
df['rank_salary']=df['salary'].rank(ascending=False).astype(int)
df

  employee department  salary  experience  performance_score  rank_salary
0     Asha         IT   60000           3                 85            3
1    Rahul      Sales   45000           2                 78            5
2     Neha         IT   75000           5                 92            1
3   Vikram         HR   50000           4                 80            4
4    Priya      Sales   45000           2                 88            5
5     Aman         HR   65000           6                 92            2

#### Q7. Handle tied ranks
Rank performance_score from highest to lowest using the dense method. Explain how dense ranking differs from the default ranking method when scores are tied.

In [18]:
df['performance_rank']=df['performance_score'].rank(ascending=False,method='min').astype(int)
df

,employee,department,salary,experience,performance_score,rank_salary,performance_rank
0,Asha,IT,60000,3,85,3,4
1,Rahul,Sales,45000,2,78,5,6
2,Neha,IT,75000,5,92,1,1
3,Vikram,HR,50000,4,80,4,5
4,Priya,Sales,45000,2,88,5,3
5,Aman,HR,65000,6,92,2,1

#### Q8. Find the top performers
Return the three employees with the highest performance_score using nlargest().

In [20]:
df.nlargest(3,'performance_score')

,employee,department,salary,experience,performance_score,rank_salary,performance_rank
2,Neha,IT,75000,5,92,1,1
5,Aman,HR,65000,6,92,2,1
4,Priya,Sales,45000,2,88,5,3

#### Q9. Understand index alignment
Consider these two Series:
s1 = pd.Series([100, 200, 300], index=["A", "B", "C"])s2 = pd.Series([10, 20, 30], index=["B", "C", "D"])



Calculate s1 + s2. Explain why Pandas aligns values by index labels rather than simply adding values at matching positions, and why some results are missing.

In [22]:
s1 = pd.Series([100, 200, 300], index=["A", "B", "C"])
s2 = pd.Series([10, 20, 30], index=["B", "C", "D"])

In [23]:
s1+s2

A      NaN
B    210.0
C    320.0
D      NaN
dtype: float64

##### Pandas performs index alignment when adding Series. It matches values by their index labels, not by their positions.

#### Q10. Mini-project — Employee ranking system
Using the original DataFrame:
1. Sort employees by performance score descending and salary descending.
2. Assign a dense performance rank.
3. Filter employees with performance scores of at least 85.
4. Return employee, department, salary, performance_score, and performance_rank.
5. Reset the index.
6. Explain how ranking and sorting can help an analyst identify high-performing employees without losing track of tied scores.

In [26]:
df = pd.DataFrame({
    "employee": ["Asha", "Rahul", "Neha", "Vikram", "Priya", "Aman"],
    "department": ["IT", "Sales", "IT", "HR", "Sales", "HR"],
    "salary": [60000, 45000, 75000, 50000, 45000, 65000],
    "experience": [3, 2, 5, 4, 2, 6],
    "performance_score": [85, 78, 92, 80, 88, 92]
})
df

  employee department  salary  experience  performance_score
0     Asha         IT   60000           3                 85
1    Rahul      Sales   45000           2                 78
2     Neha         IT   75000           5                 92
3   Vikram         HR   50000           4                 80
4    Priya      Sales   45000           2                 88
5     Aman         HR   65000           6                 92

In [27]:
#Sort employees by performance score descending and salary descending.
df=df.sort_values(by=['performance_score','salary'],ascending=[False,True])
df

  employee department  salary  experience  performance_score
5     Aman         HR   65000           6                 92
2     Neha         IT   75000           5                 92
4    Priya      Sales   45000           2                 88
0     Asha         IT   60000           3                 85
3   Vikram         HR   50000           4                 80
1    Rahul      Sales   45000           2                 78

In [28]:
#Assign a dense performance rank.
df['performance_rank']=df['performance_score'].rank(method='min',ascending=False).astype(int)
df

  employee department  salary  experience  performance_score  performance_rank
5     Aman         HR   65000           6                 92                 1
2     Neha         IT   75000           5                 92                 1
4    Priya      Sales   45000           2                 88                 3
0     Asha         IT   60000           3                 85                 4
3   Vikram         HR   50000           4                 80                 5
1    Rahul      Sales   45000           2                 78                 6

In [29]:
#Filter employees with performance scores of at least 85.
df=df[df['performance_score']>=85]
df

  employee department  salary  experience  performance_score  performance_rank
5     Aman         HR   65000           6                 92                 1
2     Neha         IT   75000           5                 92                 1
4    Priya      Sales   45000           2                 88                 3
0     Asha         IT   60000           3                 85                 4

In [30]:
df=df.reset_index(drop=True)
df

  employee department  salary  experience  performance_score  performance_rank
0     Aman         HR   65000           6                 92                 1
1     Neha         IT   75000           5                 92                 1
2    Priya      Sales   45000           2                 88                 3
3     Asha         IT   60000           3                 85                 4