# Batch 2 - Advanced Filtering, Boolean Masks and Conditional Selection

In [6]:
import pandas as pd

df = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "age": [22, 35, 28, 42, 31, 25, 38, 45],
    "purchase_amount": [500, 1500, 800, 2000, 1200, 700, 1800, 2500],
    "city": [
        "Delhi", "Mumbai", "Delhi", "Pune",
        "Mumbai", "Pune", "Delhi", "Mumbai"
    ],
    "membership": [
        "Basic", "Premium", "Basic", "Premium",
        "Premium", "Basic", "Premium", "Basic"
    ]
})
df

  customer  age  purchase_amount    city membership
0        A   22              500   Delhi      Basic
1        B   35             1500  Mumbai    Premium
2        C   28              800   Delhi      Basic
3        D   42             2000    Pune    Premium
4        E   31             1200  Mumbai    Premium
5        F   25              700    Pune      Basic
6        G   38             1800   Delhi    Premium
7        H   45             2500  Mumbai      Basic

#### Q1. Multiple conditions with AND
Select customers whose age is greater than 30 and whose purchase_amount is greater than 1000.
Return only customer, age, and purchase_amount.

In [20]:
df[(df['age']>30) & (df['purchase_amount']>1000)][['customer','age','purchase_amount']]

  customer  age  purchase_amount
1        B   35             1500
3        D   42             2000
4        E   31             1200
6        G   38             1800
7        H   45             2500

#### Q2. Multiple conditions with OR
Select customers who live in Delhi or have a purchase amount greater than 2000.
Return all columns.

In [25]:
df[(df['city']=='Delhi') | (df['purchase_amount']>2000)]

  customer  age  purchase_amount    city membership
0        A   22              500   Delhi      Basic
2        C   28              800   Delhi      Basic
6        G   38             1800   Delhi    Premium
7        H   45             2500  Mumbai      Basic

#### Q3. Combining AND and OR
Select customers who meet either condition:
- They live in Mumbai and have Premium membership.
- Their age is greater than 40.
Return customer, age, city, and membership.

In [32]:
df[((df['city']=='Mumbai') & (df['membership']=='Premium')
|
(df['age']>40))][['customer','age','city','membership']]

  customer  age    city membership
1        B   35  Mumbai    Premium
3        D   42    Pune    Premium
4        E   31  Mumbai    Premium
7        H   45  Mumbai      Basic

#### Q4. Filtering with isin()
Select customers who live in either Delhi or Pune.
Use isin() rather than multiple OR conditions.

In [35]:
df[(df['city'].isin(['Delhi','Pune']))]

  customer  age  purchase_amount   city membership
0        A   22              500  Delhi      Basic
2        C   28              800  Delhi      Basic
3        D   42             2000   Pune    Premium
5        F   25              700   Pune      Basic
6        G   38             1800  Delhi    Premium

#### Q5. Excluding values
Select all customers who are not Basic members.
Solve this using the ~ operator and isin()

In [50]:
df[~(df['membership']).isin(['Basic'])]

  customer  age  purchase_amount    city membership
1        B   35             1500  Mumbai    Premium
3        D   42             2000    Pune    Premium
4        E   31             1200  Mumbai    Premium
6        G   38             1800   Delhi    Premium

#### Q6. Range-based filtering
Select customers whose age is between 25 and 40, inclusive.
Solve this using Boolean conditions, then solve it again using between().

In [53]:
df[(df['age'].between(25,40))]

  customer  age  purchase_amount    city membership
1        B   35             1500  Mumbai    Premium
2        C   28              800   Delhi      Basic
4        E   31             1200  Mumbai    Premium
5        F   25              700    Pune      Basic
6        G   38             1800   Delhi    Premium

In [59]:
df[(df['age']>=25) & (df['age']<=40)]

  customer  age  purchase_amount    city membership
1        B   35             1500  Mumbai    Premium
2        C   28              800   Delhi      Basic
4        E   31             1200  Mumbai    Premium
5        F   25              700    Pune      Basic
6        G   38             1800   Delhi    Premium

#### Q7. Conditional selection with query()
Use df.query() to select customers whose age is greater than 30 and whose purchase amount is at least 1500.
Return customer, age, and purchase_amount.

In [64]:
df.query('age>30 and purchase_amount>=1500')[['customer','age','purchase_amount']]

  customer  age  purchase_amount
1        B   35             1500
3        D   42             2000
6        G   38             1800
7        H   45             2500

#### Q8. Negating a Boolean condition
Select customers who either:
- Do not live in Mumbai, or
- Have a purchase amount less than 1000.
Use Boolean masks. Be careful with operator precedence.

In [67]:
df[~((df['city']=='Mumbai') | (df['purchase_amount']<1000))]

  customer  age  purchase_amount   city membership
3        D   42             2000   Pune    Premium
6        G   38             1800  Delhi    Premium

#### Q9. Missing values and Boolean masks
Create this DataFrame:
data = pd.DataFrame({    "customer": ["A", "B", "C", "D", "E"],    "age": [25, None, 35, 42, None],    "income": [30000, 50000, None, 70000, 45000]})



Select rows where age is not missing and income is greater than 40000. Explain why notna() is useful.

In [72]:
data = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [25, None, 35, 42, None],
    "income": [30000, 50000, None, 70000, 45000]
})
data

  customer   age   income
0        A  25.0  30000.0
1        B   NaN  50000.0
2        C  35.0      NaN
3        D  42.0  70000.0
4        E   NaN  45000.0

In [76]:
data[(data['age'].notna()) & (data['income']>40000)]

  customer   age   income
3        D  42.0  70000.0

#### Q10. Mini-project — Customer segmentation
Using the original df, create a filtered DataFrame containing customers who satisfy all these requirements:
- Age is at least 30.
- Purchase amount is at least 1200.
- Membership is Premium.
- City is either Mumbai or Delhi.
Then:
1. Return customer, age, city, membership, and purchase_amount.
2. Sort the result by purchase_amount in descending order.
3. Reset the index.
4. Explain how this type of filtering could be useful before training an ML model.

In [104]:
df1=df.query("age>=30 and purchase_amount>=1200 and membership=='Premium' and city in ['Mumbai','Delhi']")
df1

  customer  age  purchase_amount    city membership
1        B   35             1500  Mumbai    Premium
4        E   31             1200  Mumbai    Premium
6        G   38             1800   Delhi    Premium

In [106]:
df1.sort_values(by='purchase_amount',ascending=False)

  customer  age  purchase_amount    city membership
6        G   38             1800   Delhi    Premium
1        B   35             1500  Mumbai    Premium
4        E   31             1200  Mumbai    Premium

In [108]:
df1.reset_index()

   index customer  age  purchase_amount    city membership
0      1        B   35             1500  Mumbai    Premium
1      4        E   31             1200  Mumbai    Premium
2      6        G   38             1800   Delhi    Premium