#### Batch 4 — Advanced Selection and Indexing Mini-Projects

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "age": [22, 35, 28, 42, 31, 25, 38, 45],
    "city": [
        "Delhi", "Mumbai", "Delhi", "Pune",
        "Mumbai", "Pune", "Delhi", "Mumbai"
    ],
    "orders": [2, 8, 4, 10, 6, 3, 9, 12],
    "revenue": [500, 2500, 1200, 4000, 1800, 700, 3200, 5000],
    "satisfaction": [3.5, 4.8, 4.0, 4.9, 4.2, 3.2, 4.7, 4.9]
})
df

   customer_id  age    city  orders  revenue  satisfaction
0          101   22   Delhi       2      500           3.5
1          102   35  Mumbai       8     2500           4.8
2          103   28   Delhi       4     1200           4.0
3          104   42    Pune      10     4000           4.9
4          105   31  Mumbai       6     1800           4.2
5          106   25    Pune       3      700           3.2
6          107   38   Delhi       9     3200           4.7
7          108   45  Mumbai      12     5000           4.9

#### Q1. Conditional column selection
Select customers whose revenue exceeds 2,000 and whose satisfaction score is at least 4.5. Return only customer_id, revenue, and satisfaction.

In [4]:
df[(df['revenue']>2000) & (df['satisfaction']>=4.5)][['customer_id','revenue','satisfaction']]

   customer_id  revenue  satisfaction
1          102     2500           4.8
3          104     4000           4.9
6          107     3200           4.7
7          108     5000           4.9

#### Q2. Advanced Boolean filtering
Select customers who live in Delhi or Mumbai, have at least 5 orders, and are younger than 40. Use properly parenthesized Boolean masks.

In [6]:
df[(df['city'].isin(['Delhi','Mumbai'])) & (df['orders']>=5) & (df['age']<40)]

   customer_id  age    city  orders  revenue  satisfaction
1          102   35  Mumbai       8     2500           4.8
4          105   31  Mumbai       6     1800           4.2
6          107   38   Delhi       9     3200           4.7

#### Q3. loc with conditional selection
Use .loc to select rows where revenue is at least 1,800 and update their satisfaction score by adding 0.1. Cap the updated score at 5.0.

In [8]:
mask=df['revenue']>=1800
df.loc[mask,'satisfaction']=(df.loc[mask,'satisfaction']+0.1).clip(upper=5.0)
df.loc[mask]

   customer_id  age    city  orders  revenue  satisfaction
1          102   35  Mumbai       8     2500           4.9
3          104   42    Pune      10     4000           5.0
4          105   31  Mumbai       6     1800           4.3
6          107   38   Delhi       9     3200           4.8
7          108   45  Mumbai      12     5000           5.0

#### Q4. iloc with row and column positions
Retrieve rows at positions 1, 3, and 5, and columns at positions 0, 1, and 4. Explain the difference between label-based and position-based selection.

In [10]:
df.iloc[[1,3,5],[0,1,4]]

   customer_id  age  revenue
1          102   35     2500
3          104   42     4000
5          106   25      700

#### Q5. Indexing and reindexing
Set customer_id as the index. Then reindex the DataFrame to customer IDs [101, 103, 105, 109]. Explain what happens to customer 109 and why.

In [12]:
df

   customer_id  age    city  orders  revenue  satisfaction
0          101   22   Delhi       2      500           3.5
1          102   35  Mumbai       8     2500           4.9
2          103   28   Delhi       4     1200           4.0
3          104   42    Pune      10     4000           5.0
4          105   31  Mumbai       6     1800           4.3
5          106   25    Pune       3      700           3.2
6          107   38   Delhi       9     3200           4.8
7          108   45  Mumbai      12     5000           5.0

In [13]:
df_index=df.set_index('customer_id',drop=True)
df_index

             age    city  orders  revenue  satisfaction
customer_id
101           22   Delhi       2      500           3.5
102           35  Mumbai       8     2500           4.9
103           28   Delhi       4     1200           4.0
104           42    Pune      10     4000           5.0
105           31  Mumbai       6     1800           4.3
106           25    Pune       3      700           3.2
107           38   Delhi       9     3200           4.8
108           45  Mumbai      12     5000           5.0

In [14]:
df_reindex=df_index.reindex([101, 103, 105, 109])
df_reindex

              age    city  orders  revenue  satisfaction
customer_id
101          22.0   Delhi     2.0    500.0           3.5
103          28.0   Delhi     4.0   1200.0           4.0
105          31.0  Mumbai     6.0   1800.0           4.3
109           NaN     NaN     NaN      NaN           NaN

#### Q6. Multi-condition ranking
Rank customers by revenue in descending order, using the min method for ties. Explain how tied ranks are assigned.

In [16]:
df['revenue_rank']=df['revenue'].rank(method='min',ascending=False).astype(int)
df

   customer_id  age    city  orders  revenue  satisfaction  revenue_rank
0          101   22   Delhi       2      500           3.5             8
1          102   35  Mumbai       8     2500           4.9             4
2          103   28   Delhi       4     1200           4.0             6
3          104   42    Pune      10     4000           5.0             2
4          105   31  Mumbai       6     1800           4.3             5
5          106   25    Pune       3      700           3.2             7
6          107   38   Delhi       9     3200           4.8             3
7          108   45  Mumbai      12     5000           5.0             1

#### Q7. Missing-value filtering
Create a copy of the DataFrame and set the revenue for customer 103 and satisfaction for customer 106 to NaN. Select rows where both values are present using notna().

In [20]:
df_copy=df.copy()
df_copy.loc[df_copy['customer_id'] == 103, 'revenue'] = np.nan
df_copy.loc[df_copy['customer_id'] == 106, 'satisfaction'] = np.nan
df_copy

   customer_id  age    city  orders  revenue  satisfaction  revenue_rank
0          101   22   Delhi       2    500.0           3.5             8
1          102   35  Mumbai       8   2500.0           4.9             4
2          103   28   Delhi       4      NaN           4.0             6
3          104   42    Pune      10   4000.0           5.0             2
4          105   31  Mumbai       6   1800.0           4.3             5
5          106   25    Pune       3    700.0           NaN             7
6          107   38   Delhi       9   3200.0           4.8             3
7          108   45  Mumbai      12   5000.0           5.0             1

In [28]:
df_copy[(df_copy['revenue'].notna()) & (df_copy['satisfaction'].notna())]

   customer_id  age    city  orders  revenue  satisfaction  revenue_rank
0          101   22   Delhi       2    500.0           3.5             8
1          102   35  Mumbai       8   2500.0           4.9             4
3          104   42    Pune      10   4000.0           5.0             2
4          105   31  Mumbai       6   1800.0           4.3             5
6          107   38   Delhi       9   3200.0           4.8             3
7          108   45  Mumbai      12   5000.0           5.0             1

#### Q8. Top-N selection
Use nlargest() to retrieve the four customers with the highest revenue. Then sort those four customers by age in ascending order.

In [33]:
high_rev=df.nlargest(4,'revenue').sort_values(by='age')
high_rev

   customer_id  age    city  orders  revenue  satisfaction  revenue_rank
1          102   35  Mumbai       8     2500           4.9             4
6          107   38   Delhi       9     3200           4.8             3
3          104   42    Pune      10     4000           5.0             2
7          108   45  Mumbai      12     5000           5.0             1

#### Q9. Safe conditional updates
Create a copy of the DataFrame. Add a high_value column that is True when revenue is at least 2,500 and False otherwise. Then increase orders by 1 only for high-value customers, using .loc.

In [36]:
df_high=df.copy()
df_high['high_value']= df_high['revenue']>=2500
df_high

,customer_id,age,city,orders,revenue,satisfaction,revenue_rank,high_value
0,101,22,Delhi,2,500,3.5,8,False
1,102,35,Mumbai,8,2500,4.9,4,True
2,103,28,Delhi,4,1200,4.0,6,False
3,104,42,Pune,10,4000,5.0,2,True
4,105,31,Mumbai,6,1800,4.3,5,False
5,106,25,Pune,3,700,3.2,7,False
6,107,38,Delhi,9,3200,4.8,3,True
7,108,45,Mumbai,12,5000,5.0,1,True

In [46]:
mask=df_high['high_value']==True
df_high.loc[mask,'orders']=df_high.loc[mask,'orders']+1
df_high

,customer_id,age,city,orders,revenue,satisfaction,revenue_rank,high_value
0,101,22,Delhi,2,500,3.5,8,False
1,102,35,Mumbai,9,2500,4.9,4,True
2,103,28,Delhi,4,1200,4.0,6,False
3,104,42,Pune,11,4000,5.0,2,True
4,105,31,Mumbai,6,1800,4.3,5,False
5,106,25,Pune,3,700,3.2,7,False
6,107,38,Delhi,10,3200,4.8,3,True
7,108,45,Mumbai,13,5000,5.0,1,True

#### Q10. Mini-project — Customer targeting
Build a customer-targeting table that:
1. Selects customers aged 25–40, inclusive.
2. Requires revenue of at least 1,200 and satisfaction of at least 4.0.
3. Returns customer_id, age, city, revenue, and satisfaction.
4. Sorts by revenue descending.
5. Adds a revenue rank using dense ranking.
6. Resets the index.
7. Explains how this table could help identify customers for a marketing campaign and why selection criteria should be chosen carefully.

In [49]:
df

   customer_id  age    city  orders  revenue  satisfaction  revenue_rank
0          101   22   Delhi       2      500           3.5             8
1          102   35  Mumbai       8     2500           4.9             4
2          103   28   Delhi       4     1200           4.0             6
3          104   42    Pune      10     4000           5.0             2
4          105   31  Mumbai       6     1800           4.3             5
5          106   25    Pune       3      700           3.2             7
6          107   38   Delhi       9     3200           4.8             3
7          108   45  Mumbai      12     5000           5.0             1

In [55]:
#Selects customers aged 25–40, inclusive.
final=df[df['age'].between(25,40)]
final

   customer_id  age    city  orders  revenue  satisfaction  revenue_rank
1          102   35  Mumbai       8     2500           4.9             4
2          103   28   Delhi       4     1200           4.0             6
4          105   31  Mumbai       6     1800           4.3             5
5          106   25    Pune       3      700           3.2             7
6          107   38   Delhi       9     3200           4.8             3

In [57]:
#Requires revenue of at least 1,200 and satisfaction of at least 4.0.
final=final.query("revenue>=1200 and satisfaction>=4.0")
final

   customer_id  age    city  orders  revenue  satisfaction  revenue_rank
1          102   35  Mumbai       8     2500           4.9             4
2          103   28   Delhi       4     1200           4.0             6
4          105   31  Mumbai       6     1800           4.3             5
6          107   38   Delhi       9     3200           4.8             3

In [59]:
#Returns customer_id, age, city, revenue, and satisfaction.
final=final.drop(columns=['orders','revenue_rank'])
final

   customer_id  age    city  revenue  satisfaction
1          102   35  Mumbai     2500           4.9
2          103   28   Delhi     1200           4.0
4          105   31  Mumbai     1800           4.3
6          107   38   Delhi     3200           4.8

In [61]:
#Sorts by revenue descending.
final=final.sort_values(by='revenue', ascending = False)
final

   customer_id  age    city  revenue  satisfaction
6          107   38   Delhi     3200           4.8
1          102   35  Mumbai     2500           4.9
4          105   31  Mumbai     1800           4.3
2          103   28   Delhi     1200           4.0

In [65]:
#Adds a revenue rank using dense ranking.
final['revenue_rank']=final['revenue'].rank(method='min',ascending = False).astype(int)
final

   customer_id  age    city  revenue  satisfaction  revenue_rank
6          107   38   Delhi     3200           4.8             1
1          102   35  Mumbai     2500           4.9             2
4          105   31  Mumbai     1800           4.3             3
2          103   28   Delhi     1200           4.0             4

In [69]:
#Resets the index.
final=final.reset_index(drop=True)
final

   customer_id  age    city  revenue  satisfaction  revenue_rank
0          107   38   Delhi     3200           4.8             1
1          102   35  Mumbai     2500           4.9             2
2          105   31  Mumbai     1800           4.3             3
3          103   28   Delhi     1200           4.0             4