# Core concepts

#### Q1. Unique Values and Frequencies
Given:
import pandas as pddf = pd.DataFrame({    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi"],    "purchased": [1, 0, 1, 1, 0, 1]})



Write code to:
a. Find all unique cities.
b. Count the number of unique cities.
c. Count how many records belong to each city.
d. Count how many records have purchased = 1 and purchased = 0.

In [3]:
import pandas as pd

df = pd.DataFrame({
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi"],
    "purchased": [1, 0, 1, 1, 0, 1]
})
df

     city  purchased
0   Delhi          1
1  Mumbai          0
2   Delhi          1
3    Pune          1
4  Mumbai          0
5   Delhi          1

In [4]:
df['city'].unique()

array(['Delhi', 'Mumbai', 'Pune'], dtype=object)

In [5]:
df['city'].nunique()

3

In [6]:
df['city'].value_counts()

city
Delhi     3
Mumbai    2
Pune      1
Name: count, dtype: int64

In [7]:
print(df['purchased'].value_counts())

purchased
1    4
0    2
Name: count, dtype: int64

#### Q2. Understanding Summary Statistics
Given:
scores = pd.Series([60, 70, 80, 90, 100])



Answer the following:
a. Calculate the mean.
b. Calculate the median.
c. Calculate the standard deviation using pandas.
d. What does the minimum value tell you?
e. Why can summary statistics be useful before training an ML model?

In [9]:
scores = pd.Series([60, 70, 80, 90, 100])

In [10]:
print(scores.mean())

80.0

In [11]:
print(scores.median())

80.0

In [12]:
print(scores.std())

15.811388300841896

#### Q3. Creating and Removing Columns
Given:
df = pd.DataFrame({    "quantity": [2, 3, 5],    "unit_price": [100, 200, 150],    "product": ["A", "B", "C"]})



Write code to:
a. Create a new column named total_price by multiplying quantity by unit_price.
b. Create a column named high_value that is True when total_price is greater than 500 and False otherwise.
c. Remove the product column from the DataFrame.
d. Display the resulting DataFrame.

In [14]:
df = pd.DataFrame({
    "quantity": [2, 3, 5],
    "unit_price": [100, 200, 150],
    "product": ["A", "B", "C"]
})
df['total_price']=df['quantity']*df['unit_price']
df['high_value']=df['total_price']>500
df=df.drop(columns='product')
df

   quantity  unit_price  total_price  high_value
0         2         100          200       False
1         3         200          600        True
2         5         150          750        True

#### Q4. Sorting and Ranking
Given:
df = pd.DataFrame({    "student": ["Aman", "Priya", "Rahul", "Neha"],    "score": [75, 95, 60, 95]})



Write code to:
a. Sort the DataFrame by score in descending order.
b. Sort by score descending and then by student ascending.
c. Create a rank column based on descending scores, assigning tied scores the same minimum rank.
d. Explain what happens when two students have the same score.

In [16]:
df = pd.DataFrame({
    "student": ["Aman", "Priya", "Rahul", "Neha"],
    "score": [75, 95, 60, 95]
})
df_sorted=df.sort_values(by = 'score',ascending=False)
df_sorted

  student  score
1   Priya     95
3    Neha     95
0    Aman     75
2   Rahul     60

In [17]:
df_sorted2=df.sort_values(by = ['score','student'],ascending=[False,True])
df_sorted2

  student  score
3    Neha     95
1   Priya     95
0    Aman     75
2   Rahul     60

#### Q5. Applying Operations to Columns
Given:
df = pd.DataFrame({    "age": [20, 30, 40],    "salary": [20000, 40000, 60000]})



Write code to:
a. Increase every salary by 10%.
b. Create an age_group column that labels ages below 30 as "Young" and ages 30 or above as "Adult".
c. Calculate the salary-to-age ratio for each row.
d. Explain why vectorized pandas operations are generally preferable to manually looping over every row for simple calculations.

In [19]:
df = pd.DataFrame({
    "age": [20, 30, 40],
    "salary": [20000, 40000, 60000]
})
df['salary']=df['salary']+df['salary']*0.1
df

   age   salary
0   20  22000.0
1   30  44000.0
2   40  66000.0

In [20]:
df.loc[df['age']<30, 'age_group']='Young'
df.loc[df['age']>=30, 'age_group']='Adult'
df

   age   salary age_group
0   20  22000.0     Young
1   30  44000.0     Adult
2   40  66000.0     Adult

In [21]:
df['salary_age_ratio']=df['salary']/df['age']
df

   age   salary age_group  salary_age_ratio
0   20  22000.0     Young       1100.000000
1   30  44000.0     Adult       1466.666667
2   40  66000.0     Adult       1650.000000

#### Q6. Resetting and Understanding Indexes
Given:
df = pd.DataFrame({    "name": ["Aman", "Priya", "Rahul"],    "score": [80, 90, 70]}, index=[10, 20, 30])



Answer the following:
a. What is the index of this DataFrame?
b. Write code to reset the index while retaining the original index as a column.
c. Write code to reset the index and discard the old index.
d. Explain why resetting an index might be useful after combining or transforming datasets.

In [23]:
df = pd.DataFrame({
    "name": ["Aman", "Priya", "Rahul"],
    "score": [80, 90, 70]
}, index=[10, 20, 30])
#10, 20 ,30 are the indexes
df

     name  score
10   Aman     80
20  Priya     90
30  Rahul     70

In [24]:
df=df.reset_index()
df

   index   name  score
0     10   Aman     80
1     20  Priya     90
2     30  Rahul     70

In [25]:
df=df.drop(columns='index')
df

    name  score
0   Aman     80
1  Priya     90
2  Rahul     70

#### Resetting an index is useful after combining or transforming datasets because the original index may become duplicated, non-sequential, or no longer meaningful.

#### Q7. Unexpected Results from Column Operations
Consider:
df = pd.DataFrame({    "price": [100, 200, 300],    "quantity": [2, 3, 4]})df["total"] = df["price"] + df["quantity"]



The analyst intended to calculate total revenue per product.
Answer:
a. What values will the total column contain?
b. Why is the result incorrect for the intended calculation?
c. Write the corrected statement.
d. Calculate the expected total values.

In [28]:
df = pd.DataFrame({
    "price": [100, 200, 300],
    "quantity": [2, 3, 4]
})

df["total_revenue"] = df["price"] * df["quantity"]
df

   price  quantity  total_revenue
0    100         2            200
1    200         3            600
2    300         4           1200

#### Q8. Duplicate Records
Given:
df = pd.DataFrame({    "customer_id": [101, 102, 101, 103, 102],    "amount": [500, 700, 500, 300, 900]})



Write code to:
a. Count the number of completely duplicated rows.
b. Display the rows that are duplicated across all columns, excluding the first occurrence.
c. Count the number of unique customer IDs.
d. Explain why you should investigate duplicates before deleting them from an ML dataset.

In [30]:
df = pd.DataFrame({
    "customer_id": [101, 102, 101, 103, 102],
    "amount": [500, 700, 500, 300, 900]
})
df.duplicated().sum()

1

In [31]:
duplicates=df.duplicated()
duplicates
type(duplicates)

pandas.core.series.Series

In [32]:
df[df.duplicated()]

   customer_id  amount
2          101     500

In [33]:
df['customer_id'].nunique()

3

#### Q9. Inspecting Target Distribution
You are preparing a dataset for customer churn prediction:
df = pd.DataFrame({    "age": [25, 30, 45, 50, 28, 35, 42, 31],    "monthly_spend": [500, 700, 900, 850, 400, 600, 950, 650],    "churn": [0, 0, 1, 1, 0, 0, 1, 0]})



Write code to:
a. Count the occurrences of each target class.
b. Calculate the proportion of each target class.
c. Calculate the mean monthly spend for each churn class.
d. Explain why target distribution matters when evaluating a classification model.

In [35]:
df = pd.DataFrame({
    "age": [25, 30, 45, 50, 28, 35, 42, 31],
    "monthly_spend": [500, 700, 900, 850, 400, 600, 950, 650],
    "churn": [0, 0, 1, 1, 0, 0, 1, 0]
})
df

   age  monthly_spend  churn
0   25            500      0
1   30            700      0
2   45            900      1
3   50            850      1
4   28            400      0
5   35            600      0
6   42            950      1
7   31            650      0

In [36]:
df['churn'].value_counts()

churn
0    5
1    3
Name: count, dtype: int64

In [37]:
df['churn'].value_counts(normalize=True)*100

churn
0    62.5
1    37.5
Name: proportion, dtype: float64

In [38]:
df.groupby('churn')['monthly_spend'].mean()

churn
0    570.0
1    900.0
Name: monthly_spend, dtype: float64

#### Q10. Mini-Project — Initial Customer Data Analysis
Create this DataFrame:
df = pd.DataFrame({    "customer_id": [101, 102, 103, 104, 105, 106],    "age": [22, 35, 29, 41, 35, 22],    "monthly_spend": [1200, 2500, 1800, 3200, 2500, 1200],    "visits": [4, 8, 5, 9, 8, 4],    "churn": [0, 1, 0, 1, 1, 0]})



Write a complete solution that:
1. Displays the DataFrame's shape and data types.
2. Reports the number of unique values in each column.
3. Displays the frequency of each churn class.
4. Calculates mean, median and standard deviation for monthly_spend.
5. Creates a spend_per_visit column by dividing monthly_spend by visits.
6. Sorts customers by monthly_spend in descending order.
7. Checks for completely duplicated rows.
8. Groups the data by churn and calculates average monthly_spend and visits.
9. Prints a short interpretation of one finding from the results.

In [40]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106],
    "age": [22, 35, 29, 41, 35, 22],
    "monthly_spend": [1200, 2500, 1800, 3200, 2500, 1200],
    "visits": [4, 8, 5, 9, 8, 4],
    "churn": [0, 1, 0, 1, 1, 0]
})

print('Shape: ',df.shape, '\nDatatypes:\n',df.dtypes)

Shape:  (6, 5)
Datatypes:
 customer_id      int64
age              int64
monthly_spend    int64
visits           int64
churn            int64
dtype: object

In [41]:
df.nunique()

customer_id      6
age              4
monthly_spend    4
visits           4
churn            2
dtype: int64

In [42]:
df['churn'].value_counts(normalize=True)*100

churn
0    50.0
1    50.0
Name: proportion, dtype: float64

In [43]:
#Calculates mean, median and standard deviation for monthly_spend
df['monthly_spend'].agg(['mean','median','std'])

mean      2066.666667
median    2150.000000
std        804.155872
Name: monthly_spend, dtype: float64

In [44]:
#Creates a spend_per_visit column by dividing monthly_spend by visits.

df['spend_per_visit']=round(df['monthly_spend']/df['visits'],2)
df

   customer_id  age  monthly_spend  visits  churn  spend_per_visit
0          101   22           1200       4      0           300.00
1          102   35           2500       8      1           312.50
2          103   29           1800       5      0           360.00
3          104   41           3200       9      1           355.56
4          105   35           2500       8      1           312.50
5          106   22           1200       4      0           300.00

In [45]:
#Sorts customers by monthly_spend in descending order.
df_sorted=df.sort_values(by='monthly_spend',ascending=False)
df_sorted

   customer_id  age  monthly_spend  visits  churn  spend_per_visit
3          104   41           3200       9      1           355.56
1          102   35           2500       8      1           312.50
4          105   35           2500       8      1           312.50
2          103   29           1800       5      0           360.00
0          101   22           1200       4      0           300.00
5          106   22           1200       4      0           300.00

In [82]:
#Checks for completely duplicated rows.
df[df.duplicated()]

Empty DataFrame
Columns: [customer_id, age, monthly_spend, visits, churn, spend_per_visit]
Index: []

In [86]:
df.duplicated().sum()

0

In [92]:
#Groups the data by churn and calculates average monthly_spend and visits.

round(df.groupby('churn')[['monthly_spend','visits']].mean(),2)

       monthly_spend  visits
churn
0            1400.00    4.33
1            2733.33    8.33