# Foundations Consolidation and ML Dataset Inspection

#### Q1. Series and DataFrame Dimensions
Consider:
import pandas as pds = pd.Series([10, 20, 30, 40])df = pd.DataFrame({    "age": [22, 25, 30, 35],    "salary": [25000, 30000, 40000, 50000],    "purchased": [1, 0, 1, 1]})



Answer:
a. What is the shape of s?
b. What is the shape of df?
c. How many observations and features does df contain?
d. Why is a Series called one-dimensional?

In [3]:
import pandas as pd

s = pd.Series([10, 20, 30, 40])

df = pd.DataFrame({
    "age": [22, 25, 30, 35],
    "salary": [25000, 30000, 40000, 50000],
    "purchased": [1, 0, 1, 1]
})
s.shape

(4,)

In [5]:
df.shape

(4, 3)

In [7]:
df.size

12

#### Q2. Data Types in an ML Dataset
Consider:
df = pd.DataFrame({    "customer_id": [101, 102, 103],    "age": [25, 35, 45],    "income": ["30000", "45000", "60000"],    "city": ["Delhi", "Pune", "Mumbai"],    "churn": [0, 1, 0]})



Answer:
a. Write code to inspect all column data types.
b. Which column contains numeric-looking strings?
c. Which column is the likely target?
d. Why should you not blindly convert every column to a numeric data type?

In [10]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103],
    "age": [25, 35, 45],
    "income": ["30000", "45000", "60000"],
    "city": ["Delhi", "Pune", "Mumbai"],
    "churn": [0, 1, 0]
})

df.dtypes

customer_id     int64
age             int64
income         object
city           object
churn           int64
dtype: object

#### Q3. Understanding Inspection Methods
Explain the purpose of each method and give one example of when it is useful:
a. df.head()
b. df.shape
c. df.info()
d. df.describe()
e. df.isna().sum()

#### Q4. Create an ML Dataset
Create a DataFrame named employees with these columns:
- employee_id: 1, 2, 3, 4
- department: "IT", "Sales", "IT", "HR"
- experience: 1, 5, 3, 8
- salary: 25000, 45000, 35000, 60000
- left_company: 0, 0, 1, 0
Then write code to:
a. Display the first three rows.
b. Print the shape.
c. Display the column names and data types.
d. Calculate the mean salary.

In [24]:
df=pd.DataFrame({
    'employee_id':[1,2,3,4],
    'department':['IT','HR','IT','HR'],
    'experience':[1,5,3,8],
    'salary':[25000,45000,35000,60000],
    'left_company':[0,0,1,0]})
df

   employee_id department  experience  salary  left_company
0            1         IT           1   25000             0
1            2         HR           5   45000             0
2            3         IT           3   35000             1
3            4         HR           8   60000             0

In [26]:
df.head(3)

   employee_id department  experience  salary  left_company
0            1         IT           1   25000             0
1            2         HR           5   45000             0
2            3         IT           3   35000             1

In [28]:
df.shape

(4, 5)

In [30]:
df.columns

Index(['employee_id', 'department', 'experience', 'salary', 'left_company'], dtype='object')

In [32]:
df.dtypes

employee_id      int64
department      object
experience       int64
salary           int64
left_company     int64
dtype: object

In [34]:
df['salary'].mean()

41250.0

#### Q5. Unique Values and Descriptive Statistics
Using the employees DataFrame from Q4, write code to:
a. Find the unique departments.
b. Count the unique departments.
c. Calculate the number of employees in each department.
d. Generate descriptive statistics for numeric columns.
e. Calculate the median experience.

In [37]:
df['department'].unique()

array(['IT', 'HR'], dtype=object)

In [39]:
df['department'].nunique()

2

In [41]:
df.groupby('department')['employee_id'].count()

department
HR    2
IT    2
Name: employee_id, dtype: int64

In [43]:
df.describe()

       employee_id  experience        salary  left_company
count     4.000000    4.000000      4.000000          4.00
mean      2.500000    4.250000  41250.000000          0.25
std       1.290994    2.986079  14930.394056          0.50
min       1.000000    1.000000  25000.000000          0.00
25%       1.750000    2.500000  32500.000000          0.00
50%       2.500000    4.000000  40000.000000          0.00
75%       3.250000    5.750000  48750.000000          0.25
max       4.000000    8.000000  60000.000000          1.00

In [45]:
df['experience'].median()

4.0

#### Q6. Create New Columns
Using the employees DataFrame, write code to:
a. Create salary_per_year_experience by dividing salary by experience.
b. Create senior_employee, which is True when experience is at least five years and False otherwise.
c. Calculate the number of employees who have left the company.
d. Explain why salary_per_year_experience may need special handling when experience is zero.

In [52]:
df['Create salary_per_year_experience']=round(df['salary']/df['experience'],2)
df

,employee_id,department,experience,salary,left_company,Create salary_per_year_experience
0,1,IT,1,25000,0,25000.00
1,2,HR,5,45000,0,9000.00
2,3,IT,3,35000,1,11666.67
3,4,HR,8,60000,0,7500.00

In [54]:
df['senior_employees']=df['experience']>=5

In [56]:
df

,employee_id,department,experience,salary,left_company,Create salary_per_year_experience,senior_employees
0,1,IT,1,25000,0,25000.00,False
1,2,HR,5,45000,0,9000.00,True
2,3,IT,3,35000,1,11666.67,False
3,4,HR,8,60000,0,7500.00,True

In [60]:
(df['left_company']==1).sum()

1

#### Q7. Debug DataFrame Construction
The following code raises an error:
df = pd.DataFrame({    "age": [20, 25, 30, 35],    "salary": [25000, 30000, 40000],    "churn": [0, 1, 0, 1]})



Answer:
a. What causes the error?
b. Correct the code while preserving all four ages and all four churn values.
c. What shape should the corrected DataFrame have?
d. Write code to verify the shape.

df = pd.DataFrame({
    "age": [20, 25, 30, 35],
    "salary": [25000, 30000, 40000],
    "churn": [0, 1, 0, 1]
})

salary has 3 values only

In [64]:
df = pd.DataFrame({
    "age": [20, 25, 30, 35],
    "salary": [25000, 30000,55000, 40000],
    "churn": [0, 1, 0, 1]
})
df

   age  salary  churn
0   20   25000      0
1   25   30000      1
2   30   55000      0
3   35   40000      1

#### Q8. Investigate Data Quality
Consider:
df = pd.DataFrame({    "age": [22, 30, None, 40, 30],    "income": ["25000", "40000", "unknown", "60000", "40000"],    "city": ["Delhi", "Pune", "Delhi", None, "Pune"],    "churn": [0, 1, 0, 1, 1]})



Write code to:
a. Inspect the data types.
b. Count missing values per column.
c. Count completely duplicated rows.
d. Identify unique values in income.
e. Explain two issues that should be investigated before using this data for ML.
Do not clean the data yet.

In [69]:
df = pd.DataFrame({
    "age": [22, 30, None, 40, 30],
    "income": ["25000", "40000", "unknown", "60000", "40000"],
    "city": ["Delhi", "Pune", "Delhi", None, "Pune"],
    "churn": [0, 1, 0, 1, 1]
})
df

    age   income   city  churn
0  22.0    25000  Delhi      0
1  30.0    40000   Pune      1
2   NaN  unknown  Delhi      0
3  40.0    60000   None      1
4  30.0    40000   Pune      1

In [71]:
df.dtypes

age       float64
income     object
city       object
churn       int64
dtype: object

In [79]:
df.isnull().sum()

age       1
income    0
city      1
churn     0
dtype: int64

In [85]:
df.duplicated().sum()

1

In [87]:
df['income'].unique()

array(['25000', '40000', 'unknown', '60000'], dtype=object)

#### Q9. Features, Target and Data Readiness
You are building a customer churn model using:
customer_id, age, monthly_spend, visits, churn
Answer:
a. Identify the target variable.
b. Identify the candidate feature columns.
c. Explain why customer_id may be inappropriate as a feature.
d. Name three pandas operations you would use to inspect the dataset before modeling.
e. Explain how missing values and incorrect data types could affect model training.

#### Q10. Final Mini-Project — ML Dataset Audit
Create the following DataFrame:
df = pd.DataFrame({    "customer_id": [101, 102, 103, 104, 105, 106],    "age": [22, 35, None, 41, 35, 22],    "monthly_spend": [1200, 2500, 1800, None, 2500, 1200],    "visits": [4, 8, 5, 9, 8, 4],    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi"],    "churn": [0, 1, 0, 1, 1, 0]})



Write a complete Python solution that:
1. Imports pandas and creates the DataFrame.
2. Displays the first five and last two rows.
3. Prints the number of rows and columns.
4. Displays the column names, data types and non-null counts.
5. Calculates missing values and missing-value percentages per column.
6. Calculates numeric descriptive statistics.
7. Counts unique values in every column.
8. Reports the frequency of each churn class.
9. Checks for completely duplicated rows.
10. Prints a short data-readiness report identifying potential issues without modifying the dataset.
Do not train a model, remove rows or impute values.

In [113]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106],
    "age": [22, 35, None, 41, 35, 22],
    "monthly_spend": [1200, 2500, 1800, None, 2500, 1200],
    "visits": [4, 8, 5, 9, 8, 4],
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai", "Delhi"],
    "churn": [0, 1, 0, 1, 1, 0]
})
df

   customer_id   age  monthly_spend  visits    city  churn
0          101  22.0         1200.0       4   Delhi      0
1          102  35.0         2500.0       8  Mumbai      1
2          103   NaN         1800.0       5   Delhi      0
3          104  41.0            NaN       9    Pune      1
4          105  35.0         2500.0       8  Mumbai      1
5          106  22.0         1200.0       4   Delhi      0

In [95]:
#Displays the first five and last two rows.
print(df.head(),'\n',df.tail(2))

   customer_id   age  monthly_spend  visits    city  churn
0          101  22.0         1200.0       4   Delhi      0
1          102  35.0         2500.0       8  Mumbai      1
2          103   NaN         1800.0       5   Delhi      0
3          104  41.0            NaN       9    Pune      1
4          105  35.0         2500.0       8  Mumbai      1
    customer_id   age  monthly_spend  visits    city  churn
4          105  35.0         2500.0       8  Mumbai      1
5          106  22.0         1200.0       4   Delhi      0

In [97]:
#Prints the number of rows and columns
df.shape

(6, 6)

In [99]:
#Displays the column names, data types and non-null counts.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    6 non-null      int64
 1   age            5 non-null      float64
 2   monthly_spend  5 non-null      float64
 3   visits         6 non-null      int64
 4   city           6 non-null      object
 5   churn          6 non-null      int64
dtypes: float64(2), int64(3), object(1)
memory usage: 420.0+ bytes

In [101]:
#Calculates missing values and missing-value percentages per column.
df.isnull().sum()

customer_id      0
age              1
monthly_spend    1
visits           0
city             0
churn            0
dtype: int64

In [103]:
(df.isnull().sum()/df.size)*100

customer_id      0.000000
age              2.777778
monthly_spend    2.777778
visits           0.000000
city             0.000000
churn            0.000000
dtype: float64

In [105]:
# Calculates numeric descriptive statistics.
df.describe()

       customer_id        age  monthly_spend    visits     churn
count     6.000000   5.000000       5.000000  6.000000  6.000000
mean    103.500000  31.000000    1840.000000  6.333333  0.500000
std       1.870829   8.573214     650.384502  2.250926  0.547723
min     101.000000  22.000000    1200.000000  4.000000  0.000000
25%     102.250000  22.000000    1200.000000  4.250000  0.000000
50%     103.500000  35.000000    1800.000000  6.500000  0.500000
75%     104.750000  35.000000    2500.000000  8.000000  1.000000
max     106.000000  41.000000    2500.000000  9.000000  1.000000

In [107]:
#Counts unique values in every column.
df.nunique()

customer_id      6
age              3
monthly_spend    3
visits           4
city             3
churn            2
dtype: int64

In [109]:
#Reports the frequency of each churn class.
df['churn'].value_counts(normalize=True)*100

churn
0    50.0
1    50.0
Name: proportion, dtype: float64

In [111]:
df[df.duplicated()]

Empty DataFrame
Columns: [customer_id, age, monthly_spend, visits, city, churn]
Index: []

In [117]:
df.duplicated().sum()

0