# Advanced Date Filtering, Time Differences & Time-Based Features

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'order_id': range(2001, 2016),
    'customer_id': [
        101, 102, 101, 103, 104, 102, 105, 101,
        103, 106, 104, 105, 102, 107, 101
    ],
    'order_date': [
        '2026-01-05', '2026-01-19', '2026-02-05',
        '2026-02-27', '2026-03-02', '2026-03-15',
        '2026-03-31', '2026-04-05', '2026-04-20',
        '2026-05-01', '2026-05-17', '2026-06-01',
        '2026-06-15', '2026-06-29', '2026-06-30'
    ],
    'sales': [
        1200, 2500, 1800, 3200, 900, 4100, 1500,
        2700, 3500, 2200, 4800, 1300, 2900, 1700, 5200
    ],
    'status': [
        'Completed', 'Completed', 'Cancelled', 'Completed',
        'Completed', 'Completed', 'Cancelled', 'Completed',
        'Completed', 'Completed', 'Cancelled', 'Completed',
        'Completed', 'Completed', 'Completed'
    ]
})

df['order_date'] = pd.to_datetime(df['order_date'])
df

    order_id  customer_id order_date  sales     status
0       2001          101 2026-01-05   1200  Completed
1       2002          102 2026-01-19   2500  Completed
2       2003          101 2026-02-05   1800  Cancelled
3       2004          103 2026-02-27   3200  Completed
4       2005          104 2026-03-02    900  Completed
5       2006          102 2026-03-15   4100  Completed
6       2007          105 2026-03-31   1500  Cancelled
7       2008          101 2026-04-05   2700  Completed
8       2009          103 2026-04-20   3500  Completed
9       2010          106 2026-05-01   2200  Completed
10      2011          104 2026-05-17   4800  Cancelled
11      2012          105 2026-06-01   1300  Completed
12      2013          102 2026-06-15   2900  Completed
13      2014          107 2026-06-29   1700  Completed
14      2015          101 2026-06-30   5200  Completed

#### Q1. Month start and month end

Create month_start and month_end columns representing the beginning and end of each order's calendar month.

In [4]:
df['month_start'] = df['order_date'].dt.to_period('M').dt.start_time
df['month_end'] = df['order_date'].dt.to_period('M').dt.end_time

df

,order_id,customer_id,order_date,sales,status,month_start,month_end
0,2001,101,2026-01-05,1200,Completed,2026-01-01,2026-01-31 23:59:59.999999999
1,2002,102,2026-01-19,2500,Completed,2026-01-01,2026-01-31 23:59:59.999999999
2,2003,101,2026-02-05,1800,Cancelled,2026-02-01,2026-02-28 23:59:59.999999999
3,2004,103,2026-02-27,3200,Completed,2026-02-01,2026-02-28 23:59:59.999999999
4,2005,104,2026-03-02,900,Completed,2026-03-01,2026-03-31 23:59:59.999999999
5,2006,102,2026-03-15,4100,Completed,2026-03-01,2026-03-31 23:59:59.999999999
6,2007,105,2026-03-31,1500,Cancelled,2026-03-01,2026-03-31 23:59:59.999999999
7,2008,101,2026-04-05,2700,Completed,2026-04-01,2026-04-30 23:59:59.999999999
8,2009,103,2026-04-20,3500,Completed,2026-04-01,2026-04-30 23:59:59.999999999
9,2010,106,2026-05-01,2200,Completed,2026-05-01,2026-05-31 23:59:59.999999999
10,2011,104,2026-05-17,4800,Cancelled,2026-05-01,2026-05-31 23:59:59.999999999
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999
13,2014,107,2026-06-29,1700,Completed,2026-06-01,2026-06-30 23:59:59.999999999
14,2015,101,2026-06-30,5200,Completed,2026-06-01,2026-06-30 23:59:59.999999999

#### Q2. Quarter identification

Create a quarter_label column such as 2026-Q1. Use the order date to derive both the year and quarter

In [6]:
df['quarter_label'] = (
    df['order_date'].dt.year.astype(str)
    + '-Q'
    + df['order_date'].dt.quarter.astype(str)
)

df

,order_id,customer_id,order_date,sales,status,month_start,month_end,quarter_label
0,2001,101,2026-01-05,1200,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1
1,2002,102,2026-01-19,2500,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1
2,2003,101,2026-02-05,1800,Cancelled,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1
3,2004,103,2026-02-27,3200,Completed,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1
4,2005,104,2026-03-02,900,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1
5,2006,102,2026-03-15,4100,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1
6,2007,105,2026-03-31,1500,Cancelled,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1
7,2008,101,2026-04-05,2700,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2
8,2009,103,2026-04-20,3500,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2
9,2010,106,2026-05-01,2200,Completed,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2
10,2011,104,2026-05-17,4800,Cancelled,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2
13,2014,107,2026-06-29,1700,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2
14,2015,101,2026-06-30,5200,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2

#### Q3. Previous and next dates

Create columns for the previous calendar day and the next calendar day relative to each order date.

In [8]:
df['previous_day'] = df['order_date'] - pd.Timedelta(days=1)
df['next_day'] = df['order_date'] + pd.Timedelta(days=1)

df

,order_id,customer_id,order_date,sales,status,month_start,month_end,quarter_label,previous_day,next_day
0,2001,101,2026-01-05,1200,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-04,2026-01-06
1,2002,102,2026-01-19,2500,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-18,2026-01-20
2,2003,101,2026-02-05,1800,Cancelled,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-04,2026-02-06
3,2004,103,2026-02-27,3200,Completed,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-26,2026-02-28
4,2005,104,2026-03-02,900,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-01,2026-03-03
5,2006,102,2026-03-15,4100,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-14,2026-03-16
6,2007,105,2026-03-31,1500,Cancelled,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-30,2026-04-01
7,2008,101,2026-04-05,2700,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-04,2026-04-06
8,2009,103,2026-04-20,3500,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-19,2026-04-21
9,2010,106,2026-05-01,2200,Completed,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-04-30,2026-05-02
10,2011,104,2026-05-17,4800,Cancelled,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-05-16,2026-05-18
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-05-31,2026-06-02
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-14,2026-06-16
13,2014,107,2026-06-29,1700,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-28,2026-06-30
14,2015,101,2026-06-30,5200,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-29,2026-07-01

#### Q4. Date offsets

Calculate the date 7 days after each order and the date 30 days before each order using Pandas date offsets or timedeltas.

In [10]:
df['date_offset']=df['order_date']+pd.Timedelta(days=7)
df

,order_id,customer_id,order_date,sales,status,month_start,month_end,quarter_label,previous_day,next_day,date_offset
0,2001,101,2026-01-05,1200,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-04,2026-01-06,2026-01-12
1,2002,102,2026-01-19,2500,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-18,2026-01-20,2026-01-26
2,2003,101,2026-02-05,1800,Cancelled,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-04,2026-02-06,2026-02-12
3,2004,103,2026-02-27,3200,Completed,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-26,2026-02-28,2026-03-06
4,2005,104,2026-03-02,900,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-01,2026-03-03,2026-03-09
5,2006,102,2026-03-15,4100,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-14,2026-03-16,2026-03-22
6,2007,105,2026-03-31,1500,Cancelled,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-30,2026-04-01,2026-04-07
7,2008,101,2026-04-05,2700,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-04,2026-04-06,2026-04-12
8,2009,103,2026-04-20,3500,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-19,2026-04-21,2026-04-27
9,2010,106,2026-05-01,2200,Completed,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-04-30,2026-05-02,2026-05-08
10,2011,104,2026-05-17,4800,Cancelled,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-05-16,2026-05-18,2026-05-24
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-05-31,2026-06-02,2026-06-08
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-14,2026-06-16,2026-06-22
13,2014,107,2026-06-29,1700,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-28,2026-06-30,2026-07-06
14,2015,101,2026-06-30,5200,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-29,2026-07-01,2026-07-07

#### Q5. Business-day calculation

Calculate the number of business days between each order date and seven calendar days after it. Exclude Saturdays and Sundays using NumPy's busday_count.

In [12]:
df['business_days'] = np.busday_count(
    df['order_date'].values.astype('datetime64[D]'),
    df['date_offset'].values.astype('datetime64[D]')
)

df

,order_id,customer_id,order_date,sales,status,month_start,month_end,quarter_label,previous_day,next_day,date_offset,business_days
0,2001,101,2026-01-05,1200,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-04,2026-01-06,2026-01-12,5
1,2002,102,2026-01-19,2500,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-18,2026-01-20,2026-01-26,5
2,2003,101,2026-02-05,1800,Cancelled,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-04,2026-02-06,2026-02-12,5
3,2004,103,2026-02-27,3200,Completed,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-26,2026-02-28,2026-03-06,5
4,2005,104,2026-03-02,900,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-01,2026-03-03,2026-03-09,5
5,2006,102,2026-03-15,4100,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-14,2026-03-16,2026-03-22,5
6,2007,105,2026-03-31,1500,Cancelled,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-30,2026-04-01,2026-04-07,5
7,2008,101,2026-04-05,2700,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-04,2026-04-06,2026-04-12,5
8,2009,103,2026-04-20,3500,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-19,2026-04-21,2026-04-27,5
9,2010,106,2026-05-01,2200,Completed,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-04-30,2026-05-02,2026-05-08,5
10,2011,104,2026-05-17,4800,Cancelled,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-05-16,2026-05-18,2026-05-24,5
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-05-31,2026-06-02,2026-06-08,5
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-14,2026-06-16,2026-06-22,5
13,2014,107,2026-06-29,1700,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-28,2026-06-30,2026-07-06,5
14,2015,101,2026-06-30,5200,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-29,2026-07-01,2026-07-07,5

#### Q6. Month-to-date filtering

For a fixed reference date of June 20, 2026, filter orders from June 1 through June 20, inclusive.

In [14]:
sel_orders=df[df['order_date'].between('2026-06-01','2026-06-20')]
sel_orders

,order_id,customer_id,order_date,sales,status,month_start,month_end,quarter_label,previous_day,next_day,date_offset,business_days
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-05-31,2026-06-02,2026-06-08,5
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-14,2026-06-16,2026-06-22,5

#### Q7. Trailing 30-day window

For the same reference date, select orders in the trailing 30-calendar-day window, including June 20 but excluding dates before May 22. Explain your boundary conditions.

In [16]:
reference_date = pd.Timestamp('2026-06-20')
start_date = reference_date - pd.Timedelta(days=29)

sel_orders = df[
    df['order_date'].between(start_date, reference_date, inclusive='both')
]

sel_orders

,order_id,customer_id,order_date,sales,status,month_start,month_end,quarter_label,previous_day,next_day,date_offset,business_days
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-05-31,2026-06-02,2026-06-08,5
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-14,2026-06-16,2026-06-22,5

#### Q8. Customer purchase recency

For each customer, calculate the number of days since their most recent order as of June 30, 2026

In [18]:
reference_date = pd.Timestamp('2026-06-30')

customer_report = (
    df.groupby('customer_id', as_index=False)
      .agg(last_order_date=('order_date', 'max'))
)

customer_report['days_since_last_order'] = (
    reference_date - customer_report['last_order_date']
).dt.days

customer_report

   customer_id last_order_date  days_since_last_order
0          101      2026-06-30                      0
1          102      2026-06-15                     15
2          103      2026-04-20                     71
3          104      2026-05-17                     44
4          105      2026-06-01                     29
5          106      2026-05-01                     60
6          107      2026-06-29                      1

#### Q9. First and latest purchase

Create a customer-level DataFrame containing each customer's first purchase date, latest purchase date, and total number of orders.

In [20]:
report=df.groupby('customer_id').agg(
    first_purchase=('order_date','min'),
    latest_purchase=('order_date','max'),
    NO_of_orders=('order_id','count')
)
report

            first_purchase latest_purchase  NO_of_orders
customer_id
101             2026-01-05      2026-06-30             4
102             2026-01-19      2026-06-15             3
103             2026-02-27      2026-04-20             2
104             2026-03-02      2026-05-17             2
105             2026-03-31      2026-06-01             2
106             2026-05-01      2026-05-01             1
107             2026-06-29      2026-06-29             1

#### Q10. Customer activity segmentation

Using June 30, 2026, as the reference date, categorize each customer based on their latest purchase:
- Active: 0–30 days ago
- At Risk: 31–60 days ago
- Inactive: more than 60 days ago
Build a customer-level report with customer_id, last_order_date, days_since_last_order, and activity_status.

In [39]:

reference_date = pd.Timestamp('2026-06-30')

customer_report = (
    df.groupby('customer_id', as_index=False)
      .agg(last_order_date=('order_date', 'max'))
)

customer_report['days_since_last_order'] = (
    reference_date - customer_report['last_order_date']
).dt.days


df = df.merge(
    customer_report[['customer_id', 'days_since_last_order']],
    on='customer_id',
    how='left'
)

In [24]:
conditions=[
    df['days_since_last_order'].between(0,30),
    df['days_since_last_order'].between(31,60),
    df['days_since_last_order']>60
    
]
labels=['Active','At Risk','Inactive']
df['activity_status']=np.select(conditions,labels)
df

,order_id,customer_id,order_date,sales,status,month_start,month_end,quarter_label,previous_day,next_day,date_offset,business_days,days_since_last_order,activity_status
0,2001,101,2026-01-05,1200,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-04,2026-01-06,2026-01-12,5,0,Active
1,2002,102,2026-01-19,2500,Completed,2026-01-01,2026-01-31 23:59:59.999999999,2026-Q1,2026-01-18,2026-01-20,2026-01-26,5,15,Active
2,2003,101,2026-02-05,1800,Cancelled,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-04,2026-02-06,2026-02-12,5,0,Active
3,2004,103,2026-02-27,3200,Completed,2026-02-01,2026-02-28 23:59:59.999999999,2026-Q1,2026-02-26,2026-02-28,2026-03-06,5,71,Inactive
4,2005,104,2026-03-02,900,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-01,2026-03-03,2026-03-09,5,44,At Risk
5,2006,102,2026-03-15,4100,Completed,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-14,2026-03-16,2026-03-22,5,15,Active
6,2007,105,2026-03-31,1500,Cancelled,2026-03-01,2026-03-31 23:59:59.999999999,2026-Q1,2026-03-30,2026-04-01,2026-04-07,5,29,Active
7,2008,101,2026-04-05,2700,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-04,2026-04-06,2026-04-12,5,0,Active
8,2009,103,2026-04-20,3500,Completed,2026-04-01,2026-04-30 23:59:59.999999999,2026-Q2,2026-04-19,2026-04-21,2026-04-27,5,71,Inactive
9,2010,106,2026-05-01,2200,Completed,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-04-30,2026-05-02,2026-05-08,5,60,At Risk
10,2011,104,2026-05-17,4800,Cancelled,2026-05-01,2026-05-31 23:59:59.999999999,2026-Q2,2026-05-16,2026-05-18,2026-05-24,5,44,At Risk
11,2012,105,2026-06-01,1300,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-05-31,2026-06-02,2026-06-08,5,29,Active
12,2013,102,2026-06-15,2900,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-14,2026-06-16,2026-06-22,5,15,Active
13,2014,107,2026-06-29,1700,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-28,2026-06-30,2026-07-06,5,1,Active
14,2015,101,2026-06-30,5200,Completed,2026-06-01,2026-06-30 23:59:59.999999999,2026-Q2,2026-06-29,2026-07-01,2026-07-07,5,0,Active