# Date-Time Fundamentals

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'order_id': range(1001, 1013),
    'customer_id': [101, 102, 103, 101, 104, 105,
                    102, 106, 103, 104, 107, 101],
    'order_date': [
        '2026-01-05 09:30:00',
        '2026-01-12 14:15:00',
        '2026-02-03 11:00:00',
        '2026-02-18 16:45:00',
        '2026-03-07 10:20:00',
        '2026-03-21 18:30:00',
        '2026-04-02 08:45:00',
        '2026-04-15 12:10:00',
        '2026-05-09 15:00:00',
        '2026-05-22 19:20:00',
        '2026-06-11 13:35:00',
        '2026-06-25 17:50:00'
    ],
    'delivery_date': [
        '2026-01-08', '2026-01-17', '2026-02-08',
        '2026-02-23', '2026-03-10', '2026-03-29',
        '2026-04-05', '2026-04-21', '2026-05-15',
        '2026-05-27', '2026-06-16', '2026-06-30'
    ],
    'sales': [2500, 1800, 3200, 4200, 1500, 3800,
              2100, 4500, 2700, 3300, 1900, 5000],
    'status': [
        'Completed', 'Cancelled', 'Completed', 'Completed',
        'Completed', 'Cancelled', 'Completed', 'Completed',
        'Cancelled', 'Completed', 'Completed', 'Completed'
    ]
})

# Convert date columns to datetime
df['order_date'] = pd.to_datetime(df['order_date'])
df['delivery_date'] = pd.to_datetime(df['delivery_date'])
df

    order_id  customer_id          order_date delivery_date  sales     status
0       1001          101 2026-01-05 09:30:00    2026-01-08   2500  Completed
1       1002          102 2026-01-12 14:15:00    2026-01-17   1800  Cancelled
2       1003          103 2026-02-03 11:00:00    2026-02-08   3200  Completed
3       1004          101 2026-02-18 16:45:00    2026-02-23   4200  Completed
4       1005          104 2026-03-07 10:20:00    2026-03-10   1500  Completed
5       1006          105 2026-03-21 18:30:00    2026-03-29   3800  Cancelled
6       1007          102 2026-04-02 08:45:00    2026-04-05   2100  Completed
7       1008          106 2026-04-15 12:10:00    2026-04-21   4500  Completed
8       1009          103 2026-05-09 15:00:00    2026-05-15   2700  Cancelled
9       1010          104 2026-05-22 19:20:00    2026-05-27   3300  Completed
10      1011          107 2026-06-11 13:35:00    2026-06-16   1900  Completed
11      1012          101 2026-06-25 17:50:00    2026-06-30   5000  Completed

In [4]:
df.dtypes

order_id                  int64
customer_id               int64
order_date       datetime64[ns]
delivery_date    datetime64[ns]
sales                     int64
status                   object
dtype: object

#### Q2. Extract the year

Create a year column from order_date.

In [7]:
df['year']=df['order_date'].dt.year
df

,order_id,customer_id,order_date,delivery_date,sales,status,year
0,1001,101,2026-01-05 09:30:00,2026-01-08,2500,Completed,2026
1,1002,102,2026-01-12 14:15:00,2026-01-17,1800,Cancelled,2026
2,1003,103,2026-02-03 11:00:00,2026-02-08,3200,Completed,2026
3,1004,101,2026-02-18 16:45:00,2026-02-23,4200,Completed,2026
4,1005,104,2026-03-07 10:20:00,2026-03-10,1500,Completed,2026
5,1006,105,2026-03-21 18:30:00,2026-03-29,3800,Cancelled,2026
6,1007,102,2026-04-02 08:45:00,2026-04-05,2100,Completed,2026
7,1008,106,2026-04-15 12:10:00,2026-04-21,4500,Completed,2026
8,1009,103,2026-05-09 15:00:00,2026-05-15,2700,Cancelled,2026
9,1010,104,2026-05-22 19:20:00,2026-05-27,3300,Completed,2026
10,1011,107,2026-06-11 13:35:00,2026-06-16,1900,Completed,2026
11,1012,101,2026-06-25 17:50:00,2026-06-30,5000,Completed,2026

#### Q3. Extract month information

Create two columns:
- order_month: numeric month.
- month_name: full month name.

In [14]:
df['order_month']=df['order_date'].dt.month
df['order_month_name']=df['order_date'].dt.month_name()
df

,order_id,customer_id,order_date,delivery_date,sales,status,year,order_month,order_month_name
0,1001,101,2026-01-05 09:30:00,2026-01-08,2500,Completed,2026,1,January
1,1002,102,2026-01-12 14:15:00,2026-01-17,1800,Cancelled,2026,1,January
2,1003,103,2026-02-03 11:00:00,2026-02-08,3200,Completed,2026,2,February
3,1004,101,2026-02-18 16:45:00,2026-02-23,4200,Completed,2026,2,February
4,1005,104,2026-03-07 10:20:00,2026-03-10,1500,Completed,2026,3,March
5,1006,105,2026-03-21 18:30:00,2026-03-29,3800,Cancelled,2026,3,March
6,1007,102,2026-04-02 08:45:00,2026-04-05,2100,Completed,2026,4,April
7,1008,106,2026-04-15 12:10:00,2026-04-21,4500,Completed,2026,4,April
8,1009,103,2026-05-09 15:00:00,2026-05-15,2700,Cancelled,2026,5,May
9,1010,104,2026-05-22 19:20:00,2026-05-27,3300,Completed,2026,5,May
10,1011,107,2026-06-11 13:35:00,2026-06-16,1900,Completed,2026,6,June
11,1012,101,2026-06-25 17:50:00,2026-06-30,5000,Completed,2026,6,June

#### Q4. Extract day components

Create day, day_name, and quarter columns from order_date.

In [19]:
df['day']=df['order_date'].dt.day
df['day_name']=df['order_date'].dt.day_name()
df['quarter']=df['order_date'].dt.quarter
df

,order_id,customer_id,order_date,delivery_date,sales,status,year,order_month,order_month_name,day,day_name,quarter
0,1001,101,2026-01-05 09:30:00,2026-01-08,2500,Completed,2026,1,January,5,Monday,1
1,1002,102,2026-01-12 14:15:00,2026-01-17,1800,Cancelled,2026,1,January,12,Monday,1
2,1003,103,2026-02-03 11:00:00,2026-02-08,3200,Completed,2026,2,February,3,Tuesday,1
3,1004,101,2026-02-18 16:45:00,2026-02-23,4200,Completed,2026,2,February,18,Wednesday,1
4,1005,104,2026-03-07 10:20:00,2026-03-10,1500,Completed,2026,3,March,7,Saturday,1
5,1006,105,2026-03-21 18:30:00,2026-03-29,3800,Cancelled,2026,3,March,21,Saturday,1
6,1007,102,2026-04-02 08:45:00,2026-04-05,2100,Completed,2026,4,April,2,Thursday,2
7,1008,106,2026-04-15 12:10:00,2026-04-21,4500,Completed,2026,4,April,15,Wednesday,2
8,1009,103,2026-05-09 15:00:00,2026-05-15,2700,Cancelled,2026,5,May,9,Saturday,2
9,1010,104,2026-05-22 19:20:00,2026-05-27,3300,Completed,2026,5,May,22,Friday,2
10,1011,107,2026-06-11 13:35:00,2026-06-16,1900,Completed,2026,6,June,11,Thursday,2
11,1012,101,2026-06-25 17:50:00,2026-06-30,5000,Completed,2026,6,June,25,Thursday,2

#### Q5. Filter a date range

Select all orders placed between March 1 and April 30, 2026, inclusive.

In [24]:
sel_orders=df[df['order_date'].between('2026-03-01','2026-04-30')]
sel_orders

,order_id,customer_id,order_date,delivery_date,sales,status,year,order_month,order_month_name,day,day_name,quarter
4,1005,104,2026-03-07 10:20:00,2026-03-10,1500,Completed,2026,3,March,7,Saturday,1
5,1006,105,2026-03-21 18:30:00,2026-03-29,3800,Cancelled,2026,3,March,21,Saturday,1
6,1007,102,2026-04-02 08:45:00,2026-04-05,2100,Completed,2026,4,April,2,Thursday,2
7,1008,106,2026-04-15 12:10:00,2026-04-21,4500,Completed,2026,4,April,15,Wednesday,2

#### Q6. Filter by month

Select all orders placed in May 2026 using a datetime-based condition.

In [31]:
sel_order=df[df['order_month']==5]
sel_order

,order_id,customer_id,order_date,delivery_date,sales,status,year,order_month,order_month_name,day,day_name,quarter
8,1009,103,2026-05-09 15:00:00,2026-05-15,2700,Cancelled,2026,5,May,9,Saturday,2
9,1010,104,2026-05-22 19:20:00,2026-05-27,3300,Completed,2026,5,May,22,Friday,2

#### Q7. Calculate delivery duration

Create a delivery_days column representing the number of days between order_date and delivery_date. Use the date portion of order_date, not its time of day.

In [38]:
df['delivery_days']=(df['delivery_date']-df['order_date']).dt.days
df

,order_id,customer_id,order_date,delivery_date,sales,status,year,order_month,order_month_name,day,day_name,quarter,delivery_days
0,1001,101,2026-01-05 09:30:00,2026-01-08,2500,Completed,2026,1,January,5,Monday,1,2
1,1002,102,2026-01-12 14:15:00,2026-01-17,1800,Cancelled,2026,1,January,12,Monday,1,4
2,1003,103,2026-02-03 11:00:00,2026-02-08,3200,Completed,2026,2,February,3,Tuesday,1,4
3,1004,101,2026-02-18 16:45:00,2026-02-23,4200,Completed,2026,2,February,18,Wednesday,1,4
4,1005,104,2026-03-07 10:20:00,2026-03-10,1500,Completed,2026,3,March,7,Saturday,1,2
5,1006,105,2026-03-21 18:30:00,2026-03-29,3800,Cancelled,2026,3,March,21,Saturday,1,7
6,1007,102,2026-04-02 08:45:00,2026-04-05,2100,Completed,2026,4,April,2,Thursday,2,2
7,1008,106,2026-04-15 12:10:00,2026-04-21,4500,Completed,2026,4,April,15,Wednesday,2,5
8,1009,103,2026-05-09 15:00:00,2026-05-15,2700,Cancelled,2026,5,May,9,Saturday,2,5
9,1010,104,2026-05-22 19:20:00,2026-05-27,3300,Completed,2026,5,May,22,Friday,2,4
10,1011,107,2026-06-11 13:35:00,2026-06-16,1900,Completed,2026,6,June,11,Thursday,2,4
11,1012,101,2026-06-25 17:50:00,2026-06-30,5000,Completed,2026,6,June,25,Thursday,2,4

#### Q8. Find delayed deliveries

Identify orders whose delivery took more than five calendar days. Display their order IDs and delivery durations.

In [41]:
sel_orders=df[df['delivery_days']>5]
sel_orders

,order_id,customer_id,order_date,delivery_date,sales,status,year,order_month,order_month_name,day,day_name,quarter,delivery_days
5,1006,105,2026-03-21 18:30:00,2026-03-29,3800,Cancelled,2026,3,March,21,Saturday,1,7

#### Q9. Find the weekend orders

Filter orders placed on Saturday or Sunday using the date-time accessors.

In [52]:
sel_orders=df[df['order_date'].dt.dayofweek.isin([5,6])]
sel_orders

,order_id,customer_id,order_date,delivery_date,sales,status,year,order_month,order_month_name,day,day_name,quarter,delivery_days
4,1005,104,2026-03-07 10:20:00,2026-03-10,1500,Completed,2026,3,March,7,Saturday,1,2
5,1006,105,2026-03-21 18:30:00,2026-03-29,3800,Cancelled,2026,3,March,21,Saturday,1,7
8,1009,103,2026-05-09 15:00:00,2026-05-15,2700,Cancelled,2026,5,May,9,Saturday,2,5

#### Q10. Business analysis by month

Create a monthly report containing:
- order_count
- total_sales
- average_sales
- unique_customers
- cancelled_orders
Group by month in chronological order.

In [61]:
report=df.groupby('order_month').agg(
    order_count=('order_id','count'),
    total_sales=('sales','sum'),
    avg_sales=('sales','mean'),
    unique_customers=('customer_id','nunique'),
    cancelled_orders=('status',lambda x: (x == 'Cancelled').sum())
)
report

,order_count,total_sales,avg_sales,unique_customers,cancelled_orders
order_month,,,,,
1,2,4300,2150.0,2,1
2,2,7400,3700.0,2,0
3,2,5300,2650.0,2,1
4,2,6600,3300.0,2,0
5,2,6000,3000.0,2,1
6,2,6900,3450.0,2,0