# Duplicate Data, Data Types and Inconsistent Values

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "customer_id": [101, 102, 103, 102, 104, 105, 106, 106],
    "name": ["Asha", "rahul", "NEHA", "rahul",
             "Priya ", "Aman", "Riya", "Riya"],
    "age": ["25", " thirty", "35", " thirty",
            "29", "42", "28", "28"],
    "city": ["Delhi", "mumbai", "DELHI", "mumbai",
             " Pune ", "Delhi", None, None],
    "income": [30000, 50000, 45000, 50000,
               -1000, 70000, np.nan, np.nan]
})
df

   customer_id    name      age    city   income
0          101    Asha       25   Delhi  30000.0
1          102   rahul   thirty  mumbai  50000.0
2          103    NEHA       35   DELHI  45000.0
3          102   rahul   thirty  mumbai  50000.0
4          104  Priya        29   Pune   -1000.0
5          105    Aman       42   Delhi  70000.0
6          106    Riya       28    None      NaN
7          106    Riya       28    None      NaN

#### Q1. Detect duplicate rows
Use duplicated() to identify complete duplicate rows. Display the Boolean result and count the duplicates.

In [4]:
df[df.duplicated()]

   customer_id   name      age    city   income
3          102  rahul   thirty  mumbai  50000.0
7          106   Riya       28    None      NaN

#### Q2. Remove duplicate rows
Use drop_duplicates() to remove complete duplicate rows. Store the result in a new DataFrame and verify the remaining duplicate count.

In [6]:
clean=df.drop_duplicates()
clean

   customer_id    name      age    city   income
0          101    Asha       25   Delhi  30000.0
1          102   rahul   thirty  mumbai  50000.0
2          103    NEHA       35   DELHI  45000.0
4          104  Priya        29   Pune   -1000.0
5          105    Aman       42   Delhi  70000.0
6          106    Riya       28    None      NaN

#### Q3. Detect duplicate customer IDs
Identify records with repeated customer_id values. Display all records involved, including the first occurrence, using duplicated(keep=False).

In [8]:
df[df['customer_id'].duplicated(keep=False)]

   customer_id   name      age    city   income
1          102  rahul   thirty  mumbai  50000.0
3          102  rahul   thirty  mumbai  50000.0
6          106   Riya       28    None      NaN
7          106   Riya       28    None      NaN

#### Q4. Remove duplicates using a subset
Remove duplicate records based on customer_id, keeping the first occurrence. Explain why this may be unsafe if two records with the same ID contain conflicting information.

In [19]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 102, 104, 105, 106, 106],
    "name": ["Asha", "rahul", "NEHA", "rahul",
             "Priya ", "Aman", "Riya", "Riya"],
    "age": ["25", " thirty", "35", " thirty",
            "29", "42", "28", "28"],
    "city": ["Delhi", "mumbai", "DELHI", "mumbai",
             " Pune ", "Delhi", None, None],
    "income": [30000, 50000, 45000, 50000,
               -1000, 70000, np.nan, np.nan]
})

df=df.drop_duplicates(subset='customer_id',keep='first')
df

   customer_id    name      age    city   income
0          101    Asha       25   Delhi  30000.0
1          102   rahul   thirty  mumbai  50000.0
2          103    NEHA       35   DELHI  45000.0
4          104  Priya        29   Pune   -1000.0
5          105    Aman       42   Delhi  70000.0
6          106    Riya       28    None      NaN

#### Q5. Standardize text values
Clean the name and city columns by removing leading/trailing whitespace and standardizing letter case. Use string methods such as .str.strip(), .str.lower(), and .str.title().

In [34]:
df['name']=df['name'].str.strip().str.lower()
df['city']=df['city'].str.strip().str.lower()
df[['name','city']]

    name    city
0   asha   delhi
1  rahul  mumbai
2   neha   delhi
4  priya    pune
5   aman   delhi
6   riya    None

#### Q6. Convert data types
Clean the age column by removing unnecessary whitespace and converting it to a numeric type. Invalid values such as "thirty" should become missing values rather than crashing the operation. Use pd.to_numeric() with errors="coerce".

In [41]:
df['age']=pd.to_numeric(df['age'],errors="coerce")
df['age']

0    25.0
1     NaN
2    35.0
4    29.0
5    42.0
6    28.0
Name: age, dtype: float64

#### Q7. Identify invalid numerical values
Find records with negative income. Create a Boolean mask and display the invalid records.
Explain why a negative value should be investigated before automatically replacing it with zero.

In [48]:
mask=df['income']>0
df.loc[~mask]

   customer_id   name   age  city  income
4          104  priya  29.0  pune -1000.0
6          106   riya  28.0  None     NaN

#### Q8. Replace invalid values
In a copy of the dataset, replace negative income values with NaN. Then report how many missing income values exist.
Use np.nan and verify the result with isna().

In [53]:
df1=df.copy()
mask=df1['income']<0
df1.loc[mask,'income']=np.nan
df1['income']

0    30000.0
1    50000.0
2    45000.0
4        NaN
5    70000.0
6        NaN
Name: income, dtype: float64

In [57]:
df1['income'].isna().sum()

2

#### Q9. Build a cleaning pipeline
Create a cleaned copy of df that:
1. Standardizes name and city.
2. Converts age to numeric, coercing invalid values to missing.
3. Replaces negative income values with missing values.
4. Removes exact duplicate rows.
5. Preserves the original DataFrame unchanged.
Check the final data types and missing-value counts.

In [60]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 102, 104, 105, 106, 106],
    "name": ["Asha", "rahul", "NEHA", "rahul",
             "Priya ", "Aman", "Riya", "Riya"],
    "age": ["25", " thirty", "35", " thirty",
            "29", "42", "28", "28"],
    "city": ["Delhi", "mumbai", "DELHI", "mumbai",
             " Pune ", "Delhi", None, None],
    "income": [30000, 50000, 45000, 50000,
               -1000, 70000, np.nan, np.nan]
})
df

   customer_id    name      age    city   income
0          101    Asha       25   Delhi  30000.0
1          102   rahul   thirty  mumbai  50000.0
2          103    NEHA       35   DELHI  45000.0
3          102   rahul   thirty  mumbai  50000.0
4          104  Priya        29   Pune   -1000.0
5          105    Aman       42   Delhi  70000.0
6          106    Riya       28    None      NaN
7          106    Riya       28    None      NaN

In [62]:
#Standardizes name and city.
df['name']=df['name'].str.strip().str.lower()
df['city']=df['city'].str.strip().str.lower()
df

   customer_id   name      age    city   income
0          101   asha       25   delhi  30000.0
1          102  rahul   thirty  mumbai  50000.0
2          103   neha       35   delhi  45000.0
3          102  rahul   thirty  mumbai  50000.0
4          104  priya       29    pune  -1000.0
5          105   aman       42   delhi  70000.0
6          106   riya       28    None      NaN
7          106   riya       28    None      NaN

In [68]:
#Converts age to numeric, coercing invalid values to missing
df['age']=pd.to_numeric(df['age'],errors='coerce')
df

   customer_id   name   age    city   income
0          101   asha  25.0   delhi  30000.0
1          102  rahul   NaN  mumbai  50000.0
2          103   neha  35.0   delhi  45000.0
3          102  rahul   NaN  mumbai  50000.0
4          104  priya  29.0    pune  -1000.0
5          105   aman  42.0   delhi  70000.0
6          106   riya  28.0    None      NaN
7          106   riya  28.0    None      NaN

In [72]:
#Replaces negative income values with missing values.
mask=df['income']<0
df.loc[mask,'income']=np.nan
df['income']

0    30000.0
1    50000.0
2    45000.0
3    50000.0
4        NaN
5    70000.0
6        NaN
7        NaN
Name: income, dtype: float64

In [74]:
df=df.drop_duplicates(keep='first')
df

   customer_id   name   age    city   income
0          101   asha  25.0   delhi  30000.0
1          102  rahul   NaN  mumbai  50000.0
2          103   neha  35.0   delhi  45000.0
4          104  priya  29.0    pune      NaN
5          105   aman  42.0   delhi  70000.0
6          106   riya  28.0    None      NaN

In [76]:
#Check the final data types and missing-value counts.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  6 non-null      int64
 1   name         6 non-null      object
 2   age          5 non-null      float64
 3   city         5 non-null      object
 4   income       4 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 288.0+ bytes