# Imputation and cleaning strategies

#### Q1. Fill missing values with a constant
Fill missing values in the city column with "Unknown". Store the result in a new DataFrame without modifying df.

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "age": [25, np.nan, 35, 42, np.nan, 29, 38, 45],
    "income": [30000, 50000, np.nan, 70000, 45000, np.nan, 60000, 80000],
    "city": ["Delhi", "Mumbai", None, "Pune", "Delhi", None, "Mumbai", "Pune"],
    "purchased": [1, 0, 1, np.nan, 0, 1, np.nan, 1]
})
df

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
1          102   NaN  50000.0  Mumbai        0.0
2          103  35.0      NaN    None        1.0
3          104  42.0  70000.0    Pune        NaN
4          105   NaN  45000.0   Delhi        0.0
5          106  29.0      NaN    None        1.0
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0

In [4]:
df['city']=df['city'].fillna('unknown')
df

   customer_id   age   income     city  purchased
0          101  25.0  30000.0    Delhi        1.0
1          102   NaN  50000.0   Mumbai        0.0
2          103  35.0      NaN  unknown        1.0
3          104  42.0  70000.0     Pune        NaN
4          105   NaN  45000.0    Delhi        0.0
5          106  29.0      NaN  unknown        1.0
6          107  38.0  60000.0   Mumbai        NaN
7          108  45.0  80000.0     Pune        1.0

#### Q2. Mean imputation
Fill missing values in age with the mean age. Calculate the mean first and then use fillna().
Explain why mean imputation can be sensitive to outliers.

In [6]:
df['age']=df['age'].fillna(round(df['age'].mean(),2))
df

   customer_id    age   income     city  purchased
0          101  25.00  30000.0    Delhi        1.0
1          102  35.67  50000.0   Mumbai        0.0
2          103  35.00      NaN  unknown        1.0
3          104  42.00  70000.0     Pune        NaN
4          105  35.67  45000.0    Delhi        0.0
5          106  29.00      NaN  unknown        1.0
6          107  38.00  60000.0   Mumbai        NaN
7          108  45.00  80000.0     Pune        1.0

#### Q3. Median imputation
Fill missing values in income with the median income. Explain why median imputation may be more appropriate than mean imputation for skewed income data.

In [8]:
df['income']=df['income'].fillna(df['income'].median())
df

   customer_id    age   income     city  purchased
0          101  25.00  30000.0    Delhi        1.0
1          102  35.67  50000.0   Mumbai        0.0
2          103  35.00  55000.0  unknown        1.0
3          104  42.00  70000.0     Pune        NaN
4          105  35.67  45000.0    Delhi        0.0
5          106  29.00  55000.0  unknown        1.0
6          107  38.00  60000.0   Mumbai        NaN
7          108  45.00  80000.0     Pune        1.0

#### Q4. Mode imputation
Fill missing values in city using the most frequent city in the dataset. Use mode() and fillna().

In [10]:
df['city']=df['city'].replace('unknown',df['city'].mode()[0])
df

   customer_id    age   income    city  purchased
0          101  25.00  30000.0   Delhi        1.0
1          102  35.67  50000.0  Mumbai        0.0
2          103  35.00  55000.0   Delhi        1.0
3          104  42.00  70000.0    Pune        NaN
4          105  35.67  45000.0   Delhi        0.0
5          106  29.00  55000.0   Delhi        1.0
6          107  38.00  60000.0  Mumbai        NaN
7          108  45.00  80000.0    Pune        1.0

#### Q5. Fill different columns with different statistics
Create a new DataFrame where:
- Missing age values are filled with the median age.
- Missing income values are filled with the median income.
- Missing city values are filled with "Unknown".
Keep the original DataFrame unchanged.

In [12]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "age": [25, np.nan, 35, 42, np.nan, 29, 38, 45],
    "income": [30000, 50000, np.nan, 70000, 45000, np.nan, 60000, 80000],
    "city": ["Delhi", "Mumbai", None, "Pune", "Delhi", None, "Mumbai", "Pune"],
    "purchased": [1, 0, 1, np.nan, 0, 1, np.nan, 1]
})

In [13]:
df1=df.copy()
df1['age']=df1['age'].fillna(df1['age'].median())
df1['income']=df1['income'].fillna(df1['income'].median())
df1['city']=df1['city'].fillna('unknown')
df1

   customer_id   age   income     city  purchased
0          101  25.0  30000.0    Delhi        1.0
1          102  36.5  50000.0   Mumbai        0.0
2          103  35.0  55000.0  unknown        1.0
3          104  42.0  70000.0     Pune        NaN
4          105  36.5  45000.0    Delhi        0.0
5          106  29.0  55000.0  unknown        1.0
6          107  38.0  60000.0   Mumbai        NaN
7          108  45.0  80000.0     Pune        1.0

#### Q6. Forward fill and backward fill
Use this time-ordered dataset:
sales = pd.DataFrame({    "day": [1, 2, 3, 4, 5],    "revenue": [1000, np.nan, np.nan, 1600, np.nan]})



Create two separate results using forward fill (ffill) and backward fill (bfill). Explain where each method gets its replacement value and why row order matters.

In [15]:
sales = pd.DataFrame({
    "day": [1, 2, 3, 4, 5],
    "revenue": [1000, np.nan, np.nan, 1600, np.nan]
})
sales

   day  revenue
0    1   1000.0
1    2      NaN
2    3      NaN
3    4   1600.0
4    5      NaN

In [16]:
sales_ffill=sales.ffill()
sales_ffill

   day  revenue
0    1   1000.0
1    2   1000.0
2    3   1000.0
3    4   1600.0
4    5   1600.0

In [17]:
sales_bfill=sales.bfill()
sales_bfill

   day  revenue
0    1   1000.0
1    2   1600.0
2    3   1600.0
3    4   1600.0
4    5      NaN

#### Q7. Conditional imputation
Fill missing income values using the median income of customers in the same city. For this question, first fill missing city labels with "Unknown".
Hint: Explore groupby() with transform() so that the result aligns with the original rows.

In [19]:
df

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
1          102   NaN  50000.0  Mumbai        0.0
2          103  35.0      NaN    None        1.0
3          104  42.0  70000.0    Pune        NaN
4          105   NaN  45000.0   Delhi        0.0
5          106  29.0      NaN    None        1.0
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0

In [20]:
df['city']=df['city'].fillna('unknown')
df

   customer_id   age   income     city  purchased
0          101  25.0  30000.0    Delhi        1.0
1          102   NaN  50000.0   Mumbai        0.0
2          103  35.0      NaN  unknown        1.0
3          104  42.0  70000.0     Pune        NaN
4          105   NaN  45000.0    Delhi        0.0
5          106  29.0      NaN  unknown        1.0
6          107  38.0  60000.0   Mumbai        NaN
7          108  45.0  80000.0     Pune        1.0

In [21]:
df['income']=df['income'].fillna(df.groupby('city')['income'].transform('median'))
df

   customer_id   age   income     city  purchased
0          101  25.0  30000.0    Delhi        1.0
1          102   NaN  50000.0   Mumbai        0.0
2          103  35.0      NaN  unknown        1.0
3          104  42.0  70000.0     Pune        NaN
4          105   NaN  45000.0    Delhi        0.0
5          106  29.0      NaN  unknown        1.0
6          107  38.0  60000.0   Mumbai        NaN
7          108  45.0  80000.0     Pune        1.0

#### Q8. Compare imputation strategies
For the age column, compare the results of mean, median, and constant imputation (use 0 for the constant).
Display the three imputed columns side by side and explain why a constant of 0 might be misleading for age.

In [23]:
impute=pd.DataFrame(
    {'mean_impute':df['age'].fillna(round(df['age'].mean(),2)),
     'median_impute':df['age'].fillna(df['age'].median()),
     'constant_impute':df['age'].fillna(0)
        
    }
)
impute

   mean_impute  median_impute  constant_impute
0        25.00           25.0             25.0
1        35.67           36.5              0.0
2        35.00           35.0             35.0
3        42.00           42.0             42.0
4        35.67           36.5              0.0
5        29.00           29.0             29.0
6        38.00           38.0             38.0
7        45.00           45.0             45.0

#### Q9. Verify the cleaning result
Starting with a copy of df, impute age with its median, income with its median, city with "Unknown", and purchased with its mode.
Then:
1. Count missing values by column.
2. Verify whether any missing values remain.
3. Confirm that the original df is unchanged.

In [25]:
df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "age": [25, np.nan, 35, 42, np.nan, 29, 38, 45],
    "income": [30000, 50000, np.nan, 70000, 45000, np.nan, 60000, 80000],
    "city": ["Delhi", "Mumbai", None, "Pune", "Delhi", None, "Mumbai", "Pune"],
    "purchased": [1, 0, 1, np.nan, 0, 1, np.nan, 1]
})
df

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
1          102   NaN  50000.0  Mumbai        0.0
2          103  35.0      NaN    None        1.0
3          104  42.0  70000.0    Pune        NaN
4          105   NaN  45000.0   Delhi        0.0
5          106  29.0      NaN    None        1.0
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0

In [29]:
impute=df.copy()
impute['age']=impute['age'].fillna(impute['age'].median())
impute['income']=impute['income'].fillna(impute['income'].median())
impute['city']=impute['city'].fillna('unknown')
impute

   customer_id   age   income     city  purchased
0          101  25.0  30000.0    Delhi        1.0
1          102  36.5  50000.0   Mumbai        0.0
2          103  35.0  55000.0  unknown        1.0
3          104  42.0  70000.0     Pune        NaN
4          105  36.5  45000.0    Delhi        0.0
5          106  29.0  55000.0  unknown        1.0
6          107  38.0  60000.0   Mumbai        NaN
7          108  45.0  80000.0     Pune        1.0

In [31]:
#Count missing values by column.
impute.isna().sum()

customer_id    0
age            0
income         0
city           0
purchased      2
dtype: int64

In [33]:
df

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
1          102   NaN  50000.0  Mumbai        0.0
2          103  35.0      NaN    None        1.0
3          104  42.0  70000.0    Pune        NaN
4          105   NaN  45000.0   Delhi        0.0
5          106  29.0      NaN    None        1.0
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0

#### Q10. Mini-project — Reusable imputation function
Write a function called impute_customer_data(data) that:
1. Creates a copy of the input DataFrame.
2. Fills missing numeric values using the median of each numeric column.
3. Fills missing categorical values using the mode of each categorical column.
4. Handles a categorical column containing only missing values without crashing.
5. Returns the cleaned DataFrame.
6. Tests the function on df and verifies that the original dataset remains unchanged.

In [38]:
def impute_customer_data(data):
    df=data.copy()
    df['age']=df['age'].fillna(df['age'].median())
    df['income']=df['income'].fillna(df['income'].median())
    df['city']=df['city'].fillna(df['city'].mode()[0])

    return df

cleaned=impute_customer_data(df)
cleaned

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
1          102  36.5  50000.0  Mumbai        0.0
2          103  35.0  55000.0   Delhi        1.0
3          104  42.0  70000.0    Pune        NaN
4          105  36.5  45000.0   Delhi        0.0
5          106  29.0  55000.0   Delhi        1.0
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0

In [41]:
df

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
1          102   NaN  50000.0  Mumbai        0.0
2          103  35.0      NaN    None        1.0
3          104  42.0  70000.0    Pune        NaN
4          105   NaN  45000.0   Delhi        0.0
5          106  29.0      NaN    None        1.0
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0