# Missing-value detection and assessment

In [4]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "age": [25, np.nan, 35, 42, np.nan, 29, 38, 45],
    "income": [30000, 50000, np.nan, 70000, 45000, np.nan, 60000, 80000],
    "city": ["Delhi", "Mumbai", None, "Pune", "Delhi", None, "Mumbai", "Pune"],
    "purchased": [1, 0, 1, None, 0, 1, None, 1]
})
df

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
1          102   NaN  50000.0  Mumbai        0.0
2          103  35.0      NaN    None        1.0
3          104  42.0  70000.0    Pune        NaN
4          105   NaN  45000.0   Delhi        0.0
5          106  29.0      NaN    None        1.0
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0

#### Q1. Detect missing values
Use isna() to identify missing values in every column. Display the resulting Boolean DataFrame.

In [7]:
df.isna().sum()

customer_id    0
age            2
income         2
city           2
purchased      2
dtype: int64

In [9]:
df.isna()

   customer_id    age  income   city  purchased
0        False  False   False  False      False
1        False   True   False  False      False
2        False  False    True   True      False
3        False  False   False  False       True
4        False   True   False  False      False
5        False  False    True   True      False
6        False  False   False  False       True
7        False  False   False  False      False

#### Q2. Count missing values
Calculate the number of missing values in each column, ordered from most missing to least missing.

In [12]:
df.isna().sum().sort_values(ascending=False)

age            2
income         2
city           2
purchased      2
customer_id    0
dtype: int64

#### Q3. Calculate missing-value percentages
Calculate the percentage of missing values in each column. Round the results to two decimal places.

In [19]:
(df.isna().mean()*100).round(2)

customer_id     0.0
age            25.0
income         25.0
city           25.0
purchased      25.0
dtype: float64

#### Q4. Identify incomplete rows
Display all rows containing at least one missing value using isna() and any().

In [24]:
df[df.isna().any(axis=1)]

   customer_id   age   income    city  purchased
1          102   NaN  50000.0  Mumbai        0.0
2          103  35.0      NaN    None        1.0
3          104  42.0  70000.0    Pune        NaN
4          105   NaN  45000.0   Delhi        0.0
5          106  29.0      NaN    None        1.0
6          107  38.0  60000.0  Mumbai        NaN

#### Q5. Identify complete rows
Return only rows with no missing values in any column. Explain how this differs from removing rows that have missing values in just one selected column.

In [27]:
df[~df.isna().any(axis=1)]

   customer_id   age   income   city  purchased
0          101  25.0  30000.0  Delhi        1.0
7          108  45.0  80000.0   Pune        1.0

#### Q6. Drop rows with missing values
Use dropna() to remove rows containing any missing value. Store the result in a new DataFrame and report the number of remaining rows.

In [30]:
df_clean=df.dropna()
df_clean

   customer_id   age   income   city  purchased
0          101  25.0  30000.0  Delhi        1.0
7          108  45.0  80000.0   Pune        1.0

In [32]:
df_clean.shape[0]

2

#### Q7. Drop columns with missing values
Use dropna(axis=1) to retain only columns with no missing values. Explain why this can be risky on real-world datasets.

In [35]:
df_clean2 =df.dropna(axis=1)
df_clean2

   customer_id
0          101
1          102
2          103
3          104
4          105
5          106
6          107
7          108

#### Q8. Drop based on selected columns
Remove rows where age or income is missing, but allow missing values in city and purchased. Use subset.

In [38]:
df_clean3=df.dropna(axis=0,subset=['age','income'])
df_clean3

   customer_id   age   income    city  purchased
0          101  25.0  30000.0   Delhi        1.0
3          104  42.0  70000.0    Pune        NaN
6          107  38.0  60000.0  Mumbai        NaN
7          108  45.0  80000.0    Pune        1.0

#### Q9. Assess missingness by column
Create a summary DataFrame with three columns: missing_count, missing_percentage, and data_type. Each row should correspond to a column in the original dataset.

In [54]:
summary=pd.DataFrame(
    {'missing_count':df.isna().sum(),
    'missing_percentage':df.isna().mean()*100,
    'data_type':df.dtypes}
)
summary

             missing_count  missing_percentage data_type
customer_id              0                 0.0     int64
age                      2                25.0   float64
income                   2                25.0   float64
city                     2                25.0    object
purchased                2                25.0   float64

#### Q10. Mini-project — Missing-data audit
Create a reusable function missing_data_report(data) that:
1. Reports each column's missing count and percentage.
2. Includes each column's data type.
3. Sorts columns by missing percentage descending.
4. Returns the summary as a DataFrame without modifying the original dataset.
5. Test it on the dataset above.
6. Explain why a data analyst should audit missingness before choosing an imputation strategy.

In [73]:

def missing_data_report(df):
    data=pd.DataFrame(
        {'missing_count':df.isna().sum(),
        'missing%':(df.isna().mean())*100,})
    data=data.sort_values(by='missing%',ascending =False)


    return data
data_summary=missing_data_report(df)
data_summary

             missing_count  missing%
age                      2      25.0
income                   2      25.0
city                     2      25.0
purchased                2      25.0
customer_id              0       0.0