# Advanced Feature Engineering and Data Transformation

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': range(301, 313),
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Pune',
             'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'category': ['Electronics', 'Clothing', 'Electronics', 'Food',
                 'Clothing', 'Food', 'Food', 'Electronics',
                 'Clothing', 'Electronics', 'Food', 'Clothing'],
    'income': [30000, 45000, 55000, 22000, 38000, 28000,
               60000, 52000, 41000, 35000, 48000, 25000],
    'spending': [12000, 18000, 25000, 9000, 15000, 11000,
                 30000, 22000, 17000, 14000, 21000, 10000],
    'orders': [2, 4, 6, 1, 3, 2, 7, 5, 4, 3, 6, 1],
    'tenure_months': [6, 12, 24, 3, 9, 6, 30, 18, 12, 9, 24, 3]
})
df

    customer_id    city     category  income  spending  orders  tenure_months
0           301   Delhi  Electronics   30000     12000       2              6
1           302  Mumbai     Clothing   45000     18000       4             12
2           303   Delhi  Electronics   55000     25000       6             24
3           304    Pune         Food   22000      9000       1              3
4           305  Mumbai     Clothing   38000     15000       3              9
5           306    Pune         Food   28000     11000       2              6
6           307   Delhi         Food   60000     30000       7             30
7           308  Mumbai  Electronics   52000     22000       5             18
8           309    Pune     Clothing   41000     17000       4             12
9           310   Delhi  Electronics   35000     14000       3              9
10          311  Mumbai         Food   48000     21000       6             24
11          312    Pune     Clothing   25000     10000       1              3

#### Q1. Customer spending rank

Create a spending_rank column that ranks customers by spending from highest to lowest. The highest spender should receive rank 1.

In [4]:
df['spending_rank']=df['spending'].rank(ascending=False)
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank
0,301,Delhi,Electronics,30000,12000,2,6,9.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0
3,304,Pune,Food,22000,9000,1,3,12.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0
5,306,Pune,Food,28000,11000,2,6,10.0
6,307,Delhi,Food,60000,30000,7,30,1.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0
8,309,Pune,Clothing,41000,17000,4,12,6.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0
10,311,Mumbai,Food,48000,21000,6,24,4.0
11,312,Pune,Clothing,25000,10000,1,3,11.0

#### Q2. City-level spending rank

Rank customers by spending within each city. Create a city_spending_rank column using groupby() and rank().

In [6]:
df['city_spending_rank']=df.groupby('city')['spending'].rank(ascending=False)
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0
3,304,Pune,Food,22000,9000,1,3,12.0,4.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0
5,306,Pune,Food,28000,11000,2,6,10.0,2.0
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0

#### Q3. Category-level average

Create a category_avg_spending column containing the average spending for each customer's product category. Every customer should receive the average for their category.

In [8]:
df['category_avg_spending']=df.groupby('category')['spending'].transform('mean')
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0

#### Q4. Deviation from city average

Create a city_spending_deviation column by subtracting each customer's city-average spending from their own spending.

In [10]:
df['city_spending_deviation'] = (
    df['spending']
    - df.groupby('city')['spending'].transform('mean')
)
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,-8250.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,-1000.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,4750.0
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,-2750.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,-4000.0
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,-750.0
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,9750.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,3000.0
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,5250.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,-6250.0
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,2000.0
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,-1750.0

#### Q5. Group-based normalization

Create a city_income_minmax column that normalizes income separately within each city to a range of 0–1. Handle groups where all income values are identical.

In [12]:
city_min=df.groupby('city')['income'].transform('min')
city_max=df.groupby('city')['income'].transform('max')
city_range=city_max-city_min
df['city_minmax']=(df['income']-city_min)/city_range.where(city_range!=0).fillna(0.0)
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_minmax
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,-8250.0,0.000000
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,-1000.0,0.500000
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,4750.0,0.833333
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,-2750.0,0.000000
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,-4000.0,0.000000
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,-750.0,0.315789
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,9750.0,1.000000
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,3000.0,1.000000
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,5250.0,1.000000
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,-6250.0,0.166667
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,2000.0,0.714286
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,-1750.0,0.157895

#### Q6. Percentile-based segmentation

Use pd.qcut() to divide customers into four spending groups: Q1, Q2, Q3, and Q4. Handle potential duplicate bin edges appropriately.

In [14]:
df['spending_quartile'] = pd.qcut(
    df['spending'].rank(method='first'),
    q=4,
    labels=['Q1', 'Q2', 'Q3', 'Q4']
)
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_minmax,spending_quartile
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,-8250.0,0.000000,Q2
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,-1000.0,0.500000,Q3
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,4750.0,0.833333,Q4
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,-2750.0,0.000000,Q1
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,-4000.0,0.000000,Q2
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,-750.0,0.315789,Q1
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,9750.0,1.000000,Q4
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,3000.0,1.000000,Q4
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,5250.0,1.000000,Q3
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,-6250.0,0.166667,Q2
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,2000.0,0.714286,Q3
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,-1750.0,0.157895,Q1

#### Q7. Cumulative spending

Sort customers by spending from highest to lowest and create a cumulative_spending column showing the running total of spending. Preserve the original customer identifiers.

In [16]:
df_sorted = df.sort_values(
    by='spending',
    ascending=False
).copy()

df_sorted['cumulative_spending'] = (
    df_sorted['spending'].cumsum()
)
df_sorted

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_minmax,spending_quartile,cumulative_spending
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,9750.0,1.000000,Q4,30000
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,4750.0,0.833333,Q4,55000
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,3000.0,1.000000,Q4,77000
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,2000.0,0.714286,Q3,98000
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,-1000.0,0.500000,Q3,116000
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,5250.0,1.000000,Q3,133000
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,-4000.0,0.000000,Q2,148000
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,-6250.0,0.166667,Q2,162000
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,-8250.0,0.000000,Q2,174000
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,-750.0,0.315789,Q1,185000
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,-1750.0,0.157895,Q1,195000
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,-2750.0,0.000000,Q1,204000

#### Q8. City-level spending share

Create a city_spending_share column showing each customer's spending as a percentage of their city's total spending.

In [18]:
city_total = df.groupby('city')['spending'].transform('sum')

df['city_spending_share'] = (
    df['spending'] / city_total
) * 100
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_minmax,spending_quartile,city_spending_share
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,-8250.0,0.000000,Q2,14.814815
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,-1000.0,0.500000,Q3,23.684211
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,4750.0,0.833333,Q4,30.864198
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,-2750.0,0.000000,Q1,19.148936
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,-4000.0,0.000000,Q2,19.736842
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,-750.0,0.315789,Q1,23.404255
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,9750.0,1.000000,Q4,37.037037
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,3000.0,1.000000,Q4,28.947368
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,5250.0,1.000000,Q3,36.170213
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,-6250.0,0.166667,Q2,17.283951
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,2000.0,0.714286,Q3,27.631579
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,-1750.0,0.157895,Q1,21.276596

#### Q9. Relative customer value

Create a relative_customer_value column by dividing each customer's spending by the average spending in their city. Explain how to interpret values above and below 1.

In [20]:
city_avg = df.groupby('city')['spending'].transform('mean')
df['relative_customer_value']=df['spending']/city_avg
df

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_minmax,spending_quartile,city_spending_share,relative_customer_value
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,-8250.0,0.000000,Q2,14.814815,0.592593
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,-1000.0,0.500000,Q3,23.684211,0.947368
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,4750.0,0.833333,Q4,30.864198,1.234568
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,-2750.0,0.000000,Q1,19.148936,0.765957
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,-4000.0,0.000000,Q2,19.736842,0.789474
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,-750.0,0.315789,Q1,23.404255,0.936170
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,9750.0,1.000000,Q4,37.037037,1.481481
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,3000.0,1.000000,Q4,28.947368,1.157895
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,5250.0,1.000000,Q3,36.170213,1.446809
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,-6250.0,0.166667,Q2,17.283951,0.691358
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,2000.0,0.714286,Q3,27.631579,1.105263
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,-1750.0,0.157895,Q1,21.276596,0.851064

Greater than 1: Customer spends more than the city average.



Equal to 1: Customer spends exactly the city average.



Less than 1: Customer spends less than the city average.

#### Q10. Mini-project: Group-Based Feature Engineering

Create a copy of the original DataFrame and add these features:
- spending_rank
- city_spending_rank
- category_avg_spending
- city_spending_deviation
- city_income_minmax
- city_spending_share
- relative_customer_value

In [23]:
df = pd.DataFrame({
    'customer_id': range(301, 313),
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Pune',
             'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'category': ['Electronics', 'Clothing', 'Electronics', 'Food',
                 'Clothing', 'Food', 'Food', 'Electronics',
                 'Clothing', 'Electronics', 'Food', 'Clothing'],
    'income': [30000, 45000, 55000, 22000, 38000, 28000,
               60000, 52000, 41000, 35000, 48000, 25000],
    'spending': [12000, 18000, 25000, 9000, 15000, 11000,
                 30000, 22000, 17000, 14000, 21000, 10000],
    'orders': [2, 4, 6, 1, 3, 2, 7, 5, 4, 3, 6, 1],
    'tenure_months': [6, 12, 24, 3, 9, 6, 30, 18, 12, 9, 24, 3]
})
df

    customer_id    city     category  income  spending  orders  tenure_months
0           301   Delhi  Electronics   30000     12000       2              6
1           302  Mumbai     Clothing   45000     18000       4             12
2           303   Delhi  Electronics   55000     25000       6             24
3           304    Pune         Food   22000      9000       1              3
4           305  Mumbai     Clothing   38000     15000       3              9
5           306    Pune         Food   28000     11000       2              6
6           307   Delhi         Food   60000     30000       7             30
7           308  Mumbai  Electronics   52000     22000       5             18
8           309    Pune     Clothing   41000     17000       4             12
9           310   Delhi  Electronics   35000     14000       3              9
10          311  Mumbai         Food   48000     21000       6             24
11          312    Pune     Clothing   25000     10000       1              3

In [24]:
#spending_rank
dff=df.copy()
dff['spending_rank']=dff['spending'].rank(ascending=False,method='min')
dff

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank
0,301,Delhi,Electronics,30000,12000,2,6,9.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0
3,304,Pune,Food,22000,9000,1,3,12.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0
5,306,Pune,Food,28000,11000,2,6,10.0
6,307,Delhi,Food,60000,30000,7,30,1.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0
8,309,Pune,Clothing,41000,17000,4,12,6.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0
10,311,Mumbai,Food,48000,21000,6,24,4.0
11,312,Pune,Clothing,25000,10000,1,3,11.0

In [25]:
#city_spending_rank
dff['city_spending_rank']=dff.groupby('city')['spending'].rank(ascending=False,method='min')
dff

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0
3,304,Pune,Food,22000,9000,1,3,12.0,4.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0
5,306,Pune,Food,28000,11000,2,6,10.0,2.0
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0

In [26]:
#category_avg_spending
dff['category_avg_spending']=dff.groupby('category')['spending'].transform('mean')
dff

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0

In [27]:
#city_spending_deviation
dff['city_spending_deviation']=(dff.groupby('city')['spending'].transform('mean')-dff['spending'])
dff

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,8250.0
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,1000.0
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,-4750.0
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,2750.0
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,4000.0
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,750.0
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,-9750.0
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,-3000.0
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,-5250.0
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,6250.0
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,-2000.0
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,1750.0

In [44]:
#city_income_minmax
city_min=dff.groupby('city')['income'].transform('min')
city_max=dff.groupby('city')['income'].transform('max')
city_range=city_max-city_min
dff['city_income_minmax']=((dff['income']-city_min)/city_range.where(city_range!=0).fillna(0.0))
dff

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_income_minmax
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,8250.0,0.000000
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,1000.0,0.500000
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,-4750.0,0.833333
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,2750.0,0.000000
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,4000.0,0.000000
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,750.0,0.315789
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,-9750.0,1.000000
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,-3000.0,1.000000
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,-5250.0,1.000000
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,6250.0,0.166667
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,-2000.0,0.714286
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,1750.0,0.157895

In [46]:
#city_spending_share
city_total = dff.groupby('city')['spending'].transform('sum')

dff['city_spending_share'] = (
    dff['spending'] / city_total
) * 100
dff

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_income_minmax,city_spending_share
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,8250.0,0.000000,14.814815
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,1000.0,0.500000,23.684211
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,-4750.0,0.833333,30.864198
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,2750.0,0.000000,19.148936
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,4000.0,0.000000,19.736842
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,750.0,0.315789,23.404255
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,-9750.0,1.000000,37.037037
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,-3000.0,1.000000,28.947368
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,-5250.0,1.000000,36.170213
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,6250.0,0.166667,17.283951
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,-2000.0,0.714286,27.631579
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,1750.0,0.157895,21.276596

In [48]:
#relative_customer_value
dff['relative_customer_value_city']=dff['spending']/dff.groupby('city')['spending'].transform('mean')
dff

,customer_id,city,category,income,spending,orders,tenure_months,spending_rank,city_spending_rank,category_avg_spending,city_spending_deviation,city_income_minmax,city_spending_share,relative_customer_value_city
0,301,Delhi,Electronics,30000,12000,2,6,9.0,4.0,18250.0,8250.0,0.000000,14.814815,0.592593
1,302,Mumbai,Clothing,45000,18000,4,12,5.0,3.0,15000.0,1000.0,0.500000,23.684211,0.947368
2,303,Delhi,Electronics,55000,25000,6,24,2.0,2.0,18250.0,-4750.0,0.833333,30.864198,1.234568
3,304,Pune,Food,22000,9000,1,3,12.0,4.0,17750.0,2750.0,0.000000,19.148936,0.765957
4,305,Mumbai,Clothing,38000,15000,3,9,7.0,4.0,15000.0,4000.0,0.000000,19.736842,0.789474
5,306,Pune,Food,28000,11000,2,6,10.0,2.0,17750.0,750.0,0.315789,23.404255,0.936170
6,307,Delhi,Food,60000,30000,7,30,1.0,1.0,17750.0,-9750.0,1.000000,37.037037,1.481481
7,308,Mumbai,Electronics,52000,22000,5,18,3.0,1.0,18250.0,-3000.0,1.000000,28.947368,1.157895
8,309,Pune,Clothing,41000,17000,4,12,6.0,1.0,15000.0,-5250.0,1.000000,36.170213,1.446809
9,310,Delhi,Electronics,35000,14000,3,9,8.0,3.0,18250.0,6250.0,0.166667,17.283951,0.691358
10,311,Mumbai,Food,48000,21000,6,24,4.0,2.0,17750.0,-2000.0,0.714286,27.631579,1.105263
11,312,Pune,Clothing,25000,10000,1,3,11.0,3.0,15000.0,1750.0,0.157895,21.276596,0.851064