# Advanced Feature Engineering and Transformation

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': range(201, 211),
    'age': [19, 25, 34, 42, 51, 63, 29, 38, 47, 55],
    'income': [18000, 25000, 32000, 45000, 55000,
               80000, 0, 38000, 62000, 48000],
    'spending': [5000, 12000, 18000, 22000, 30000,
                 45000, 0, 15000, 35000, 27000],
    'orders': [1, 2, 4, 3, 5, 8, 0, 2, 7, 4],
    'tenure_months': [2, 6, 12, 18, 24, 48, 0, 9, 36, 30],
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Mumbai',
             'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Pune']
})
df

   customer_id  age  income  spending  orders  tenure_months    city
0          201   19   18000      5000       1              2   Delhi
1          202   25   25000     12000       2              6  Mumbai
2          203   34   32000     18000       4             12   Delhi
3          204   42   45000     22000       3             18    Pune
4          205   51   55000     30000       5             24  Mumbai
5          206   63   80000     45000       8             48   Delhi
6          207   29       0         0       0              0    Pune
7          208   38   38000     15000       2              9  Mumbai
8          209   47   62000     35000       7             36   Delhi
9          210   55   48000     27000       4             30    Pune

#### Q1. Log transformation

Create a log_income column using np.log1p() to reduce the skewness of income. Explain why log1p() is safer than np.log() when income contains zero.

In [6]:
df['log_income']=np.log1p(df['income'])
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income
0,201,19,18000,5000,1,2,Delhi,9.798183
1,202,25,25000,12000,2,6,Mumbai,10.126671
2,203,34,32000,18000,4,12,Delhi,10.373522
3,204,42,45000,22000,3,18,Pune,10.714440
4,205,51,55000,30000,5,24,Mumbai,10.915107
5,206,63,80000,45000,8,48,Delhi,11.289794
6,207,29,0,0,0,0,Pune,0.000000
7,208,38,38000,15000,2,9,Mumbai,10.545368
8,209,47,62000,35000,7,36,Delhi,11.034906
9,210,55,48000,27000,4,30,Pune,10.778977

#### Q2. Log transformation of spending

Create a log_spending column using np.log1p(). Verify that all transformed values are finite.

In [13]:
df['log_spending']=np.log1p(df['spending'])
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440
6,207,29,0,0,0,0,Pune,0.000000,0.000000
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629

#### Q3. Age binning

Use pd.cut() to divide customers into these age groups: 18–25, 26–35, 36–45, 46–55, and 56+. Store the groups in a new column called age_band.

In [18]:
bins = [17, 25, 35, 45, 55, float('inf')]

labels = ['18–25', '26–35', '36–45', '46–55', '56+']

df['age_band'] = pd.cut(
    df['age'],
    bins=bins,
    labels=labels
)
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55

#### Q4. Income segmentation

Create an income_segment column with the following categories:
- Below 25,000: Low
- 25,000–49,999: Medium
- 50,000–74,999: High
- 75,000 and above: Very High

In [27]:
conditions=[
    df['income']<25000,
    df['income'].between(25000,49999),
    df['income'].between(50000,74999),
    df['income']>=75000
  
]
labels=['Low','Medium','High','Very High']
df['income_segment']=np.select(conditions,labels,default='n/a')
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium

#### Q5. Spending-to-income ratio

Create spending_ratio, expressed as a percentage of income. Handle zero income safely and explain why replacing the undefined ratio with zero could be misleading.

In [34]:
df['spending_ratio']=np.where(
    df['income']>0,
    (df['spending']/df['income'])*100,np.nan)
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment,spending_ratio
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low,27.777778
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium,48.000000
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium,56.250000
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium,48.888889
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High,54.545455
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High,56.250000
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low,NaN
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium,39.473684
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High,56.451613
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium,56.250000

#### Q6. Customer eligibility

Create an eligible_for_premium Boolean column. A customer qualifies if their income is at least 50,000, their tenure is at least 12 months, and they have placed at least three orders.

In [44]:
df['eligible_for_premium']=np.where(
    (df['income']>50000) & (df['tenure_months']>=12),
    'Yes','No')
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment,spending_ratio,eligible_for_premium
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low,27.777778,No
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium,48.000000,No
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium,56.250000,No
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium,48.888889,No
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High,54.545455,Yes
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High,56.250000,Yes
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low,NaN,No
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium,39.473684,No
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High,56.451613,Yes
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium,56.250000,No

#### Q7. Customer activity classification

Create activity_status using these rules:
- Inactive: zero orders
- New: one or two orders
- Active: three to five orders
- Highly Active: more than five orders

In [47]:
conditions=[
    df['orders']==0,
    df['orders'].isin([1,2]),
    df['orders'].between(3,5),
    df['orders']>5
   ]
labels=['Inactive','New','Active','Highly Active']

df['activity_status']=np.select(conditions,labels,default='N/A')
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment,spending_ratio,eligible_for_premium,activity_status
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low,27.777778,No,New
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium,48.000000,No,New
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium,56.250000,No,Active
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium,48.888889,No,Active
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High,54.545455,Yes,Active
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High,56.250000,Yes,Highly Active
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low,NaN,No,Inactive
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium,39.473684,No,New
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High,56.451613,Yes,Highly Active
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium,56.250000,No,Active

#### Q8. Spending per order

Create spending_per_order by dividing spending by orders. Safely handle customers with zero orders and explain the resulting missing values.

In [56]:
df['spending_per_order']=np.where(
    df['orders']>0,
    round(df['spending']/df['orders'],2),np.nan)
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment,spending_ratio,eligible_for_premium,activity_status,spending_per_order
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low,27.777778,No,New,5000.00
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium,48.000000,No,New,6000.00
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium,56.250000,No,Active,4500.00
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium,48.888889,No,Active,7333.33
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High,54.545455,Yes,Active,6000.00
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High,56.250000,Yes,Highly Active,5625.00
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low,NaN,No,Inactive,NaN
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium,39.473684,No,New,7500.00
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High,56.451613,Yes,Highly Active,5000.00
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium,56.250000,No,Active,6750.00

#### Q9. Combined feature engineering

Create three new features:
- income_per_tenure_month: income divided by tenure months, safely handling zero tenure.
- high_value_customer: True if income is at least 50,000 and spending is at least 30,000.
- customer_lifetime_activity: orders multiplied by tenure months.

In [59]:
df['income_per_tenure_month']=np.where(
    df['income']>0,
    round(df['income']/df['tenure_months'],2),np.nan
)
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment,spending_ratio,eligible_for_premium,activity_status,spending_per_order,income_per_tenure_month
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low,27.777778,No,New,5000.00,9000.00
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium,48.000000,No,New,6000.00,4166.67
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium,56.250000,No,Active,4500.00,2666.67
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium,48.888889,No,Active,7333.33,2500.00
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High,54.545455,Yes,Active,6000.00,2291.67
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High,56.250000,Yes,Highly Active,5625.00,1666.67
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low,NaN,No,Inactive,NaN,NaN
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium,39.473684,No,New,7500.00,4222.22
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High,56.451613,Yes,Highly Active,5000.00,1722.22
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium,56.250000,No,Active,6750.00,1600.00

high_value_customer: True if income is at least 50,000 and spending is at least 30,000.

In [66]:
df['high_value_customer']=(df['income']>50000) & (df['spending']>=30000)
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment,spending_ratio,eligible_for_premium,activity_status,spending_per_order,income_per_tenure_month,high_value_customer
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low,27.777778,No,New,5000.00,9000.00,False
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium,48.000000,No,New,6000.00,4166.67,False
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium,56.250000,No,Active,4500.00,2666.67,False
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium,48.888889,No,Active,7333.33,2500.00,False
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High,54.545455,Yes,Active,6000.00,2291.67,True
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High,56.250000,Yes,Highly Active,5625.00,1666.67,True
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low,NaN,No,Inactive,NaN,NaN,False
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium,39.473684,No,New,7500.00,4222.22,False
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High,56.451613,Yes,Highly Active,5000.00,1722.22,True
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium,56.250000,No,Active,6750.00,1600.00,False

customer_lifetime_activity: orders multiplied by tenure months

In [69]:
df['customer_lifetime_activity']=df['orders']*df['tenure_months']
df

,customer_id,age,income,spending,orders,tenure_months,city,log_income,log_spending,age_band,income_segment,spending_ratio,eligible_for_premium,activity_status,spending_per_order,income_per_tenure_month,high_value_customer,customer_lifetime_activity
0,201,19,18000,5000,1,2,Delhi,9.798183,8.517393,18–25,Low,27.777778,No,New,5000.00,9000.00,False,2
1,202,25,25000,12000,2,6,Mumbai,10.126671,9.392745,18–25,Medium,48.000000,No,New,6000.00,4166.67,False,12
2,203,34,32000,18000,4,12,Delhi,10.373522,9.798183,26–35,Medium,56.250000,No,Active,4500.00,2666.67,False,48
3,204,42,45000,22000,3,18,Pune,10.714440,9.998843,36–45,Medium,48.888889,No,Active,7333.33,2500.00,False,54
4,205,51,55000,30000,5,24,Mumbai,10.915107,10.308986,46–55,High,54.545455,Yes,Active,6000.00,2291.67,True,120
5,206,63,80000,45000,8,48,Delhi,11.289794,10.714440,56+,Very High,56.250000,Yes,Highly Active,5625.00,1666.67,True,384
6,207,29,0,0,0,0,Pune,0.000000,0.000000,26–35,Low,NaN,No,Inactive,NaN,NaN,False,0
7,208,38,38000,15000,2,9,Mumbai,10.545368,9.615872,36–45,Medium,39.473684,No,New,7500.00,4222.22,False,18
8,209,47,62000,35000,7,36,Delhi,11.034906,10.463132,46–55,High,56.451613,Yes,Highly Active,5000.00,1722.22,True,252
9,210,55,48000,27000,4,30,Pune,10.778977,10.203629,46–55,Medium,56.250000,No,Active,6750.00,1600.00,False,120