# Time-Based Features, Aggregation, and Automated Pipelines

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': range(401, 413),
    'city': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune',
             'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'signup_date': pd.to_datetime([
        '2025-01-10', '2025-02-15', '2025-03-20',
        '2025-04-05', '2025-05-12', '2025-06-18',
        '2025-07-22', '2025-08-09', '2025-09-14',
        '2025-10-01', '2025-11-11', '2025-12-20'
    ]),
    'last_order_date': pd.to_datetime([
        '2026-01-10', '2026-02-20', '2026-03-15',
        '2026-01-25', '2026-04-12', '2026-05-18',
        '2026-02-22', '2026-06-09', '2026-03-14',
        '2026-07-01', '2026-05-11', '2026-08-20'
    ]),
    'income': [30000, 45000, 22000, 55000, 38000, 28000,
               60000, 52000, 41000, 35000, 48000, 25000],
    'spending': [12000, 18000, 9000, 25000, 15000, 11000,
                 30000, 22000, 17000, 14000, 21000, 10000],
    'orders': [2, 4, 1, 6, 3, 2, 7, 5, 4, 3, 6, 1]
})
df

    customer_id    city signup_date last_order_date  income  spending  orders
0           401   Delhi  2025-01-10      2026-01-10   30000     12000       2
1           402  Mumbai  2025-02-15      2026-02-20   45000     18000       4
2           403    Pune  2025-03-20      2026-03-15   22000      9000       1
3           404   Delhi  2025-04-05      2026-01-25   55000     25000       6
4           405  Mumbai  2025-05-12      2026-04-12   38000     15000       3
5           406    Pune  2025-06-18      2026-05-18   28000     11000       2
6           407   Delhi  2025-07-22      2026-02-22   60000     30000       7
7           408  Mumbai  2025-08-09      2026-06-09   52000     22000       5
8           409    Pune  2025-09-14      2026-03-14   41000     17000       4
9           410   Delhi  2025-10-01      2026-07-01   35000     14000       3
10          411  Mumbai  2025-11-11      2026-05-11   48000     21000       6
11          412    Pune  2025-12-20      2026-08-20   25000     10000       1

#### Q1. Extract date features

Create signup_year, signup_month, signup_day, and signup_weekday from signup_date using Pandas datetime accessors.

In [24]:
df['signup_year']=df['signup_date'].dt.year
df['signup_month']=df['signup_date'].dt.month
df['signup_day']=df['signup_date'].dt.day
df['signup_weekday']=df['signup_date'].dt.weekday
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,signup_weekday
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,4
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,5
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,3
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,5
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,0
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,2
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,1
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,5
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,6
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,2
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,1
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,5

#### Q2. Calculate customer tenure

Create tenure_days as the number of days between last_order_date and signup_date. Identify any negative tenure values.

In [36]:
df['tenure_days']=(df['last_order_date']-df['signup_date']).dt.days
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,signup_weekday,tenure_days,days_since_last_order
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,4,365,282
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,5,370,241
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,3,360,218
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,5,295,267
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,0,335,190
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,2,334,154
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,1,215,239
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,5,304,132
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,6,181,219
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,2,273,110
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,1,181,161
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,5,243,60

#### Q3. Calculate recency

Using 2026-10-19 as the reference date, create days_since_last_order. Explain what a higher value indicates.

In [34]:
df['days_since_last_order']=(pd.Timestamp('2026-10-19')-df['last_order_date']).dt.days
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,signup_weekday,tenure_days,days_since_last_order
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,4,365,282
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,5,370,241
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,3,360,218
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,5,295,267
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,0,335,190
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,2,334,154
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,1,215,239
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,5,304,132
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,6,181,219
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,2,273,110
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,1,181,161
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,5,243,60

#### Q4. Create customer activity categories

Create recency_status using these rules:
- 0–90 days: Recent
- 91–180 days: Warming
- More than 180 days: Dormant

In [40]:
conditions=[
    df['days_since_last_order'].between(0,90),
    df['days_since_last_order'].between(91,180),
    df['days_since_last_order']>180
    
]
labels=['Recent','Warming','Dormant']
df['recency_status']=np.select(conditions,labels,default='N/A')
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,signup_weekday,tenure_days,days_since_last_order,recency_status
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,4,365,282,Dormant
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,5,370,241,Dormant
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,3,360,218,Dormant
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,5,295,267,Dormant
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,0,335,190,Dormant
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,2,334,154,Warming
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,1,215,239,Dormant
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,5,304,132,Warming
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,6,181,219,Dormant
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,2,273,110,Warming
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,1,181,161,Warming
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,5,243,60,Recent

#### Q5. Create spending efficiency features

Create spending_per_order by dividing spending by orders. Handle zero orders safely.

In [45]:
df['spending_per_order']=df['spending']/df['orders'].where(df['orders']!=0,np.nan)
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,signup_weekday,tenure_days,days_since_last_order,recency_status,spending_per_order
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,4,365,282,Dormant,6000.000000
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,5,370,241,Dormant,4500.000000
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,3,360,218,Dormant,9000.000000
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,5,295,267,Dormant,4166.666667
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,0,335,190,Dormant,5000.000000
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,2,334,154,Warming,5500.000000
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,1,215,239,Dormant,4285.714286
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,5,304,132,Warming,4400.000000
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,6,181,219,Dormant,4250.000000
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,2,273,110,Warming,4666.666667
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,1,181,161,Warming,3500.000000
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,5,243,60,Recent,10000.000000

#### Q6. Calculate city-level metrics

Create city_avg_income and city_avg_spending using groupby() and transform('mean'). Each customer should receive the average for their city.

In [48]:
df['city_avg_income']=df.groupby('city')['income'].transform('mean')
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,signup_weekday,tenure_days,days_since_last_order,recency_status,spending_per_order,city_avg_income
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,4,365,282,Dormant,6000.000000,45000.0
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,5,370,241,Dormant,4500.000000,45750.0
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,3,360,218,Dormant,9000.000000,29000.0
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,5,295,267,Dormant,4166.666667,45000.0
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,0,335,190,Dormant,5000.000000,45750.0
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,2,334,154,Warming,5500.000000,29000.0
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,1,215,239,Dormant,4285.714286,45000.0
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,5,304,132,Warming,4400.000000,45750.0
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,6,181,219,Dormant,4250.000000,29000.0
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,2,273,110,Warming,4666.666667,45000.0
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,1,181,161,Warming,3500.000000,45750.0
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,5,243,60,Recent,10000.000000,29000.0

#### Q7. Create deviation features

Create income_vs_city_avg by subtracting city-average income from each customer's income. Create spending_vs_city_avg similarly.

In [51]:
df['income_vs_city_avg ']=(df.groupby('city')['income'].transform('mean')-df['income'])
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,signup_weekday,tenure_days,days_since_last_order,recency_status,spending_per_order,city_avg_income,income_vs_city_avg
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,4,365,282,Dormant,6000.000000,45000.0,15000.0
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,5,370,241,Dormant,4500.000000,45750.0,750.0
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,3,360,218,Dormant,9000.000000,29000.0,7000.0
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,5,295,267,Dormant,4166.666667,45000.0,-10000.0
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,0,335,190,Dormant,5000.000000,45750.0,7750.0
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,2,334,154,Warming,5500.000000,29000.0,1000.0
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,1,215,239,Dormant,4285.714286,45000.0,-15000.0
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,5,304,132,Warming,4400.000000,45750.0,-6250.0
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,6,181,219,Dormant,4250.000000,29000.0,-12000.0
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,2,273,110,Warming,4666.666667,45000.0,10000.0
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,1,181,161,Warming,3500.000000,45750.0,-2250.0
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,5,243,60,Recent,10000.000000,29000.0,4000.0

#### Q8. Create a composite customer score

Calculate customer_score using these normalized features:
- Income: 40% weight
- Spending: 35% weight
- Orders: 25% weight

In [65]:
# Normalize each feature to a 0–1 range
features = ['income', 'spending', 'orders']

for col in features:
    min_val = df[col].min()
    max_val = df[col].max()

    if max_val != min_val:
        df[f'{col}_normalized'] = (
            (df[col] - min_val) / (max_val - min_val)
        )
    else:
        df[f'{col}_normalized'] = 0.0

# Calculate the composite customer score
df['customer_score'] = (
    df['income_normalized'] * 0.40 +
    df['spending_normalized'] * 0.35 +
    df['orders_normalized'] * 0.25
)

df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,...,tenure_days,days_since_last_order,recency_status,spending_per_order,city_avg_income,income_vs_city_avg,customer_score,income_normalized,spending_normalized,orders_normalized
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,...,365,282,Dormant,6000.000000,45000.0,15000.0,0.175877,0.210526,0.142857,0.166667
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,...,370,241,Dormant,4500.000000,45750.0,750.0,0.517105,0.605263,0.428571,0.500000
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,...,360,218,Dormant,9000.000000,29000.0,7000.0,0.000000,0.000000,0.000000,0.000000
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,...,295,267,Dormant,4166.666667,45000.0,-10000.0,0.822368,0.868421,0.761905,0.833333
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,...,335,190,Dormant,5000.000000,45750.0,7750.0,0.351754,0.421053,0.285714,0.333333
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,...,334,154,Warming,5500.000000,29000.0,1000.0,0.138158,0.157895,0.095238,0.166667
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,...,215,239,Dormant,4285.714286,45000.0,-15000.0,1.000000,1.000000,1.000000,1.000000
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,...,304,132,Warming,4400.000000,45750.0,-6250.0,0.699123,0.789474,0.619048,0.666667
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,...,181,219,Dormant,4250.000000,29000.0,-12000.0,0.458333,0.500000,0.380952,0.500000
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,...,273,110,Warming,4666.666667,45000.0,10000.0,0.303509,0.342105,0.238095,0.333333
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,...,181,161,Warming,3500.000000,45750.0,-2250.0,0.682018,0.684211,0.571429,0.833333
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,...,243,60,Recent,10000.000000,29000.0,4000.0,0.048246,0.078947,0.047619,0.000000

#### Q9. Create a rule-based customer segment

Create customer_segment using the following rules:
- High Value: income at least 50,000 and orders at least 5
- Regular: income at least 30,000 and orders at least 2
- Low Activity: all remaining customers
Ensure the conditions are evaluated in the correct order.

In [68]:
conditions=[
    ((df['income']>=50000) & (df['orders']>=5)),
    ((df['income']>=30000) & (df['orders']>=2))
]
labels=['High Value','Regular']

df['customer_segment']=np.select(conditions,labels,default='Low Activity')
df

,customer_id,city,signup_date,last_order_date,income,spending,orders,signup_year,signup_month,signup_day,...,days_since_last_order,recency_status,spending_per_order,city_avg_income,income_vs_city_avg,customer_score,income_normalized,spending_normalized,orders_normalized,customer_segment
0,401,Delhi,2025-01-10,2026-01-10,30000,12000,2,2025,1,10,...,282,Dormant,6000.000000,45000.0,15000.0,0.175877,0.210526,0.142857,0.166667,Regular
1,402,Mumbai,2025-02-15,2026-02-20,45000,18000,4,2025,2,15,...,241,Dormant,4500.000000,45750.0,750.0,0.517105,0.605263,0.428571,0.500000,Regular
2,403,Pune,2025-03-20,2026-03-15,22000,9000,1,2025,3,20,...,218,Dormant,9000.000000,29000.0,7000.0,0.000000,0.000000,0.000000,0.000000,Low Activity
3,404,Delhi,2025-04-05,2026-01-25,55000,25000,6,2025,4,5,...,267,Dormant,4166.666667,45000.0,-10000.0,0.822368,0.868421,0.761905,0.833333,High Value
4,405,Mumbai,2025-05-12,2026-04-12,38000,15000,3,2025,5,12,...,190,Dormant,5000.000000,45750.0,7750.0,0.351754,0.421053,0.285714,0.333333,Regular
5,406,Pune,2025-06-18,2026-05-18,28000,11000,2,2025,6,18,...,154,Warming,5500.000000,29000.0,1000.0,0.138158,0.157895,0.095238,0.166667,Low Activity
6,407,Delhi,2025-07-22,2026-02-22,60000,30000,7,2025,7,22,...,239,Dormant,4285.714286,45000.0,-15000.0,1.000000,1.000000,1.000000,1.000000,High Value
7,408,Mumbai,2025-08-09,2026-06-09,52000,22000,5,2025,8,9,...,132,Warming,4400.000000,45750.0,-6250.0,0.699123,0.789474,0.619048,0.666667,High Value
8,409,Pune,2025-09-14,2026-03-14,41000,17000,4,2025,9,14,...,219,Dormant,4250.000000,29000.0,-12000.0,0.458333,0.500000,0.380952,0.500000,Regular
9,410,Delhi,2025-10-01,2026-07-01,35000,14000,3,2025,10,1,...,110,Warming,4666.666667,45000.0,10000.0,0.303509,0.342105,0.238095,0.333333,Regular
10,411,Mumbai,2025-11-11,2026-05-11,48000,21000,6,2025,11,11,...,161,Warming,3500.000000,45750.0,-2250.0,0.682018,0.684211,0.571429,0.833333,Regular
11,412,Pune,2025-12-20,2026-08-20,25000,10000,1,2025,12,20,...,60,Recent,10000.000000,29000.0,4000.0,0.048246,0.078947,0.047619,0.000000,Low Activity